all.js:46: WARNING - If this if/for/while really shouldn't have a body, use {}
	for (var d = 1; d < arguments.length; ++d);
	                                          ^

0 error(s), 1 warning(s)
var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var c=0;return{next:function(){return c==a.length?{done:!0}:{done:!1,value:a[c++]}}}};$jscomp.arrayFromIterator=function(a){for(var c,d=[];!(c=a.next()).done;)d.push(c.value);return d};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.arrayFromArguments=function(a){for(var c=[],d=0;d<a.length;d++)c.push(a[d]);return c};
$jscomp.inherits=function(a,c){function d(){}d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;for(var f in c)if($jscomp.global.Object.defineProperties){var g=$jscomp.global.Object.getOwnPropertyDescriptor(c,f);void 0!==g&&$jscomp.global.Object.defineProperty(a,f,g)}else a[f]=c[f]};var k="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function w(){k.Symbol||(k.Symbol=x);w=function(){}}var aa=0;function x(a){return"jscomp_symbol_"+a+aa++}
function y(){w();k.Symbol.iterator||(k.Symbol.iterator=k.Symbol("iterator"));y=function(){}}function z(a){y();if(a[k.Symbol.iterator])return a[k.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var c=0;return{next:function(){return c==a.length?{done:!0}:{done:!1,value:a[c++]}}}}
function A(a,c){function d(){}d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;for(var f in c)if(k.Object.defineProperties){var g=k.Object.getOwnPropertyDescriptor(c,f);void 0!==g&&k.Object.defineProperty(a,f,g)}else a[f]=c[f]}var B={};window.NLA=B;var C=B.sb=function(){return!0};B.rb=function(a,c){for(var d=1;d<arguments.length;++d);return!0};var D=B.ga=function(){return!0};function E(){}B.m=1/67108864;console.log("NLA.PRECISION",B.m);B.b=function(a){return Math.abs(a)<B.m};
B.Ra=function(a,c){return Math.abs(a)<c};B.g=function(a,c){return Math.abs(a-c)<=B.m};B.Pb=function(a,c){return a+B.m<c};B.Gb=function(a,c){return a>c+B.m};B.Ob=function(a,c){return a<=c+B.m};B.Eb=function(a,c){return a+B.m>=c};B.Ia=function(a,c){return Math.abs(1-a)<c};B.Bb=function(a,c){return B.Ua(a-c)};B.Ua=function(a){return(a%(2*Math.PI)+2*Math.PI+B.m)%(2*Math.PI)<2*B.m};B.Vb=function(a,c){return Math.abs(a-c)<=B.m?c:a};B.vb=function(a){return(a%(2*Math.PI)+2*Math.PI)%(2*Math.PI)};
B.ka=function(a){if(0==a)return"";a*=1;for(var c=a/2,d=" ";d.length<=c;)d+=d;return d+d.substring(0,a-d.length)};B.Rb=function(a,c){return(a%c+c)%c};B.T=function(a,c,d){var f=a[c];a[c]=a[d];a[d]=f};B.H=function(a,c,d,f,g){f+=g;for(g+=c;g-- >c;)d[--f]=a[g]};B.wb=function(a,c,d){return Math.max(c,Math.min(d,a))};function F(a){this.h=new Map;this.o=0;if(a){a=z(a);for(var c=a.next();!c.done;c=a.next())ba(this,c.value)}}
F.prototype={delete:function(a){var c=a.K();if(c=this.h.get(c)){var d=c.findIndex(function(c){return c.g(a)});if(-1!=d)return 1==c.size?this.h.delete(c):c.splice(d,1),this.o--,!0}return!1},za:function(){function a(a,q){for(;;)switch(c){case 0:e=z(b.h),h=e.next();case 1:if(h.done){c=3;break}g=h.value;f=z(g);case 4:if((d=f.next(a)).done){c=5;break}c=6;return{value:d.value,done:!1};case 6:if(void 0===q){c=7;break}c=-1;throw q;case 7:c=4;break;case 5:case 2:h=e.next();c=1;break;case 3:c=-1;default:return{value:void 0,
done:!0}}}var c=0,d,f,g,h,e,b=this,q={next:function(b){return a(b,void 0)},throw:function(b){return a(void 0,b)}};y();$jscomp.initSymbol();$jscomp.initSymbolIterator();q[Symbol.iterator]=function(){return this};return q},clear:function(){this.h.clear();this.o=0},get size(){return this.o}};function ca(a,c){return da(a,c)||ea(a,c)}function da(a,c){for(var d=z(c.Ma()),f=d.next();!f.done;f=d.next())if(f=(f=a.h.get(f.value))&&f.find(function(a){return a.L(c)}))return f}
function ea(a,c){var d=c.K(),f=a.h.get(d);if(f){if(d=f.find(function(a){return a.g(c)}))return d;f.push(c)}else a.h.set(d,[c]);a.o++;return c}function ba(a,c){var d=c.K(),f=a.h.get(d);if(f){if(f.some(function(a){return a.g(c)}))return;f.push(c)}else a.h.set(d,[c]);a.o++}w();y();$jscomp.initSymbol();$jscomp.initSymbolIterator();F.prototype[Symbol.iterator]=F.prototype.za;B.Tb=function(){return Math.floor(16777216*Math.random())};B.Qb=function(a,c,d){var f=a.get(c);f?f.push(d):a.set(c,[d])};
B.ea=function(a){B.G(a,G.prototype)};
var H={Sb:function(a){Array.prototype.push.apply(this,a)},zb:function(a,c,d,f,g,h,e){var b=c+e*d;for(g+=e*h;b>c;)f[g-=h]=a[b-=d]},na:function(a,c,d){d=d||1;for(var f=Array(Math.ceil((this.length-a)/c)),g=0,h=0;h<this.length;h+=c)for(var e=0;e<d;e++)f[g++]=this[a+h+e];return f},yb:function(){return Array.prototype.concat.apply([],this)},min:function(){return Math.min.apply(null,this)},max:function(){return Math.max.apply(null,this)},Ib:function(a){if(0==this.length)return 0;for(var c=this.length,d=
-1,f=-Infinity;c--;){var g=a(this[c],c);g>f&&(f=g,d=c)}return d},$b:function(a){for(var c=this.length,d=void 0,f=-Infinity;c--;){var g=this[c],h=a(g);h>f&&(f=h,d=g)}return d},Va:function(){for(var a=this.length,c=0;a--;)c+=Math.abs(this[a]);return c},Wb:function(){for(var a=this.length,c=0;a--;)c+=this[a];return c},Lb:function(){return 0==this.length},Xa:function(){var a=new Set(this);return Array.h(a)},remove:function(a){a=this.indexOf(a);-1!=a&&this.splice(a,1)},Ub:function(a){for(var c=a.length;c--;)this.remove(a[c])},
Wa:function(a){var c=this.indexOf(a);-1!=c?this.splice(c,1):this.push(a)},tb:function(a,c){for(var d=0,f=this.length-1,g,h;d<=f;)if(g=(d+f)/2|0,h=this[g],0>c(h,a))d=g+1;else if(0<c(h,a))f=g-1;else return g;return-d-1},ub:function(a,c){c=c||B.l;for(var d=0,f=this.length,g,h;d<f;)g=~~((d+f)/2),h=this[g],0>c(h,a)?d=g+1:f=g;this.splice(d,0,a)}};B.l=function(a,c){return a-c};var I={key:void 0},J;
for(J in H){I.key=J;var M=I.key;B["array"+(M.charAt(0).toUpperCase()+M.slice(1))]=function(a){return function(c,d){for(var f=[],g=1;g<arguments.length;++g)f[g-1]=arguments[g];H[a.key].apply(c,f)}}(I);I={key:I.key}}B.R=function(a,c,d,f,g,h,e){var b=c+e*d;for(g+=e*h;b>c;)f[g-=h]=a[b-=d]};B.nb=function(a,c,d,f,g,h,e,b){for(var q=0;q<b;q++)B.H(a,c+d*q,f,g+h*q,e)};B.qb=function(a,c,d){console.log(Math.ceil((c-a)/d));a=Array(Math.ceil((c-a)/d));for(var f=0,g=0;g<c;g+=d)a[f++]=g;return a};
B.S=function(a,c){for(var d=Array(a),f=a;f--;)d[f]=c(f);return d};function N(a){this.c=a}B.mb=function(){E(arguments[0]instanceof Float64Array||arguments.every(function(a){return"number"==typeof a}));return new N(arguments[0]instanceof Float64Array?arguments[0]:Float64Array.h(arguments))};
N.prototype={A:function(a){var c=this.c;a=a.c;for(var d=new Float64Array(c.length),f=c.length;f--;)d[f]=c[f]+a[f];return new N(d)},l:function(a){var c=this.c;a=a.c;for(var d=new Float64Array(c.length),f=c.length;f--;)d[f]=c[f]-a[f];return new N(d)},J:function(a){for(var c=this.c,d=new Float64Array(c.length),f=c.length;f--;)d[f]=c[f]/a;return new N(d)},i:function(a){var c=0,d=this.c;a=a.c;for(var f=d.length;f--;)c+=d[f]*a[f];return c},w:function(a){for(var c=this.c,d=new Float64Array(c.length),f=c.length;f--;)d[f]=
c[f]*a;return new N(d)},s:function(a){var c=new Float64Array(3);c[0]=this.c[1]*a.c[2]-this.c[2]*a.c[1];c[1]=this.c[2]*a.c[0]-this.c[0]*a.c[2];c[2]=this.c[0]*a.c[1]-this.c[1]*a.c[0];return new N(c)},g:function(a){if(a===this)return!0;if(a.constructor==N||this.c.length!=a.c.length)return!1;for(var c=this.c.length;c--;)if(!B.g(this.c[c],a.c[c]))return!1;return!0},map:function(a){for(var c=new Float64Array(this.c.length),d=c.length;d--;)c[d]=a(d);return new N(c)},toString:function(a){a=a||function(c){return+c.toFixed(6)};
return"NLA.Vector("+this.c.map(a).join(", ")+")"},fa:function(a){this.b();a.b();return Math.acos(this.i(a)/this.length()/a.length())},b:function(){return B.b(this.length())},length:function(){return Math.sqrt(this.ia())},ia:function(){for(var a=0,c=this.c,d=c.length;d--;)a+=c[d]*c[d];return a},v:function(){var a=this.length();if(B.b(a))throw Error("cannot normalize zero vector");return this.J(this.length())},Z:function(a){return B.g(a,this.length())}};
B.G=function(a,c){c&&Object.getOwnPropertyNames(c).forEach(function(d){c.hasOwnProperty(d)&&(a.hasOwnProperty(d)&&console.warn("target ",a," already has property ",d),Object.defineProperty(a,d,Object.getOwnPropertyDescriptor(c,d)))})};B.Ab=function(a,c,d,f,g){d.prototype=B.Ga(c&&c.prototype,f);d.prototype.constructor=d;d.prototype.name=a;B.G(d,g);return d};B.Fa=function(a){return Math.la(a,-4)};B.Ga=function(a,c){var d=Object.create(a||O);B.G(d,c);return d};function O(){}A(O,Object);
O.prototype.toSource=function(){return this.toString==Object.prototype.toString?Object.prototype.toSource.apply(this):this.toString()};B.Db=function(a){a=parseFloat(a.replace(",",".").replace(/^[^0-9,\.\-]/,""));return Number.isFinite(a)?a:0};
(function(){function a(c,a,f){if("undefined"===typeof f||0===+f)return Math[c](a);a=+a;f=+f;if(isNaN(a)||"number"!==typeof f||0!==f%1)return NaN;a=a.toString().split("e");a=Math[c](+(a[0]+"e"+(a[1]?+a[1]-f:-f)));a=a.toString().split("e");return+(a[0]+"e"+(a[1]?+a[1]+f:f))}Math.la||(Math.la=function(c,d){return a("round",c,d)});Math.Ja||(Math.Ja=function(c,d){return a("floor",c,d)});Math.Ea||(Math.Ea=function(c,d){return a("ceil",c,d)})})();function P(a,c,d){this.a=d;this.width=a;this.height=c}
function Q(a){for(var c=new Float64Array(a*a),d=a*(a+1);d;)d-=a+1,c[d]=1;return new P(a,a,c)}function R(a){if(0==a.length)throw Error("cannot have 0 vector");var c=a.length,d=a[0].length,f=new Float64Array(c*d);B.H(a[0],0,f,0,d);for(var g=1;g<c;g++){if(a[g].length!=d)throw Error("all row arrays must be the same length");B.H(a[g],0,f,g*d,d)}return new P(d,c,f)}function S(a){return fa(a.map(function(c){return c.c}))}
function fa(a){if(0==a.length)throw Error("cannot have 0 vector");var c=a.length,d=a[0].length,f=new Float64Array(d*c);B.R(a[0],0,1,f,0,c,d);for(var g=1;g<c;g++){if(a[g].length!=d)throw Error("all col arrays must be the same length");B.R(a[g],0,1,f,g,c,d)}return new P(c,d,f)}
P.prototype={toString:function(a){var c=this;a=a||function(c){return c.toFixed(3)};E("string"==typeof a(0),""+typeof a(0));var d=Array.prototype.slice.call(this.a).map(a),f=B.S(this.width,function(a){return d.na(a,c.width).map(function(c){return c.length}).max()});return B.S(this.height,function(a){return d.slice(a*c.width,(a+1)*c.width).map(function(c,e){return B.ka(f[e]-c.length)+c}).join(" ")}).map(function(c){return c+"\n"}).join("")},g:function(a){if(a.constructor!=P||this.width!=a.width||this.height!=
a.height)return!1;for(var c=this.a.length;c--;)if(this.a[c]!=a.a[c])return!1},K:function(){for(var a=0,c=this.a.length;c--;)a=31*a+B.Cb(this.a[c]);return a},Pa:function(){var a;if(a=this.height==this.width)a:{a=this.oa().w(this);var c=Q(this.width),d;d=d||B.m;if(!(c instanceof P))throw Error("not a matrix");if(a.width!=c.width||a.height!=c.height)a=!1;else{for(var f=a.a.length;f--;)if(Math.abs(a.a[f]-c.a[f])>=d){a=!1;break a}a=!0}}return a},Na:function(a){a:if(a="number"==typeof a?a:B.m,this.height==
this.width){for(var c=0;c<this.height-1;c++)for(var d=c;d<this.width;d++){var f=this.a[c*this.width+d];if(c==d?!B.Ia(f,a):!B.Ra(f,a)){a=!1;break a}}a=!0}else a=!1;return a&&T(this)},map:function(a){return new P(this.width,this.height,this.a.map(a))},$:function(){var a=ga(this),c;c=a.ta;for(var d=a.Aa,f=Array(d.width),g=d.width;g--;){var h=g,e;e=c;var b=U(d,g);a:{var q=e;if(q.height==q.width)for(var t=0;t<q.height-1;t++)for(var r=t+1;r<q.width;r++)if(!B.b(q.a[t*q.width+r]))break a}q=new Float64Array(e.width);
for(t=0;t<e.height;t++){for(var r=b.c[t],l=0;l<t;l++)r-=q[l]*e.a[t*e.width+l];q[t]=r/e.a[t*e.width+t]}e=new N(q);f[h]=e}c=S(f);a=a.Ca;d=Array(c.width);for(f=c.width;f--;){g=f;h=a;e=U(c,f);T(h);b=new Float64Array(h.width);for(q=h.height;q--;){t=e.c[q];for(r=q+1;r<h.width;r++)t-=b[r]*h.a[q*h.width+r];b[q]=t/h.a[q*h.width+q]}h=new N(b);d[g]=h}return S(d)},w:function(a){for(var c=a.width,d=this.height,f=this.width,g=new Float64Array(c*d),h=d;h--;)for(var e=c;e--;){for(var b=0,q=f;q--;)b+=this.a[h*f+q]*
a.a[q*c+e];g[h*c+e]=b}return new P(c,d,g)},oa:function(){for(var a=this.height,c=this.width,d=new Float64Array(a*c),f=c;f--;)for(var g=a;g--;)d[f*a+g]=this.a[g*c+f];return new P(a,c,d)},max:function(){return B.ob(this.a)},min:function(){return B.pb(this.a)}};function Y(a){for(var c=Float64Array,c=c||Float64Array,d=a.height,f=Array(a.height);d--;){var g=d,h=a,e=d,b=c,b=b||Float64Array,b=new b(h.width);B.H(h.a,e*h.width,b,0,h.width);f[g]=b}return f}
function T(a){if(a.height!=a.width)return!1;for(var c=1;c<a.height;c++)for(var d=0;d<c;d++)if(!B.b(a.a[c*a.width+d]))return!1;return!0}function ga(a){var c=Y(a),d=a.width;a=B.S(d,function(){return new Float64Array(d)});for(var f=Y(Q(d)),g=0;g<d;g++){for(var h=0,e=d,b=g;--e>=g;)Math.abs(c[e][g])>=h&&(h=Math.abs(c[e][g]),b=e);B.T(c,g,b);B.T(a,g,b);B.T(f,g,b);a[g][g]=1;for(e=g+1;e<d;e++)for(h=c[e][g]/c[g][g],a[e][g]=h,b=g;b<d;b++)c[e][b]-=h*c[g][b]}return{ta:R(a),Ca:R(c),Aa:R(f)}}
function U(a,c){var d=new Float64Array(a.height);B.R(a.a,c,a.width,d,0,1,a.height);return new N(d)}
B.xb=function(a){function c(c){for(;;)switch(d){case 0:g=0;case 1:if(!(g<a)){d=3;break}f=g;case 4:if(!(f<a)){d=6;break}d=7;return{value:{Hb:g,Nb:f},done:!1};case 7:if(void 0===c){d=8;break}d=-1;throw c;case 8:case 5:f++;d=4;break;case 6:case 2:g++;d=1;break;case 3:d=-1;default:return{value:void 0,done:!0}}}var d=0,f,g,h={next:function(){return c(void 0)},throw:function(h){return c(h)}};y();$jscomp.initSymbol();$jscomp.initSymbolIterator();h[Symbol.iterator]=function(){return this};return h};
function G(){}A(G,O);B.G(Array.prototype,H);B||(window.hb={});
(function(a){function c(a,h,e){if(3==arguments.length)return c.create(parseFloat(a),parseFloat(h),parseFloat(e));if(2==arguments.length)return c.create(parseFloat(a),parseFloat(h),0);if(1==arguments.length&&"object"==typeof a){if(a instanceof c)return a;if(a instanceof Array||a instanceof Float32Array||a instanceof Float64Array){if(2==a.length)return c.create(parseFloat(a[0]),parseFloat(a[1]),0);if(3==a.length)return c.create(parseFloat(a[0]),parseFloat(a[1]),parseFloat(a[2]))}else if("x"in a&&"y"in
a)return"z"in a?c.create(parseFloat(a.x),parseFloat(a.y),parseFloat(a.z)):c.create(parseFloat(a.x),parseFloat(a.y),0)}throw Error("invalid arguments"+arguments);}var d=B.assert,f=B.ga;c.ba=0;c.create=function(a,h,e){d(3==arguments.length);f(a,h,e);var b=Object.create(c.prototype);Object.defineProperties(b,{x:{value:a},y:{value:h},z:{value:e}});return b};c.prototype={ja:function(c,h){h=h||.8*B.m;return this.map(function(c){return c+(Math.random()-.5)*h})},abs:function(){return c.create(Math.abs(this.x),
Math.abs(this.y),Math.abs(this.z))},A:function(a){d(a instanceof c);return c.create(this.x+a.x,this.y+a.y,this.z+a.z)},l:function(a){d(a instanceof c);return c.create(this.x-a.x,this.y-a.y,this.z-a.z)},w:function(a){f(a);return c.create(this.x*a,this.y*a,this.z*a)},J:function(a){f(a);return c.create(this.x/a,this.y/a,this.z/a)},i:function(a){d(a instanceof c,"a instanceof V3");return this.x*a.x+this.y*a.y+this.z*a.z},ia:function(){return this.i(this)},V:function(a){d(a instanceof c,"a instanceof V3");
return this.l(a).length()},min:function(a){return c.create(Math.min(this.x,a.x),Math.min(this.y,a.y),Math.min(this.z,a.z))},max:function(a){return c.create(Math.max(this.x,a.x),Math.max(this.y,a.y),Math.max(this.z,a.z))},g:function(c){return this==c||this.x==c.x&&this.y==c.y&&this.z==c.z},s:function(a){return c.create(this.y*a.z-this.z*a.y,this.z*a.x-this.x*a.z,this.x*a.y-this.y*a.x)},M:function(){return this.J(this.length())},La:function(){if(B.b(this.x)&&B.b(this.y)){if(B.b(this.z))throw Error("zero vector");
return c.F}return c(-this.y,this.x,0)},map:function(a){return c.create(a(this.x),a(this.y),a(this.z))},toString:function(c){c=c||B.Fa;return"V3("+[this.x,this.y,this.z].map(c).join(", ")+")"},fa:function(a){d(1==arguments.length);d(a instanceof c,"vector instanceof V3");d(!this.b());d(!a.b());return Math.acos(this.i(a)/this.length()/a.length())},length:function(){return Math.sqrt(this.x*this.x+this.y*this.y+this.z*this.z)},b:function(){return this.L(c.ZERO)},L:function(a){return a===this?!0:a instanceof
c?B.g(this.x,a.x)&&B.g(this.y,a.y)&&B.g(this.z,a.z):!1},v:function(){d(!this.b(),"cannot normalize zero vector");return this.J(this.length())},Z:function(c){return B.g(c,this.length())},transform:function(c){d(c instanceof B.ya);return c.C(this)},get ca(){return this.toString()},K:function(){return~~(31*(31*~~(268435456*this.x)+~~(268435456*this.y))+~~(268435456*this.z))},Ma:function(){var c=~~(31*(31*~~(268435456*this.x-.5)+~~(268435456*this.y-.5))+~~(268435456*this.z-.5));return[~~c,~~(c+961),~~(c+
31),~~(c+31+961),~~(c+1),~~(c+1+961),~~(c+1+31),~~(c+1+31+961)]}};c.prototype.toSource=c.prototype.toString;c.random=function(){return c(Math.random(),Math.random(),Math.random())};c.ra=function(){var a=2*Math.random()*Math.PI,h=2*Math.random()-1,e=Math.sqrt(1-h*h);return c(e*Math.cos(a),e*Math.sin(a),h)};c.W=function(a,h){return c.create(Math.cos(a)*Math.cos(h),Math.sin(h),Math.sin(a)*Math.cos(h))};c.aa=function(a){return c.create(a(0),a(1),a(2))};c.ca=function(c){return c.ca};c.min=function(a,h){return c.create(Math.min(a.x,
h.x),Math.min(a.y,h.y),Math.min(a.z,h.z))};c.max=function(a,h){return c.create(Math.max(a.x,h.x),Math.max(a.y,h.y),Math.max(a.z,h.z))};c.ma=function(c,a,e){return a.l(c).w(e).A(c)};c.X=function(a){return c.create(a[0],a[1],a[2])};c.h=function(c,a){return c.fa(a)};c.sa=function(a,h){for(var e=[],b=1;b<arguments.length;++b)e[b-1]=arguments[b];d(a instanceof Function);return c.create(a.apply(void 0,e.map(function(b){return b.x})),a.apply(void 0,e.map(function(b){return b.y})),a.apply(void 0,e.map(function(b){return b.z})))};
c.pa=function(a,h,e){d(a instanceof c,"v0 instanceof V3");d(h instanceof c,""+h.toString());d(e instanceof c,"v2 instanceof V3");return h.l(a).s(e.l(a))};c.Y=function(a){for(var h=[],e=0;e<arguments.length;++e)h[e-0]=arguments[e];d(h.every(function(b){return b instanceof c}));for(var b=e=0,q=0,f=h.length;f--;)e+=h[f].x,b+=h[f].y,q+=h[f].z;return c.create(e,b,q)};c.Ta=function(a){for(var h=[],e=0;e<arguments.length;++e)h[e-0]=arguments[e];d(h.every(function(b){return b instanceof c}));for(var e=h[0].x,
b=h[0].y,q=h[0].z,f=h.length,f=1;f<h.length;f++)e-=h[f].x,b-=h[f].y,q-=h[f].z;return c.create(e,b,q)};c.D=function(c,a,e,b,q){e=e||0;b=b||0;q=q||c.length-e;a=a||new Float32Array(3*q);d(a.length-b>=q,"dest.length - destStart >= v3count");for(var f=0;f<q;f++){var r=c[e+f];a[b+3*f]=r.x;a[b+3*f+1]=r.y;a[b+3*f+2]=r.z}return a};c.ja=function(c,a){return c.ja(a)};c.qa=function(a,h){return c.create(a*Math.cos(h),a*Math.sin(h),0)};c.o=function(c){for(var a=new F,e;e=c.next().value;)if(!e.g(ca(a,e)))return!1;
return!0};Object.defineProperties(c,{ZERO:{value:c.create(0,0,0)},O:{value:c.create(1,0,0)},F:{value:c.create(0,1,0)},P:{value:c.create(0,0,1)},bb:{value:c.create(Infinity,Infinity,Infinity)}});a.B=c})(B);if(!B.B)throw Error("Define NLA.V3 first");
(function(a){function c(){var a;a=0==arguments.length?new Float64Array(16):new Float64Array(Array.prototype.concat.apply([],arguments));var e=Object.create(c.prototype);Object.defineProperty(e,"m",{value:a});return e}var d=B.B;c.prototype=Object.create(P.prototype);var f={$:function(){return c.Y(this)},trace:function(){return this.a[0]+this.a[5]+this.a[10]+this.a[15]},Sa:function(c){return this.a.every(function(a,b){return B.g(a,c.a[b])})},oa:function(){return c.o(this)},w:function(a){return c.h(this,
a)},C:function(c){C(c);var a=this.a,b=c.x,f=c.y;c=c.z;var t=b*a[12]+f*a[13]+c*a[14]+1*a[15];return d.create((b*a[0]+f*a[1]+c*a[2]+1*a[3])/t,(b*a[4]+f*a[5]+c*a[6]+1*a[7])/t,(b*a[8]+f*a[9]+c*a[10]+1*a[11])/t)},da:function(a){C(a);var c=this.a;return d.create(c[0]*a.x+c[1]*a.y+c[2]*a.z,c[4]*a.x+c[5]*a.y+c[6]*a.z,c[8]*a.x+c[9]*a.y+c[10]*a.z)},Yb:function(a){var c=this;return a.map(function(b){return c.C(b)})},Zb:function(a){var c=this;return a.map(function(b){return c.da(b)})},A:function(a){for(var e=
c(),b=0;16>b;b++)e.a[b]=this.a[b]+a.a[b];return e},l:function(a){for(var e=c(),b=0;16>b;b++)e.a[b]=this.a[b]-a.a[b];return e},Xb:function(a){for(var e=c(),b=0;16>b;b++)e.a[b]=this.a[b]*a;return e},Ha:function(a){for(var e=c(),b=0;16>b;b++)e.a[b]=this.a[b]/a;return e},clone:function(){return c.I(this)},I:function(){return c.I(this)},Mb:function(){return!B.b(this.U())},Kb:function(){var a=this.a;return 1>=!B.b(a[0])+!B.b(a[1])+!B.b(a[2])&&1>=!B.b(a[4])+!B.b(a[5])+!B.b(a[6])&&1>=!B.b(a[8])+!B.b(a[9])+
!B.b(a[10])},Pa:function(){var a=c.aa,e=c.ba;c.o(this,a);c.h(this,a,e);c.D(a);return a.Sa(e)},U:function(){var a=this.a,c=a[4],b=a[5],d=a[6],f=a[7],g=a[8],l=a[9],n=a[10],p=a[11],u=a[12],v=a[13],K=a[14],L=a[15],V=n*L-p*K,W=l*L-p*v,X=l*K-n*v,p=g*L-p*u,n=g*K-n*u,g=g*v-l*u;return a[0]*(b*V-d*W+f*X)-a[1]*(c*V-d*p+f*n)+a[2]*(c*W-b*p+f*g)-a[3]*(c*X-b*n+d*g)},Oa:function(){return 0>this.U()},Fb:function(){var a=this.a,c=a[15];return d.create(a[3]/c,a[7]/c,a[11]/c)},v:function(){var a=this.U();return 1==a?
this:this.Ha(Math.sqrt(Math.sqrt(a)))},Jb:function(){var a=this.a;return B.g(1,a[15])&&B.b(a[12])&&B.b(a[13])&&B.b(a[14])&&B.b(a[3])&&B.b(a[7])&&B.b(a[11])},Na:function(){return this.a.every(function(a,c){return(c/4|0)==c%4?B.g(1,a):B.b(a)})},toString:function(a){a=a||function(a){return a.toFixed(6).replace(/(0|\.)(?=0*$)/g," ").toString()};E("string"==typeof a(0),""+typeof a(0));var c=Array.prototype.slice.call(this.a).map(a),b=[0,1,2,3].map(function(a){return c.na(a,4).map(function(a){return a.length}).max()});
return[0,1,2,3].map(function(a){return c.slice(4*a,4*a+4).map(function(a,c){return B.ka(b[c]-a.length)+a}).join(" ")}).join("\n")}},g;for(g in f)c.prototype[g]=f[g];c.Y=function(a){var e;e=e||c();var b=a.a;a=e.a;a[0]=b[5]*b[10]*b[15]-b[5]*b[14]*b[11]-b[6]*b[9]*b[15]+b[6]*b[13]*b[11]+b[7]*b[9]*b[14]-b[7]*b[13]*b[10];a[1]=-b[1]*b[10]*b[15]+b[1]*b[14]*b[11]+b[2]*b[9]*b[15]-b[2]*b[13]*b[11]-b[3]*b[9]*b[14]+b[3]*b[13]*b[10];a[2]=b[1]*b[6]*b[15]-b[1]*b[14]*b[7]-b[2]*b[5]*b[15]+b[2]*b[13]*b[7]+b[3]*b[5]*
b[14]-b[3]*b[13]*b[6];a[3]=-b[1]*b[6]*b[11]+b[1]*b[10]*b[7]+b[2]*b[5]*b[11]-b[2]*b[9]*b[7]-b[3]*b[5]*b[10]+b[3]*b[9]*b[6];a[4]=-b[4]*b[10]*b[15]+b[4]*b[14]*b[11]+b[6]*b[8]*b[15]-b[6]*b[12]*b[11]-b[7]*b[8]*b[14]+b[7]*b[12]*b[10];a[5]=b[0]*b[10]*b[15]-b[0]*b[14]*b[11]-b[2]*b[8]*b[15]+b[2]*b[12]*b[11]+b[3]*b[8]*b[14]-b[3]*b[12]*b[10];a[6]=-b[0]*b[6]*b[15]+b[0]*b[14]*b[7]+b[2]*b[4]*b[15]-b[2]*b[12]*b[7]-b[3]*b[4]*b[14]+b[3]*b[12]*b[6];a[7]=b[0]*b[6]*b[11]-b[0]*b[10]*b[7]-b[2]*b[4]*b[11]+b[2]*b[8]*b[7]+
b[3]*b[4]*b[10]-b[3]*b[8]*b[6];a[8]=b[4]*b[9]*b[15]-b[4]*b[13]*b[11]-b[5]*b[8]*b[15]+b[5]*b[12]*b[11]+b[7]*b[8]*b[13]-b[7]*b[12]*b[9];a[9]=-b[0]*b[9]*b[15]+b[0]*b[13]*b[11]+b[1]*b[8]*b[15]-b[1]*b[12]*b[11]-b[3]*b[8]*b[13]+b[3]*b[12]*b[9];a[10]=b[0]*b[5]*b[15]-b[0]*b[13]*b[7]-b[1]*b[4]*b[15]+b[1]*b[12]*b[7]+b[3]*b[4]*b[13]-b[3]*b[12]*b[5];a[11]=-b[0]*b[5]*b[11]+b[0]*b[9]*b[7]+b[1]*b[4]*b[11]-b[1]*b[8]*b[7]-b[3]*b[4]*b[9]+b[3]*b[8]*b[5];a[12]=-b[4]*b[9]*b[14]+b[4]*b[13]*b[10]+b[5]*b[8]*b[14]-b[5]*b[12]*
b[10]-b[6]*b[8]*b[13]+b[6]*b[12]*b[9];a[13]=b[0]*b[9]*b[14]-b[0]*b[13]*b[10]-b[1]*b[8]*b[14]+b[1]*b[12]*b[10]+b[2]*b[8]*b[13]-b[2]*b[12]*b[9];a[14]=-b[0]*b[5]*b[14]+b[0]*b[13]*b[6]+b[1]*b[4]*b[14]-b[1]*b[12]*b[6]-b[2]*b[4]*b[13]+b[2]*b[12]*b[5];a[15]=b[0]*b[5]*b[10]-b[0]*b[9]*b[6]-b[1]*b[4]*b[10]+b[1]*b[8]*b[6]+b[2]*b[4]*b[9]-b[2]*b[8]*b[5];for(var b=b[0]*a[0]+b[1]*a[4]+b[2]*a[8]+b[3]*a[12],d=16;d--;)a[d]/=b;return e};c.o=function(a,e){e=e||c();var b=a.a,d=e.a;d[0]=b[0];d[1]=b[4];d[2]=b[8];d[3]=b[12];
d[4]=b[1];d[5]=b[5];d[6]=b[9];d[7]=b[13];d[8]=b[2];d[9]=b[6];d[10]=b[10];d[11]=b[14];d[12]=b[3];d[13]=b[7];d[14]=b[11];d[15]=b[15];return e};c.h=function(a,e,b){b=b||c();a=a.a;e=e.a;var d=b.a;d[0]=a[0]*e[0]+a[1]*e[4]+a[2]*e[8]+a[3]*e[12];d[1]=a[0]*e[1]+a[1]*e[5]+a[2]*e[9]+a[3]*e[13];d[2]=a[0]*e[2]+a[1]*e[6]+a[2]*e[10]+a[3]*e[14];d[3]=a[0]*e[3]+a[1]*e[7]+a[2]*e[11]+a[3]*e[15];d[4]=a[4]*e[0]+a[5]*e[4]+a[6]*e[8]+a[7]*e[12];d[5]=a[4]*e[1]+a[5]*e[5]+a[6]*e[9]+a[7]*e[13];d[6]=a[4]*e[2]+a[5]*e[6]+a[6]*e[10]+
a[7]*e[14];d[7]=a[4]*e[3]+a[5]*e[7]+a[6]*e[11]+a[7]*e[15];d[8]=a[8]*e[0]+a[9]*e[4]+a[10]*e[8]+a[11]*e[12];d[9]=a[8]*e[1]+a[9]*e[5]+a[10]*e[9]+a[11]*e[13];d[10]=a[8]*e[2]+a[9]*e[6]+a[10]*e[10]+a[11]*e[14];d[11]=a[8]*e[3]+a[9]*e[7]+a[10]*e[11]+a[11]*e[15];d[12]=a[12]*e[0]+a[13]*e[4]+a[14]*e[8]+a[15]*e[12];d[13]=a[12]*e[1]+a[13]*e[5]+a[14]*e[9]+a[15]*e[13];d[14]=a[12]*e[2]+a[13]*e[6]+a[14]*e[10]+a[15]*e[14];d[15]=a[12]*e[3]+a[13]*e[7]+a[14]*e[11]+a[15]*e[15];return b};c.I=function(a,e){e=e||c();for(var b=
a.a,d=e.a,f=16;f--;)d[f]=b[f];return e};c.Ta=function(a,e,b,f){b=b||a.s(e);f=f||d.ZERO;return c(a.x,e.x,b.x,f.x,a.y,e.y,b.y,f.y,a.z,e.z,b.z,f.z,0,0,0,1)};c.Ka=function(a,e,b){C(a,e,b);return c(a.x,a.y,a.z,0,e.x,e.y,e.z,0,b.x,b.y,b.z,0,0,0,0,1)};c.D=function(a){a=a||c();var e=a.a;e[0]=e[5]=e[10]=e[15]=1;e[1]=e[2]=e[3]=e[4]=e[6]=e[7]=e[8]=e[9]=e[11]=e[12]=e[13]=e[14]=0;return a};c.pa=function(a,e){e=e||c();for(var b=16;b--;)m[b]=a(Math.floor(b/4),b%4,b);return e};c.qa=function(a,e,b,d,f){D(a,e,b,d);
a=Math.tan(a*Math.PI/360)*b;e*=a;return c.X(-e,e,-a,a,b,d,f)};c.X=function(a,e,b,d,f,g,l){D(a,e,b,d,f,g);l=l||c();var n=l.a;n[0]=2*f/(e-a);n[1]=0;n[2]=(e+a)/(e-a);n[3]=0;n[4]=0;n[5]=2*f/(d-b);n[6]=(d+b)/(d-b);n[7]=0;n[8]=0;n[9]=0;n[10]=-(g+f)/(g-f);n[11]=-2*g*f/(g-f);n[12]=0;n[13]=0;n[14]=-1;n[15]=0;return l};c.cb=function(a,e,b){C(a);console.log("p",a.ca,e);b=b||c();var d=b.a,f=e.f;e=e.u;var g=f.i(a);d[0]=a.x*f.x+e-g;d[1]=a.x*f.y;d[2]=a.x*f.z;d[3]=-e*a.x;d[4]=a.y*f.x;d[5]=a.y*f.y+e-g;d[6]=a.y*f.z;
d[7]=-e*a.y;d[8]=a.z*f.x;d[9]=a.z*f.y;d[10]=a.z*f.z+e-g;d[11]=-e*a.z;d[12]=f.x;d[13]=f.y;d[14]=f.z;d[15]=-g;console.log(d);return b};c.$a=function(a,e,b,d,f,g,l){D(a,e,b,d,f,g);l=l||c();var n=l.a;n[0]=2/(e-a);n[1]=0;n[2]=0;n[3]=-(e+a)/(e-a);n[4]=0;n[5]=2/(d-b);n[6]=0;n[7]=-(d+b)/(d-b);n[8]=0;n[9]=0;n[10]=-2/(g-f);n[11]=-(g+f)/(g-f);n[12]=0;n[13]=0;n[14]=0;n[15]=1;return l};c.kb=function(a,e,b,d){1==arguments.length||2==arguments.length?(d=e,e=a.y,b=a.z,a=a.x):D(a,e,b);d=d||c();var f=d.a;f[0]=a;f[1]=
0;f[2]=0;f[3]=0;f[4]=0;f[5]=e;f[6]=0;f[7]=0;f[8]=0;f[9]=0;f[10]=b;f[11]=0;f[12]=0;f[13]=0;f[14]=0;f[15]=1;return d};c.lb=function(a,e,b,d){1==arguments.length||2==arguments.length?(d=e,e=a.y,b=a.z,a=a.x):D(a,e,b);d=d||c();var f=d.a;f[0]=1;f[1]=0;f[2]=0;f[3]=a;f[4]=0;f[5]=1;f[6]=0;f[7]=e;f[8]=0;f[9]=0;f[10]=1;f[11]=b;f[12]=0;f[13]=0;f[14]=0;f[15]=1;return d};c.rotation=function(a,e,b,f,g){2==arguments.length||3==arguments.length?(D(a),g=b,b=e.y,f=e.z,e=e.x):D(a,e,b,f);d(e,b,f).b();g=g||c();var r=g.a,
l=Math.sqrt(e*e+b*b+f*f);e/=l;b/=l;f/=l;var l=Math.cos(a),n=Math.sin(a),p=1-l;r[0]=e*e*p+l;r[1]=e*b*p-f*n;r[2]=e*f*p+b*n;r[3]=0;r[4]=b*e*p+f*n;r[5]=b*b*p+l;r[6]=b*f*p-e*n;r[7]=0;r[8]=f*e*p-b*n;r[9]=f*b*p+e*n;r[10]=f*f*p+l;r[11]=0;r[12]=0;r[13]=0;r[14]=0;r[15]=1;return g};c.sa=function(a,e,b,d){d=d||c();var f=d.a;e=a.l(e).M();b=b.s(e).M();var g=e.s(b).M();f[0]=b.x;f[1]=b.y;f[2]=b.z;f[3]=-b.i(a);f[4]=g.x;f[5]=g.y;f[6]=g.z;f[7]=-g.i(a);f[8]=e.x;f[9]=e.y;f[10]=e.z;f[11]=-e.i(a);f[12]=0;f[13]=0;f[14]=
0;f[15]=1;return d};c.gb=function(a){D(a);var e=Math.cos(a);a=Math.sin(a);return c([1,0,0,0,0,e,-a,0,0,a,e,0,0,0,0,1])};c.ib=function(a){var e=Math.cos(a);a=Math.sin(a);return c([e,0,a,0,0,1,0,0,-a,0,e,0,0,0,0,1])};c.jb=function(a){var e=Math.cos(a);a=Math.sin(a);return c([e,-a,0,0,a,e,0,0,0,0,1,0,0,0,0,1])};c.fb=function(a,e,b,d){d=d||c();e=e.v();var f=a.x,g=a.y;a=a.z;var l=e.x,n=e.y;e=e.z;var p=d.a,u=Math.cos(b);b=Math.sin(b);p[0]=l*l+(n*n+e*e)*u;p[1]=l*n*(1-u)-e*b;p[2]=l*e*(1-u)+n*b;p[3]=(f*(n*
n+e*e)-l*(g*n+a*e))*(1-u)+(g*e-a*n)*b;p[4]=l*n*(1-u)+e*b;p[5]=n*n+(l*l+e*e)*u;p[6]=n*e*(1-u)-l*b;p[7]=(g*(l*l+e*e)-n*(f*l+a*e))*(1-u)+(a*l-f*e)*b;p[8]=l*e*(1-u)-n*b;p[9]=n*e*(1-u)+l*b;p[10]=e*e+(l*l+n*n)*u;p[11]=(a*(l*l+n*n)-e*(f*l+g*n))*(1-u)+(f*n-g*l)*b;p[12]=0;p[13]=0;p[14]=0;p[15]=1;return d};c.Ya=function(a,e){var b=a.f.x,d=a.f.y,f=a.f.z,g=a.u;e=e||c();var l=e.a;l[0]=1-2*b*b;l[1]=-2*d*b;l[2]=-2*f*b;l[3]=0;l[4]=-2*b*d;l[5]=1-2*d*d;l[6]=-2*f*d;l[7]=0;l[8]=-2*b*f;l[9]=-2*d*f;l[10]=1-2*f*f;l[11]=
0;l[12]=2*b*g;l[13]=2*d*g;l[14]=2*f*g;l[15]=1;return e};c.eb=function(a,e,b){e=e||a.f;var d=a.f.x,f=a.f.y,g=a.f.z,l=e,n=l.x,p=l.y,l=l.z,u=a.u;b=b||c();var v=b.a;a=a.f.i(e);n/=a;p/=a;l/=a;v[0]=1-d*n;v[1]=-f*n;v[2]=-g*n;v[3]=n*u;v[4]=-d*p;v[5]=1-f*p;v[6]=-g*p;v[7]=p*u;v[8]=-d*l;v[9]=-f*l;v[10]=1-g*l;v[11]=l*u;v[12]=0;v[13]=0;v[14]=0;v[15]=1;return b};c.ra=function(a,e){var b=a.j.x,d=a.j.y,f=a.j.z,g=a.anchor.x,l=a.anchor.y,n=a.anchor.z;e=e||c();var p=e.a;p[0]=b*b;p[1]=b*d;p[2]=b*f;p[3]=g;p[4]=d*b;p[5]=
d*d;p[6]=d*f;p[7]=l;p[8]=f*b;p[9]=f*d;p[10]=f*f;p[11]=n;p[12]=0;p[13]=0;p[14]=0;p[15]=1};c.Za=function(){var a=arguments;if(0==a.length)return c.D();for(var e=c(),b=a[0].I(),d=1;d<a.length;d++)c.h(b,a[d],e),b=z([b,e]),e=b.next().value,b=b.next().value;return b};c.ab=function(a,e){e=e||c();var b=e.a;b[0]=-1;b[1]=0;b[2]=0;b[3]=2*a.x;b[4]=0;b[5]=-1;b[6]=0;b[7]=2*a.y;b[8]=0;b[9]=0;b[10]=-1;b[11]=2*a.z;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return e};c.aa=c();c.ba=c();c.W=c(0,1,1,2,3,4,8,13,21,34,55,89,0,0,0,
1);c.ma=c.W.$();a.ya=c})(B);if(!B.B)throw Error("Define NLA.V3 first");
(function(a){function c(a,b){g(b.Z(1),"dir must be normalized"+b);var d=Object.create(c.prototype);d.anchor=a;d.j=b;return d}var d=B.B,f=B.Ba,g=B.assert,h=B.ga;c.D=function(a,b){return c(a,b.l(a).v())};c.h=function(a,b){return c(a,b.v())};c.prototype={ua:function(a){a=this.N(a);h(a);return B.b(a)},g:function(a){B.assert(a instanceof c);return this.ua(a.anchor)&&B.g(1,Math.abs(this.j.i(a.j)))},V:function(a){return a.f?a.V(this):a.j?this.va(a):this.N(a)},va:function(a){g(a instanceof c);if(this.wa(a))return this.N(a.anchor);
var b=this.j.s(a.j).M();return Math.abs(this.anchor.l(a.anchor).i(b))},N:function(a){var b=a.l(this.anchor).i(this.j);return this.Da(b).l(a).length()},Da:function(a){h(a);return this.anchor.A(this.j.w(a))},wa:function(a){B.assert(a instanceof c);return B.g(1,Math.abs(this.j.i(a.j)))},contains:function(a){a=this.V(a);return null!==a&&a<=B.m},toString:function(a){a=a||function(a){return+a.toFixed(4)};return"L3("+this.anchor.toString(a)+", "+this.j.toString(a)+")"},ha:function(a){a=(a.u-a.f.i(this.anchor))/
a.f.i(this.j);return this.anchor.A(this.j.w(a))},transform:function(a){var b=a.C(this.anchor);a=a.da(this.j);return c(b,a.v())}};B.ea(c.prototype);c.o=function(a,b){g(a instanceof f);g(b instanceof f);var c=a.f.s(b.f),d=c.length();if(1E-10>d)throw Error("Parallel planes");c.w(1/d);return a.ha(b)};Object.defineProperties(c,{O:{value:c(d.ZERO,d.O)},F:{value:c(d.ZERO,d.F)},P:{value:c(d.ZERO,d.P)}});a.xa=c})(B);if(!B.B)throw Error("Define NLA.V3 first");
(function(a){function c(a,d,h){a.Z(1);h=Object.create(h||c.prototype);h.f=a;h.u=d;return h}var d=B.B;c.h=function(a,d,h){d=d.l(a).s(h.l(a)).v();return c(d,d.i(a),void 0)};c.o=function(a,d,h){a=a.v();return c(a,a.i(d),h)};c.ma=function(a,d,h,e){return c.o(d.s(h),a,e)};c.prototype={get anchor(){return this.f.w(this.u)},L:function(a){return B.g(this.u,a.u)&&this.f.L(a.f)},Qa:function(a){return B.g(1,Math.abs(this.f.i(a.f)))},toString:function(a){a=a||function(a){return a};return"P3("+this.f.toString(a)+
", "+a(this.u)+")"},transform:function(a){var d=a.Oa(),h=this.f.La(),e=h.s(this.f),b=a.C(this.anchor),e=a.C(this.anchor.A(e));a=a.C(this.anchor.A(h));return c.h(b,d?a:e,d?e:a)},ha:function(a){this.Qa(a);var c=this.f,h=a.f,e=c.s(h).v();a=M4.Ka(c,h,e).$().da(d.create(this.u,a.u,0));return B.xa(a,e)}};B.ea(c.prototype);c.Y=c.ba=c(d.O,0);c.aa=c.W=c(d.F,0);c.D=c.X=c(d.P,0);a.Ba=c})(B);
