var mpchars = [
  {'rarity': 0, 'name': 'HF Soldier', 'sn': 'HFS', "min": 1},
  {'rarity': 0, 'name': 'HM Soldier', 'sn': 'HMS', "min": 1},
  {'rarity': 0, 'name': 'HF Vanguard', 'sn': 'HFV', "min": 1},
  {'rarity': 0, 'name': 'HM Vanguard', 'sn': 'HMV', "min": 1},
  {'rarity': 0, 'name': 'HF Engineer', 'sn': 'HFE', "min": 1},
  {'rarity': 0, 'name': 'HM Engineer', 'sn': 'HME', "min": 1},
  {'rarity': 0, 'name': 'HF Adept', 'sn': 'HFA', "min": 1},
  {'rarity': 0, 'name': 'HM Adept', 'sn': 'HMA', "min": 1},
  {'rarity': 0, 'name': 'HF Sentinel', 'sn': 'HFT', "min": 1},
  {'rarity': 0, 'name': 'HM Sentinel', 'sn': 'HMT', "min": 1},
  {'rarity': 0, 'name': 'HF Infiltrator', 'sn': 'HFI', "min": 1},
  {'rarity': 0, 'name': 'HM Infiltrator', 'sn': 'HMI', "min": 1},
  {'rarity': 1, 'name': 'Turian Soldier', 'sn': 'TS'},
  {'rarity': 1, 'name': 'Krogan Vanguard', 'sn': 'KV'},
  {'rarity': 1, 'name': 'Krogan Engineer', 'sn': 'KE'},
  {'rarity': 1, 'name': 'Asari Sentinel', 'sn': 'AS'},
  {'rarity': 1, 'name': 'Salarian Infiltrator', 'sn': 'SI'},
  {'rarity': 1, 'name': 'Asari Adept', 'sn': 'AA'},
  {'rarity': 2, 'name': 'Krogan Mercenary', 'sn': 'KM'},
  {'rarity': 2, 'name': 'Turian Havoc Trooper', 'sn': 'THT'},
  {'rarity': 2, 'name': 'Asari Huntress', 'sn': 'AH'},
  {'rarity': 2, 'name': 'Angara Insurgent', 'sn': 'AI'},
  {'rarity': 2, 'name': 'Salarian Architect', 'sn': 'SA'},
  {'rarity': 2, 'name': 'Turian Agent', 'sn': 'TA'},
  {'rarity': 3, 'name': 'Asari Duelist', 'sn': 'AD'},
  {'rarity': 3, 'name': 'Angara Avenger', 'sn': 'AgA'},
  {'rarity': 3, 'name': 'Salarian Operator', 'sn': 'SO'},
  {'rarity': 3, 'name': 'Human Kineticist', 'sn': 'HK'},
  {'rarity': 3, 'name': 'Krogan Gladiator', 'sn': 'KG'},
  {'rarity': 3, 'name': 'Angara Exemplar', 'sn': 'AgE'},
  {'rarity': 2, 'name': 'Batarian Scrapper', 'sn': 'BS'},
]
