var mpchars = [
  {'rarity': 0, 'name': 'HF Soldier', 'sn': 'HFS', 'startlvl': 1},
  {'rarity': 0, 'name': 'HM Soldier', 'sn': 'HMS', 'startlvl': 1},
  {'rarity': 0, 'name': 'HF Vanguard', 'sn': 'HFV', 'startlvl': 1},
  {'rarity': 0, 'name': 'HM Vanguard', 'sn': 'HMV', 'startlvl': 1},
  {'rarity': 0, 'name': 'HF Engineer', 'sn': 'HFE', 'startlvl': 1},
  {'rarity': 0, 'name': 'HM Engineer', 'sn': 'HME', 'startlvl': 1},
  {'rarity': 0, 'name': 'HF Adept', 'sn': 'HFA', 'startlvl': 1},
  {'rarity': 0, 'name': 'HM Adept', 'sn': 'HMA', 'startlvl': 1},
  {'rarity': 0, 'name': 'HF Sentinel', 'sn': 'HFT', 'startlvl': 1},
  {'rarity': 0, 'name': 'HM Sentinel', 'sn': 'HMT', 'startlvl': 1},
  {'rarity': 0, 'name': 'HF Infiltrator', 'sn': 'HFI', 'startlvl': 1},
  {'rarity': 0, 'name': 'HM Infiltrator', 'sn': 'HMI', 'startlvl': 1},
  {'rarity': 1, 'name': 'Turian Soldier', 'sn': 'TS'},
  {'rarity': 1, 'name': 'Krogan Vanguard', 'sn': 'KV'},
  {'rarity': 1, 'name': 'Krogan Engineer', 'sn': 'KE'},
  {'rarity': 1, 'name': 'Asari Sentinel', 'sn': 'AS'},
  {'rarity': 1, 'name': 'Salarian Infiltrator', 'sn': 'SI'},
  {'rarity': 1, 'name': 'Asari Adept', 'sn': 'AA'},
  {'rarity': 2, 'name': 'Krogan Mercenary', 'sn': 'KM'},
  {'rarity': 2, 'name': 'Turian Havoc Trooper', 'sn': 'THT'},
  {'rarity': 2, 'name': 'Asari Huntress', 'sn': 'AH'},
  {'rarity': 2, 'name': 'Angara Insurgent', 'sn': 'AI'},
  {'rarity': 3, 'name': 'Asari Duelist', 'sn': 'AD'},
  {'rarity': 3, 'name': 'Angara Avenger', 'sn': 'AgA'},
  {'rarity': 3, 'name': 'Salarian Operator', 'sn': 'SO'},
  {'rarity': 3, 'name': 'Human Kineticist', 'sn': 'HK'},
]