var h="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function t(){h.Symbol||(h.Symbol=aa);t=function(){}}var ba=0;function aa(a){return"jscomp_symbol_"+a+ba++}function w(){t();h.Symbol.iterator||(h.Symbol.iterator=h.Symbol("iterator"));w=function(){}}
function ca(a){w();if(a[h.Symbol.iterator])return a[h.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var c=0;return{next:function(){return c==a.length?{done:!0}:{done:!1,value:a[c++]}}}}
function x(a,c){function d(){}d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;for(var e in c)if(h.Object.defineProperties){var g=h.Object.getOwnPropertyDescriptor(c,e);void 0!==g&&h.Object.defineProperty(a,e,g)}else a[e]=c[e]}var y={};window.NLA=y;var z=y.Va=function(){return!0};y.Ua=function(a,c){for(var d=1;d<arguments.length;++d);return!0};var A=y.m=function(a){for(var c=0;c<arguments.length;++c);return!0};function B(){}y.i=1/67108864;console.log("NLA.PRECISION",y.i);
y.c=function(a){return Math.abs(a)<y.i};y.oa=function(a,c){return Math.abs(a)<c};y.f=function(a,c){return Math.abs(a-c)<=y.i};y.pb=function(a,c){return a+y.i<c};y.jb=function(a,c){return a>c+y.i};y.ob=function(a,c){return a<=c+y.i};y.ib=function(a,c){return a+y.i>=c};y.la=function(a,c){return Math.abs(1-a)<c};y.eb=function(a,c){return y.ra(a-c)};y.ra=function(a){return(a%(2*Math.PI)+2*Math.PI+y.i)%(2*Math.PI)<2*y.i};y.tb=function(a,c){return Math.abs(a-c)<=y.i?c:a};
y.Ya=function(a){return(a%(2*Math.PI)+2*Math.PI)%(2*Math.PI)};y.Z=function(a){if(0==a)return"";a*=1;for(var c=a/2,d=" ";d.length<=c;)d+=d;return d+d.substring(0,a-d.length)};y.rb=function(a,c){return(a%c+c)%c};y.J=function(a,c,d){var e=a[c];a[c]=a[d];a[d]=e};y.D=function(a,c,d,e,g){e+=g;for(g+=c;g-- >c;)d[--e]=a[g]};y.Za=function(a,c,d){y.m(a,c,d);return Math.max(c,Math.min(d,a))};t();w();y.sb=function(){return Math.floor(16777216*Math.random())};
y.qb=function(a,c,d){var e=a.get(c);e?e.push(d):a.set(c,[d])};y.T=function(a){y.C(a,C.prototype)};
var D={aa:function(a){Array.prototype.push.apply(this,a)},V:function(a,c,d,e,g,p,f){var b=c+f*d;for(g+=f*p;b>c;)e[g-=p]=a[b-=d]},j:function(a,c,d){y.m(a,c);d=d||1;for(var e=Array(Math.ceil((this.length-a)/c)),g=0,p=0;p<this.length;p+=c)for(var f=0;f<d;f++)e[g++]=this[a+p+f];return e},U:function(){return Array.prototype.concat.apply([],this)},min:function(){return Math.min.apply(null,this)},max:function(){return Math.max.apply(null,this)},X:function(a){if(0==this.length)return 0;for(var c=this.length,
d=-1,e=-Infinity;c--;){var g=a(this[c],c);g>e&&(e=g,d=c)}return d},da:function(a){for(var c=this.length,d=void 0,e=-Infinity;c--;){var g=this[c],p=a(g);p>e&&(e=p,d=g)}return d},F:function(){for(var a=this.length,c=0;a--;)c+=Math.abs(this[a]);return c},R:function(){for(var a=this.length,c=0;a--;)c+=this[a];return c},Y:function(){return 0==this.length},unique:function(){var a=new Set(this);return Array.j(a)},remove:function(a){a=this.indexOf(a);-1!=a&&this.splice(a,1)},ca:function(a){for(var c=a.length;c--;)this.remove(a[c])},
toggle:function(a){var c=this.indexOf(a);-1!=c?this.splice(c,1):this.push(a)},K:function(a,c){for(var d=0,e=this.length-1,g,p;d<=e;)if(g=(d+e)/2|0,p=this[g],0>c(p,a))d=g+1;else if(0<c(p,a))e=g-1;else return g;return-d-1},N:function(a,c){c=c||y.o;for(var d=0,e=this.length,g,p;d<e;)g=~~((d+e)/2),p=this[g],0>c(p,a)?d=g+1:e=g;this.splice(d,0,a)}};y.o=function(a,c){return a-c};var E={key:void 0},F;
for(F in D){E.key=F;var G=E.key;y["array"+(G.charAt(0).toUpperCase()+G.slice(1))]=function(a){return function(c,d){for(var e=[],g=1;g<arguments.length;++g)e[g-1]=arguments[g];D[a.key].apply(c,e)}}(E);E={key:E.key}}y.H=function(a,c,d,e,g,p,f){var b=c+f*d;for(g+=f*p;b>c;)e[g-=p]=a[b-=d]};y.Qa=function(a,c,d,e,g,p,f,b){for(var q=0;q<b;q++)y.D(a,c+d*q,e,g+p*q,f)};y.Ta=function(a,c,d){y.m(a,d);console.log(Math.ceil((c-a)/d));a=Array(Math.ceil((c-a)/d));for(var e=0,g=0;g<c;g+=d)a[e++]=g;return a};
y.I=function(a,c){y.m(a);for(var d=Array(a),e=a;e--;)d[e]=c(e);return d};function H(a){this.b=a}y.Ka=function(){B(arguments[0]instanceof Float64Array||arguments.every(function(a){return"number"==typeof a}));return new H(arguments[0]instanceof Float64Array?arguments[0]:Float64Array.j(arguments))};
H.prototype={B:function(a){var c=this.b;a=a.b;for(var d=new Float64Array(c.length),e=c.length;e--;)d[e]=c[e]+a[e];return new H(d)},o:function(a){var c=this.b;a=a.b;for(var d=new Float64Array(c.length),e=c.length;e--;)d[e]=c[e]-a[e];return new H(d)},l:function(a){var c=0,d=this.b;a=a.b;for(var e=d.length;e--;)c+=d[e]*a[e];return c},v:function(a){for(var c=this.b,d=new Float64Array(c.length),e=c.length;e--;)d[e]=c[e]*a;return new H(d)},s:function(a){var c=new Float64Array(3);c[0]=this.b[1]*a.b[2]-this.b[2]*
a.b[1];c[1]=this.b[2]*a.b[0]-this.b[0]*a.b[2];c[2]=this.b[0]*a.b[1]-this.b[1]*a.b[0];return new H(c)},f:function(a){if(a===this)return!0;if(a.constructor==H||this.b.length!=a.b.length)return!1;for(var c=this.b.length;c--;)if(!y.f(this.b[c],a.b[c]))return!1;return!0},map:function(a){for(var c=new Float64Array(this.b.length),d=c.length;d--;)c[d]=a(d);return new H(c)},toString:function(a){a=a||function(a){return+a.toFixed(6)};return"NLA.Vector("+this.b.map(a).join(", ")+")"},c:function(){return y.c(this.length())},
length:function(){return Math.sqrt(this.j())},j:function(){for(var a=0,c=this.b,d=c.length;d--;)a+=c[d]*c[d];return a},A:function(){var a=this.length();if(y.c(a))throw Error("cannot normalize zero vector");for(var a=this.length(),c=this.b,d=new Float64Array(c.length),e=c.length;e--;)d[e]=c[e]/a;return new H(d)},O:function(a){y.m(a);return y.f(a,this.length())}};
y.C=function(a,c){c&&Object.getOwnPropertyNames(c).forEach(function(d){c.hasOwnProperty(d)&&(a.hasOwnProperty(d)&&console.warn("target ",a," already has property ",d),Object.defineProperty(a,d,Object.getOwnPropertyDescriptor(c,d)))})};y.bb=function(a,c,d,e,g){d.prototype=y.ja(c&&c.prototype,e);d.prototype.constructor=d;d.prototype.name=a;y.C(d,g);return d};y.ia=function(a){return Math.$(a,-4)};y.ja=function(a,c){var d=Object.create(a||I);y.C(d,c);return d};function I(){}x(I,Object);
I.prototype.toSource=function(){return this.toString==Object.prototype.toString?Object.prototype.toSource.apply(this):this.toString()};y.gb=function(a){a=parseFloat(a.replace(",",".").replace(/^[^0-9,\.\-]/,""));return Number.isFinite(a)?a:0};
(function(){function a(a,d,e){if("undefined"===typeof e||0===+e)return Math[a](d);d=+d;e=+e;if(isNaN(d)||"number"!==typeof e||0!==e%1)return NaN;d=d.toString().split("e");d=Math[a](+(d[0]+"e"+(d[1]?+d[1]-e:-e)));d=d.toString().split("e");return+(d[0]+"e"+(d[1]?+d[1]+e:e))}Math.$||(Math.$=function(c,d){return a("round",c,d)});Math.ma||(Math.ma=function(c,d){return a("floor",c,d)});Math.ha||(Math.ha=function(c,d){return a("ceil",c,d)})})();function J(a,c,d){this.a=d;this.width=a;this.height=c}
function K(a){y.m(a);for(var c=new Float64Array(a*a),d=a*(a+1);d;)d-=a+1,c[d]=1;return new J(a,a,c)}function L(a){if(0==a.length)throw Error("cannot have 0 vector");var c=a.length,d=a[0].length,e=new Float64Array(c*d);y.D(a[0],0,e,0,d);for(var g=1;g<c;g++){if(a[g].length!=d)throw Error("all row arrays must be the same length");y.D(a[g],0,e,g*d,d)}return new J(d,c,e)}function M(a){return da(a.map(function(a){return a.b}))}
function da(a){if(0==a.length)throw Error("cannot have 0 vector");var c=a.length,d=a[0].length,e=new Float64Array(d*c);y.H(a[0],0,1,e,0,c,d);for(var g=1;g<c;g++){if(a[g].length!=d)throw Error("all col arrays must be the same length");y.H(a[g],0,1,e,g,c,d)}return new J(c,d,e)}
J.prototype={toString:function(a){var c=this;a=a||function(a){return a.toFixed(3)};B("string"==typeof a(0),""+typeof a(0));var d=Array.prototype.slice.call(this.a).map(a),e=y.I(this.width,function(a){return d.j(a,c.width).map(function(a){return a.length}).max()});return y.I(this.height,function(a){return d.slice(a*c.width,(a+1)*c.width).map(function(a,f){return y.Z(e[f]-a.length)+a}).join(" ")}).map(function(a){return a+"\n"}).join("")},f:function(a){if(a.constructor!=J||this.width!=a.width||this.height!=
a.height)return!1;for(var c=this.a.length;c--;)if(this.a[c]!=a.a[c])return!1},aa:function(){var a;if(a=this.height==this.width)a:{a=this.N().v(this);var c=K(this.width),d;d=d||y.i;if(!(c instanceof J))throw Error("not a matrix");if(a.width!=c.width||a.height!=c.height)a=!1;else{for(var e=a.a.length;e--;)if(Math.abs(a.a[e]-c.a[e])>=d){a=!1;break a}a=!0}}return a},Y:function(a){a:if(a="number"==typeof a?a:y.i,this.height==this.width){for(var c=0;c<this.height-1;c++)for(var d=c;d<this.width;d++){var e=
this.a[c*this.width+d];if(c==d?!y.la(e,a):!y.oa(e,a)){a=!1;break a}}a=!0}else a=!1;return a&&N(this)},map:function(a){return new J(this.width,this.height,this.a.map(a))},W:function(){var a=ha(this),c;c=a.ea;for(var d=a.fa,e=Array(d.width),g=d.width;g--;){var p=g,f;f=c;var b=O(d,g);a:{var q=f;if(q.height==q.width)for(var r=0;r<q.height-1;r++)for(var n=r+1;n<q.width;n++)if(!y.c(q.a[r*q.width+n]))break a}q=new Float64Array(f.width);for(r=0;r<f.height;r++){for(var n=b.b[r],l=0;l<r;l++)n-=q[l]*R(f,r,l);
q[r]=n/R(f,r,r)}f=new H(q);e[p]=f}c=M(e);a=a.ga;d=Array(c.width);for(e=c.width;e--;){g=e;p=a;f=O(c,e);N(p);b=new Float64Array(p.width);for(q=p.height;q--;){r=f.b[q];for(n=q+1;n<p.width;n++)r-=b[n]*R(p,q,n);b[q]=r/R(p,q,q)}p=new H(b);d[g]=p}return M(d)},v:function(a){for(var c=a.width,d=this.height,e=this.width,g=new Float64Array(c*d),p=d;p--;)for(var f=c;f--;){for(var b=0,q=e;q--;)b+=this.a[p*e+q]*a.a[q*c+f];g[p*c+f]=b}return new J(c,d,g)},N:function(){for(var a=this.height,c=this.width,d=new Float64Array(a*
c),e=c;e--;)for(var g=a;g--;)d[e*a+g]=this.a[g*c+e];return new J(a,c,d)},max:function(){return y.Ra(this.a)},min:function(){return y.Sa(this.a)}};function ia(a){for(var c=Float64Array,c=c||Float64Array,d=a.height,e=Array(a.height);d--;){var g=d,p=a,f=d,b=c,b=b||Float64Array,b=new b(p.width);y.D(p.a,f*p.width,b,0,p.width);e[g]=b}return e}function N(a){if(a.height!=a.width)return!1;for(var c=1;c<a.height;c++)for(var d=0;d<c;d++)if(!y.c(a.a[c*a.width+d]))return!1;return!0}
function ha(a){var c=ia(a),d=a.width;a=y.I(d,function(){return new Float64Array(d)});for(var e=ia(K(d)),g=0;g<d;g++){for(var p=0,f=d,b=g;--f>=g;)Math.abs(c[f][g])>=p&&(p=Math.abs(c[f][g]),b=f);y.J(c,g,b);y.J(a,g,b);y.J(e,g,b);a[g][g]=1;for(f=g+1;f<d;f++)for(p=c[f][g]/c[g][g],a[f][g]=p,b=g;b<d;b++)c[f][b]-=p*c[g][b]}return{ea:L(a),ga:L(c),fa:L(e)}}function O(a,c){var d=new Float64Array(a.height);y.H(a.a,c,a.width,d,0,1,a.height);return new H(d)}function R(a,c,d){y.m(c,d);return a.a[c*a.width+d]}
y.$a=function(a){function c(p){for(;;)switch(d){case 0:g=0;case 1:if(!(g<a)){d=3;break}e=g;case 4:if(!(e<a)){d=6;break}d=7;return{value:{lb:g,nb:e},done:!1};case 7:if(void 0===p){d=8;break}d=-1;throw p;case 8:case 5:e++;d=4;break;case 6:case 2:g++;d=1;break;case 3:d=-1;default:return{value:void 0,done:!0}}}var d=0,e,g,p={next:function(){return c(void 0)},throw:function(a){return c(a)}};w();p[Symbol.iterator]=function(){return this};return p};function C(){}x(C,I);y.C(Array.prototype,D);function S(a,c,d){this.x=this.y=this.z=0;if(3==arguments.length)return T(parseFloat(a),parseFloat(c),parseFloat(d));if(2==arguments.length)return T(parseFloat(a),parseFloat(c),0);if(1==arguments.length&&"object"==typeof a){if(a instanceof S)return a;if(a instanceof Array||a instanceof Float32Array||a instanceof Float64Array){if(2==a.length)return T(parseFloat(a[0]),parseFloat(a[1]),0);if(3==a.length)return T(parseFloat(a[0]),parseFloat(a[1]),parseFloat(a[2]))}else if("x"in a&&"y"in a)return"z"in a?
T(parseFloat(a.x),parseFloat(a.y),parseFloat(a.z)):T(parseFloat(a.x),parseFloat(a.y),0)}throw Error("invalid arguments"+arguments);}function T(a,c,d){A(a,c,d);var e=Object.create(S.prototype);Object.defineProperties(e,{x:{value:a},y:{value:c},z:{value:d}});return e}
S.prototype={abs:function(){return T(Math.abs(this.x),Math.abs(this.y),Math.abs(this.z))},B:function(a){return T(this.x+a.x,this.y+a.y,this.z+a.z)},o:function(a){return T(this.x-a.x,this.y-a.y,this.z-a.z)},v:function(a){A(a);return T(this.x*a,this.y*a,this.z*a)},l:function(a){return this.x*a.x+this.y*a.y+this.z*a.z},j:function(){return this.l(this)},M:function(a){return Math.hypot(this.x-a.x,this.y-a.y,this.z-a.z)},min:function(a){return T(Math.min(this.x,a.x),Math.min(this.y,a.y),Math.min(this.z,
a.z))},max:function(a){return T(Math.max(this.x,a.x),Math.max(this.y,a.y),Math.max(this.z,a.z))},f:function(a){return this==a||this.x==a.x&&this.y==a.y&&this.z==a.z},s:function(a){return T(this.y*a.z-this.z*a.y,this.z*a.x-this.x*a.z,this.x*a.y-this.y*a.x)},map:function(a){return T(a(this.x),a(this.y),a(this.z))},toString:function(a){a=a||y.ia;return"V3("+[this.x,this.y,this.z].map(a).join(", ")+")"},length:function(){return Math.hypot(this.x,this.y,this.z)},c:function(){return this.P(U)},P:function(a){return a===
this?!0:a instanceof S?y.f(this.x,a.x)&&y.f(this.y,a.y)&&y.f(this.z,a.z):!1},A:function(){this.c();return ja(this,this.length())},O:function(a){y.m(a);return y.f(a,this.length())},F:function(){return Math.abs(this.x)+Math.abs(this.y)+Math.abs(this.z)},transform:function(a){return a.w(this)},get qa(){return this.toString()}};function V(a){return ja(a,a.length())}function ja(a,c){A(c);return T(a.x/c,a.y/c,a.z/c)}S.prototype.toSource=S.prototype.toString;
var U=T(0,0,0),ka=T(1,0,0),W=T(0,1,0),la=T(0,0,1);T(Infinity,Infinity,Infinity);y.S=S;if(!y.S)throw Error("Define NLA.V3 first");
(function(a){function c(){var a;a=0==arguments.length?new Float64Array(16):new Float64Array(Array.prototype.concat.apply([],arguments));var f=Object.create(c.prototype);Object.defineProperty(f,"m",{value:a});return f}var d=y.S;c.prototype=Object.create(J.prototype);var e={W:function(){return c.X(this)},trace:function(){return this.a[0]+this.a[5]+this.a[10]+this.a[15]},pa:function(a){return this.a.every(function(c,b){return y.f(c,a.a[b])})},N:function(){return c.F(this)},v:function(a){return c.j(this,
a)},w:function(a){z(a);var c=this.a,b=a.x,q=a.y;a=a.z;var r=b*c[12]+q*c[13]+a*c[14]+1*c[15];return d.create((b*c[0]+q*c[1]+a*c[2]+1*c[3])/r,(b*c[4]+q*c[5]+a*c[6]+1*c[7])/r,(b*c[8]+q*c[9]+a*c[10]+1*c[11])/r)},ba:function(a){z(a);var c=this.a;return d.create(c[0]*a.x+c[1]*a.y+c[2]*a.z,c[4]*a.x+c[5]*a.y+c[6]*a.z,c[8]*a.x+c[9]*a.y+c[10]*a.z)},hb:function(a){var c=this;return a.map(function(b){return c.w(b)})},kb:function(a){var c=this;return a.map(function(b){return c.ba(b)})},B:function(a){for(var f=
c(),b=0;16>b;b++)f.a[b]=this.a[b]+a.a[b];return f},o:function(a){for(var f=c(),b=0;16>b;b++)f.a[b]=this.a[b]-a.a[b];return f},fb:function(a){for(var f=c(),b=0;16>b;b++)f.a[b]=this.a[b]*a;return f},ka:function(a){for(var f=c(),b=0;16>b;b++)f.a[b]=this.a[b]/a;return f},clone:function(){return c.G(this)},G:function(){return c.G(this)},Aa:function(){return!y.c(this.L())},za:function(){var a=this.a;return 1>=!y.c(a[0])+!y.c(a[1])+!y.c(a[2])&&1>=!y.c(a[4])+!y.c(a[5])+!y.c(a[6])&&1>=!y.c(a[8])+!y.c(a[9])+
!y.c(a[10])},aa:function(){var a=c.ca,f=c.R;c.F(this,a);c.j(this,a,f);c.K(a);return a.pa(f)},L:function(){var a=this.a,c=a[4],b=a[5],d=a[6],r=a[7],e=a[8],g=a[9],k=a[10],m=a[11],u=a[12],v=a[13],P=a[14],Q=a[15],ea=k*Q-m*P,fa=g*Q-m*v,ga=g*P-k*v,m=e*Q-m*u,k=e*P-k*u,e=e*v-g*u;return a[0]*(b*ea-d*fa+r*ga)-a[1]*(c*ea-d*m+r*k)+a[2]*(c*fa-b*m+r*e)-a[3]*(c*ga-b*k+d*e)},na:function(){return 0>this.L()},xa:function(){var a=this.a,c=a[15];return d.create(a[3]/c,a[7]/c,a[11]/c)},A:function(){var a=this.L();return 1==
a?this:this.ka(Math.sqrt(Math.sqrt(a)))},ya:function(){var a=this.a;return y.f(1,a[15])&&y.c(a[12])&&y.c(a[13])&&y.c(a[14])&&y.c(a[3])&&y.c(a[7])&&y.c(a[11])},Y:function(){return this.a.every(function(a,c){return(c/4|0)==c%4?y.f(1,a):y.c(a)})},toString:function(a){a=a||function(a){return a.toFixed(6).replace(/(0|\.)(?=0*$)/g," ").toString()};B("string"==typeof a(0),""+typeof a(0));var c=Array.prototype.slice.call(this.a).map(a),b=[0,1,2,3].map(function(a){return c.j(a,4).map(function(a){return a.length}).max()});
return[0,1,2,3].map(function(a){return c.slice(4*a,4*a+4).map(function(a,c){return y.Z(b[c]-a.length)+a}).join(" ")}).join("\n")}},g;for(g in e)c.prototype[g]=e[g];c.X=function(a){var f;f=f||c();var b=a.a;a=f.a;a[0]=b[5]*b[10]*b[15]-b[5]*b[14]*b[11]-b[6]*b[9]*b[15]+b[6]*b[13]*b[11]+b[7]*b[9]*b[14]-b[7]*b[13]*b[10];a[1]=-b[1]*b[10]*b[15]+b[1]*b[14]*b[11]+b[2]*b[9]*b[15]-b[2]*b[13]*b[11]-b[3]*b[9]*b[14]+b[3]*b[13]*b[10];a[2]=b[1]*b[6]*b[15]-b[1]*b[14]*b[7]-b[2]*b[5]*b[15]+b[2]*b[13]*b[7]+b[3]*b[5]*
b[14]-b[3]*b[13]*b[6];a[3]=-b[1]*b[6]*b[11]+b[1]*b[10]*b[7]+b[2]*b[5]*b[11]-b[2]*b[9]*b[7]-b[3]*b[5]*b[10]+b[3]*b[9]*b[6];a[4]=-b[4]*b[10]*b[15]+b[4]*b[14]*b[11]+b[6]*b[8]*b[15]-b[6]*b[12]*b[11]-b[7]*b[8]*b[14]+b[7]*b[12]*b[10];a[5]=b[0]*b[10]*b[15]-b[0]*b[14]*b[11]-b[2]*b[8]*b[15]+b[2]*b[12]*b[11]+b[3]*b[8]*b[14]-b[3]*b[12]*b[10];a[6]=-b[0]*b[6]*b[15]+b[0]*b[14]*b[7]+b[2]*b[4]*b[15]-b[2]*b[12]*b[7]-b[3]*b[4]*b[14]+b[3]*b[12]*b[6];a[7]=b[0]*b[6]*b[11]-b[0]*b[10]*b[7]-b[2]*b[4]*b[11]+b[2]*b[8]*b[7]+
b[3]*b[4]*b[10]-b[3]*b[8]*b[6];a[8]=b[4]*b[9]*b[15]-b[4]*b[13]*b[11]-b[5]*b[8]*b[15]+b[5]*b[12]*b[11]+b[7]*b[8]*b[13]-b[7]*b[12]*b[9];a[9]=-b[0]*b[9]*b[15]+b[0]*b[13]*b[11]+b[1]*b[8]*b[15]-b[1]*b[12]*b[11]-b[3]*b[8]*b[13]+b[3]*b[12]*b[9];a[10]=b[0]*b[5]*b[15]-b[0]*b[13]*b[7]-b[1]*b[4]*b[15]+b[1]*b[12]*b[7]+b[3]*b[4]*b[13]-b[3]*b[12]*b[5];a[11]=-b[0]*b[5]*b[11]+b[0]*b[9]*b[7]+b[1]*b[4]*b[11]-b[1]*b[8]*b[7]-b[3]*b[4]*b[9]+b[3]*b[8]*b[5];a[12]=-b[4]*b[9]*b[14]+b[4]*b[13]*b[10]+b[5]*b[8]*b[14]-b[5]*b[12]*
b[10]-b[6]*b[8]*b[13]+b[6]*b[12]*b[9];a[13]=b[0]*b[9]*b[14]-b[0]*b[13]*b[10]-b[1]*b[8]*b[14]+b[1]*b[12]*b[10]+b[2]*b[8]*b[13]-b[2]*b[12]*b[9];a[14]=-b[0]*b[5]*b[14]+b[0]*b[13]*b[6]+b[1]*b[4]*b[14]-b[1]*b[12]*b[6]-b[2]*b[4]*b[13]+b[2]*b[12]*b[5];a[15]=b[0]*b[5]*b[10]-b[0]*b[9]*b[6]-b[1]*b[4]*b[10]+b[1]*b[8]*b[6]+b[2]*b[4]*b[9]-b[2]*b[8]*b[5];for(var b=b[0]*a[0]+b[1]*a[4]+b[2]*a[8]+b[3]*a[12],d=16;d--;)a[d]/=b;return f};c.F=function(a,f){f=f||c();var b=a.a,d=f.a;d[0]=b[0];d[1]=b[4];d[2]=b[8];d[3]=b[12];
d[4]=b[1];d[5]=b[5];d[6]=b[9];d[7]=b[13];d[8]=b[2];d[9]=b[6];d[10]=b[10];d[11]=b[14];d[12]=b[3];d[13]=b[7];d[14]=b[11];d[15]=b[15];return f};c.j=function(a,f,b){b=b||c();a=a.a;f=f.a;var d=b.a;d[0]=a[0]*f[0]+a[1]*f[4]+a[2]*f[8]+a[3]*f[12];d[1]=a[0]*f[1]+a[1]*f[5]+a[2]*f[9]+a[3]*f[13];d[2]=a[0]*f[2]+a[1]*f[6]+a[2]*f[10]+a[3]*f[14];d[3]=a[0]*f[3]+a[1]*f[7]+a[2]*f[11]+a[3]*f[15];d[4]=a[4]*f[0]+a[5]*f[4]+a[6]*f[8]+a[7]*f[12];d[5]=a[4]*f[1]+a[5]*f[5]+a[6]*f[9]+a[7]*f[13];d[6]=a[4]*f[2]+a[5]*f[6]+a[6]*f[10]+
a[7]*f[14];d[7]=a[4]*f[3]+a[5]*f[7]+a[6]*f[11]+a[7]*f[15];d[8]=a[8]*f[0]+a[9]*f[4]+a[10]*f[8]+a[11]*f[12];d[9]=a[8]*f[1]+a[9]*f[5]+a[10]*f[9]+a[11]*f[13];d[10]=a[8]*f[2]+a[9]*f[6]+a[10]*f[10]+a[11]*f[14];d[11]=a[8]*f[3]+a[9]*f[7]+a[10]*f[11]+a[11]*f[15];d[12]=a[12]*f[0]+a[13]*f[4]+a[14]*f[8]+a[15]*f[12];d[13]=a[12]*f[1]+a[13]*f[5]+a[14]*f[9]+a[15]*f[13];d[14]=a[12]*f[2]+a[13]*f[6]+a[14]*f[10]+a[15]*f[14];d[15]=a[12]*f[3]+a[13]*f[7]+a[14]*f[11]+a[15]*f[15];return b};c.G=function(a,f){f=f||c();for(var b=
a.a,d=f.a,e=16;e--;)d[e]=b[e];return f};c.ua=function(a,f,b,e){b=b||a.s(f);e=e||d.j;return c(a.x,f.x,b.x,e.x,a.y,f.y,b.y,e.y,a.z,f.z,b.z,e.z,0,0,0,1)};c.ta=function(a,f,b){z(a,f,b);return c(a.x,a.y,a.z,0,f.x,f.y,f.z,0,b.x,b.y,b.z,0,0,0,0,1)};c.K=function(a){a=a||c();var f=a.a;f[0]=f[5]=f[10]=f[15]=1;f[1]=f[2]=f[3]=f[4]=f[6]=f[7]=f[8]=f[9]=f[11]=f[12]=f[13]=f[14]=0;return a};c.va=function(a,f){f=f||c();for(var b=f.a,d=16;d--;)b[d]=a(Math.floor(d/4),d%4,d);return f};c.wa=function(a,f,b,d,e){A(a,f,b,
d);a=Math.tan(a*Math.PI/360)*b;f=a*f;return c.V(-f,f,-a,a,b,d,e)};c.V=function(a,f,b,d,e,g,l){A(a,f,b,d,e,g);l=l||c();var k=l.a;k[0]=2*e/(f-a);k[1]=0;k[2]=(f+a)/(f-a);k[3]=0;k[4]=0;k[5]=2*e/(d-b);k[6]=(d+b)/(d-b);k[7]=0;k[8]=0;k[9]=0;k[10]=-(g+e)/(g-e);k[11]=-2*g*e/(g-e);k[12]=0;k[13]=0;k[14]=-1;k[15]=0;return l};c.La=function(a,f,b){z(a);console.log("p",a.qa,f);b=b||c();var d=b.a,e=f.g;f=f.u;var g=e.l(a);d[0]=a.x*e.x+f-g;d[1]=a.x*e.y;d[2]=a.x*e.z;d[3]=-f*a.x;d[4]=a.y*e.x;d[5]=a.y*e.y+f-g;d[6]=a.y*
e.z;d[7]=-f*a.y;d[8]=a.z*e.x;d[9]=a.z*e.y;d[10]=a.z*e.z+f-g;d[11]=-f*a.z;d[12]=e.x;d[13]=e.y;d[14]=e.z;d[15]=-g;console.log(d);return b};c.Ia=function(a,d,b,e,g,n,l){A(a,d,b,e,g,n);l=l||c();var k=l.a;k[0]=2/(d-a);k[1]=0;k[2]=0;k[3]=-(d+a)/(d-a);k[4]=0;k[5]=2/(e-b);k[6]=0;k[7]=-(e+b)/(e-b);k[8]=0;k[9]=0;k[10]=-2/(n-g);k[11]=-(n+g)/(n-g);k[12]=0;k[13]=0;k[14]=0;k[15]=1;return l};c.cb=function(a,d,b,e){1==arguments.length||2==arguments.length?(e=d,d=a.y,b=a.z,a=a.x):A(a,d,b);e=e||c();var g=e.a;g[0]=
a;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=d;g[6]=0;g[7]=0;g[8]=0;g[9]=0;g[10]=b;g[11]=0;g[12]=0;g[13]=0;g[14]=0;g[15]=1;return e};c.mb=function(a,d,b,e){1==arguments.length||2==arguments.length?(e=d,d=a.y,b=a.z,a=a.x):A(a,d,b);e=e||c();var g=e.a;g[0]=1;g[1]=0;g[2]=0;g[3]=a;g[4]=0;g[5]=1;g[6]=0;g[7]=d;g[8]=0;g[9]=0;g[10]=1;g[11]=b;g[12]=0;g[13]=0;g[14]=0;g[15]=1;return e};c.rotation=function(a,f,b,e,g){2==arguments.length||3==arguments.length?(A(a),g=b,b=f.y,e=f.z,f=f.x):A(a,f,b,e);d(f,b,e).c();g=g||c();
var n=g.a,l=Math.sqrt(f*f+b*b+e*e);f/=l;b/=l;e/=l;var l=Math.cos(a),k=Math.sin(a),m=1-l;n[0]=f*f*m+l;n[1]=f*b*m-e*k;n[2]=f*e*m+b*k;n[3]=0;n[4]=b*f*m+e*k;n[5]=b*b*m+l;n[6]=b*e*m-f*k;n[7]=0;n[8]=e*f*m-b*k;n[9]=e*b*m+f*k;n[10]=e*e*m+l;n[11]=0;n[12]=0;n[13]=0;n[14]=0;n[15]=1;return g};c.Ea=function(a,d,b,e){e=e||c();var g=e.a;d=V(a.o(d));b=V(b.s(d));var n=V(d.s(b));g[0]=b.x;g[1]=b.y;g[2]=b.z;g[3]=-b.l(a);g[4]=n.x;g[5]=n.y;g[6]=n.z;g[7]=-n.l(a);g[8]=d.x;g[9]=d.y;g[10]=d.z;g[11]=-d.l(a);g[12]=0;g[13]=0;
g[14]=0;g[15]=1;return e};c.Wa=function(a){A(a);var d=Math.cos(a);a=Math.sin(a);return c([1,0,0,0,0,d,-a,0,0,a,d,0,0,0,0,1])};c.Xa=function(a){var d=Math.cos(a);a=Math.sin(a);return c([d,0,a,0,0,1,0,0,-a,0,d,0,0,0,0,1])};c.ab=function(a){var d=Math.cos(a);a=Math.sin(a);return c([d,-a,0,0,a,d,0,0,0,0,1,0,0,0,0,1])};c.Pa=function(a,d,b,e){e=e||c();d=d.A();var g=a.x,n=a.y;a=a.z;var l=d.x,k=d.y;d=d.z;var m=e.a,u=Math.cos(b);b=Math.sin(b);m[0]=l*l+(k*k+d*d)*u;m[1]=l*k*(1-u)-d*b;m[2]=l*d*(1-u)+k*b;m[3]=
(g*(k*k+d*d)-l*(n*k+a*d))*(1-u)+(n*d-a*k)*b;m[4]=l*k*(1-u)+d*b;m[5]=k*k+(l*l+d*d)*u;m[6]=k*d*(1-u)-l*b;m[7]=(n*(l*l+d*d)-k*(g*l+a*d))*(1-u)+(a*l-g*d)*b;m[8]=l*d*(1-u)-k*b;m[9]=k*d*(1-u)+l*b;m[10]=d*d+(l*l+k*k)*u;m[11]=(a*(l*l+k*k)-d*(g*l+n*k))*(1-u)+(g*k-n*l)*b;m[12]=0;m[13]=0;m[14]=0;m[15]=1;return e};c.Fa=function(a,d){var b=a.g.x,e=a.g.y,g=a.g.z,n=a.u;d=d||c();var l=d.a;l[0]=1-2*b*b;l[1]=-2*e*b;l[2]=-2*g*b;l[3]=0;l[4]=-2*b*e;l[5]=1-2*e*e;l[6]=-2*g*e;l[7]=0;l[8]=-2*b*g;l[9]=-2*e*g;l[10]=1-2*g*g;
l[11]=0;l[12]=2*b*n;l[13]=2*e*n;l[14]=2*g*n;l[15]=1;return d};c.sa=function(a,d,b){d=d||a.g;var e=a.g.x,g=a.g.y,n=a.g.z,l=d,k=l.x,m=l.y,l=l.z,u=a.u;b=b||c();var v=b.a;a=a.g.l(d);k/=a;m/=a;l/=a;v[0]=1-e*k;v[1]=-g*k;v[2]=-n*k;v[3]=k*u;v[4]=-e*m;v[5]=1-g*m;v[6]=-n*m;v[7]=m*u;v[8]=-e*l;v[9]=-g*l;v[10]=1-n*l;v[11]=l*u;v[12]=0;v[13]=0;v[14]=0;v[15]=1;return b};c.Ca=function(a,d){var b=a.h.x,e=a.h.y,g=a.h.z,n=a.anchor.x,l=a.anchor.y,k=a.anchor.z;d=d||c();var m=d.a;m[0]=b*b;m[1]=b*e;m[2]=b*g;m[3]=n;m[4]=
e*b;m[5]=e*e;m[6]=e*g;m[7]=l;m[8]=g*b;m[9]=g*e;m[10]=g*g;m[11]=k;m[12]=0;m[13]=0;m[14]=0;m[15]=1};c.Ha=function(){var a=arguments;if(0==a.length)return c.K();for(var d=c(),b=a[0].G(),e=1;e<a.length;e++)c.j(b,a[e],d),b=ca([b,d]),d=b.next().value,b=b.next().value;return b};c.Ja=function(a,d){d=d||c();var b=d.a;b[0]=-1;b[1]=0;b[2]=0;b[3]=2*a.x;b[4]=0;b[5]=-1;b[6]=0;b[7]=2*a.y;b[8]=0;b[9]=0;b[10]=-1;b[11]=2*a.z;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return d};c.ca=c();c.R=c();c.U=c(0,1,1,2,3,4,8,13,21,34,55,
89,0,0,0,1);c.da=c.U.W();a.Da=c})(y);function X(a,c){c.O(1);var d=Object.create(X.prototype);d.anchor=a;d.h=c;return d}
X.prototype={f:function(a){y.assert(a instanceof X);var c=Y(this,a.anchor);A(c);return y.c(c)&&y.f(1,Math.abs(this.h.l(a.h)))},M:function(a){if(a.g)a=a.M(this);else if(a.h)if(y.assert(a instanceof X),y.f(1,Math.abs(this.h.l(a.h))))a=Y(this,a.anchor);else{var c=V(this.h.s(a.h));a=Math.abs(this.anchor.o(a.anchor).l(c))}else a=Y(this,a);return a},toString:function(a){a=a||function(a){return+a.toFixed(4)};return"L3("+this.anchor.toString(a)+", "+this.h.toString(a)+")"},transform:function(a){var c=a.w(this.anchor);
a=a.ba(this.h);return X(c,a.A())}};function Y(a,c){var d=c.o(a.anchor).l(a.h);A(d);return a.anchor.B(a.h.v(d)).M(c)}y.T(X.prototype);Object.defineProperties(X,{Ma:{value:X(U,ka)},Na:{value:X(U,W)},Oa:{value:X(U,la)}});y.Ba=X;function Z(a,c,d){y.m(c);a.O(1);d=Object.create(d||Z.prototype);d.g=a;d.u=c;return d}
Z.prototype={get anchor(){return this.g.v(this.u)},P:function(a){return y.f(this.u,a.u)&&this.g.P(a.g)},toString:function(a){a=a||function(a){return a};return"P3("+this.g.toString(a)+", "+a(this.u)+")"},transform:function(a){var c=a.na(),d;var e=this.g;if(y.c(e.x)&&y.c(e.y)){if(y.c(e.z))throw Error("zero vector");d=W}else d=S(-e.y,e.x,0);var g=d.s(this.g),e=a.w(this.anchor),g=a.w(this.anchor.B(g));a=a.w(this.anchor.B(d));d=c?g:a;c=(c?a:g).o(e).s(d.o(e)).A();return Z(c,c.l(e),void 0)}};y.T(Z.prototype);
Z(ka,0);Z(W,0);Z(la,0);y.Ga=Z;
