brep.js:860: WARNING - Suspicious code. This code lacks side-effects. Is there a bug?
		if (!addedFaces) {
		^

0 error(s), 1 warning(s)
var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};
$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(b,d);void 0!==e&&$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};"min max PI sqrt pow round".split(" ").forEach(function(a){window[a]=Math[a]});function BREP(a,b,c,d,e){this.vertices=a;this.edges=b;this.faces=c;this.infiniteVolume=d||!1;this.source=e}
var M4=NLA.Matrix4x4,V3=NLA.Vector3,P3=NLA.Plane3,L3=NLA.Line3;BREP.box=function(a,b,c){a=[V3(0,0,0),V3(0,b,0),V3(a,b,0),V3(a,0,0)];return BREP.extrude(a,P3(V3.Z.negated(),0),V3(0,0,c))};var faceId=0;
BREP.Face=function(a,b,c){assert(!b||b instanceof P3,"plane is not a P3");NLA.assertVectors.apply(null,a);this.vertices=a;this.name=c;this.plane=b?b:P3.throughPoints(a[0],a[1],a[2]);assert(!b||a.every(function(a){return b.containsPoint(a)}),"all vertices must be contained within the plane");assert(Array.from(BREP.Face.segmentsIterator(a)).every(function(a){return!a[0].like(a[1])}),"no degenerate segments"+a.map(function(a){return a.ss}).join(","));isCCW(a,this.plane.normal)||(this.plane=this.plane.flipped());
this.id=faceId++};BREP.Face.segmentsIterator=function(a){function b(b,e){for(;;)switch(c){case 0:d=0;case 1:if(!(d<a.length)){c=3;break}c=4;return{value:[a[d],a[(d+1)%a.length]],done:!1};case 4:if(void 0===e){c=5;break}c=-1;throw e;case 5:case 2:d++;c=1;break;case 3:c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e={next:function(a){return b(a,void 0)},throw:function(a){return b(void 0,a)}};$jscomp.initSymbolIterator();e[Symbol.iterator]=function(){return this};return e};
BREP.prototype.flipped=function(){return new BREP(null,null,this.faces.map(function(a){return a.flipped()}),!this.infiniteVolume,this.source+".flipped()")};BREP.prototype.toSource=BREP.prototype.toString=function(){return this.source||Object.toSource.apply(this)};BREP.prototype.transform=function(a){return new BREP(null,null,this.faces.map(function(b){return b.transform(a)}),this.infiniteVolume)};
BREP.prototype.minus=function(a){return this.clipped(a,!0,!0).newAll(a.flipped().clipped(this.flipped(),!0,!1))};BREP.prototype.plus=function(a){return this.clipped(a,!0,!0).newAll(a.clipped(this,!1,!0))};BREP.segmentIntersectsVertexLoop=function(a,b,c){};
BREP.Face.prototype={what:"Face",toString:function(){return"new BREP.Face(["+this.vertices.map(function(a){return a.toString()}).join(", ")+"], "+this.plane.toString()+")"},toSource:function(){return this.toString()},equals:function(a){return this.vertices.length==a.vertices.length&&this.vertices.some(function(b,c,d){return a.vertices.every(function(a,b){return a.like(d[(c+b)%d.length])})})},constructor:BREP.Face,containsPoint:function(a){assert(a instanceof V3,"point was"+a.toString());assert(this.plane.containsPoint(a),
"this.plane.containsPoint(point)"+this.plane.distanceToPointSigned(a));for(var b=this.vertices,c=b[0].minus(b[b.length-1]),d=b.length-1,e=!1;d--;)segmentIntersectsRay(b[d],b[d+1],a,c)&&(e=!e);return e},containsPoint2:function(a,b){assert(a instanceof V3,"point was"+a.toString());assert(this.plane.containsPoint(a));var c=this.vertices.map(function(b){return b.minus(a)});if(c[0].isZero())return b;for(var d=0,e=0;e<c.length;e++){var g=c[e],n=c[(e+1)%c.length];if(n.isZero())return b;g=g.angleRelativeNormal(n,
this.plane.normal);if(NLA.eqAngle(Math.PI,g))return b;d+=g}return!NLA.isZero(d)},pointsToInside:function(a,b,c){var d=this,e=this.vertices.map(function(c,e,f){var m=f[(e+1)%f.length];e=f[(e-1+f.length)%f.length];return c==a?(console.log("sadas",b.angleRelativeNormal(m.minus(c),d.plane.normal).toSource(),m.minus(c).toSource()),[{reversed:!1,angle:(b.angleRelativeNormal(m.minus(c),d.plane.normal)+2*Math.PI+NLA.PRECISION/2)%(2*Math.PI)},{reversed:!0,angle:(b.angleRelativeNormal(e.minus(c),d.plane.normal)+
2*Math.PI+NLA.PRECISION/2)%(2*Math.PI)}]):[]}).concatenated().sort(function(a,b){return a.angle-b.angle});assert(0!=e.length,"ff.length != 0");return NLA.isZero(e[0].angle)?c:e[0].reversed},flipped:function(){return new BREP.Face(this.vertices.slice().reverse(),this.plane.flipped(),this.name+"flipped")},intersectsLine:function(a){assert(a instanceof L3);var b=a.intersectWithPlaneLambda(this.plane);return Number.isFinite(b)?this.containsPoint(a.at(b))?b:NaN:NaN},withHole:function(a){var b=this.vertices,
c,d,e;for(d=0;d<b.length;d++){var g=b[d];for(e=0;e<a.length;e++){var n=a[e];c=!1;for(var f=d+1;f<b.length+d-1;f++){var m=b[f%b.length],k=b[(f+1)%b.length];if(segmentsTouchOrIntersect(g,n,m,k)){c=!0;break}}if(!c){for(f=e+1;f<a.length+e-1;f++)if(m=a[f%a.length],k=a[(f+1)%a.length],segmentsTouchOrIntersect(g,n,m,k)){c=!0;break}if(!c)break}}if(!c)break}if(c)throw Error("");a=a.slice(e).concat(a.slice(0,e+1));b=b.slice(0,d+1).concat(a,b.slice(d));console.log(b.toSource());return new BREP.Face(b,this.plane,
this.name+"holed")},transform:function(a){return new BREP.Face(a.transformedPoints(this.vertices),this.plane.transform(a),this.name)}};NLA.addTransformationMethods(BREP.Face.prototype);NLA.addTransformationMethods(BREP.prototype);BREP.prototype.ss=function(){return"new BREP(null, null, ["+this.faces.map(function(a){return"new BREP.Face(["+a.vertices.map(function(a){return a.toString(function(a){return a})}).join(",")+"], "+a.plane.toString(function(a){return a})+")"}).join(",")+"])"};
BREP.prototype.equals=function(a){return this.faces.length==a.faces.length&&this.faces.every(function(b){return a.faces.some(function(a){return b.equals(a)})})};
BREP.prototype.toMesh=function(){function a(a,b){var c=min(a,b),e=max(a,b);return c<<16|e}function b(a){var b=c.get(a);void 0===b&&(b=e.vertices.length,c.set(a,b),e.vertices.push(a.toArray()));return b}var c=new Map,d=new Set,e=new GL.Mesh({normals:!1,colors:!1,lines:!0});this.faces.forEach(function(c){var n=triangulateVertices(c.plane.normal,c.vertices);c=c.vertices;for(var f=0;f<n.length;f+=3){var m=b(c[n[f]]),k=b(c[n[f+1]]),h=b(c[n[f+2]]);e.triangles.push(m,k,h)}for(f=0;f<c.length;f++)n=b(c[f]),
m=b(c[(f+1)%c.length]),d.add(a(n,m))});d.forEach(function(a){return e.lines.push([a>>16,a&65535])});e.compile();return e};
BREP.prototype.toNormalMesh=function(){function a(a,b){var c=min(a,b),e=max(a,b);return c<<16|e}function b(a){var b=c.get(a);void 0===b&&(b=e.vertices.length,c.set(a,b));return b}var c=new Map,d=new Set,e=new GL.Mesh({normals:!0,colors:!1,lines:!0}),g=new Map;this.faces.forEach(function(c){var f=triangulateVertices(c.plane.normal,c.vertices),m=c.vertices,k=e.vertices.length;g.set(c,{start:3*e.triangles.length,count:f.length});m.forEach(function(a){b(a);e.vertices.push(a);e.normals.push(c.plane.normal)});
for(var h=0;h<f.length;h+=3)e.triangles.push(k+f[h],k+f[h+1],k+f[h+2]);for(h=0;h<m.length;h++)f=b(m[h]),k=b(m[(h+1)%m.length]),d.add(a(f,k))});d.forEach(function(a){return e.lines.push([a>>16,a&65535])});e.faceIndexes=g;e.compile();return e};function segmentIntersectsRay(a,b,c,d){b=(a=segmentIntersectsLineST(a,b,c,d))&&a.segmentAt;c=a&&a.lineAt;return a&&0<b&&1>b&&0<c}
function segmentIntersectsLineST(a,b,c,d){b=b.minus(a);var e=b.cross(d),g=e.lengthSquared();if(NLA.isZero(g))return null;a=c.minus(a);d=a.cross(d).dot(e)/g;b=a.cross(b).dot(e)/g;return{segmentAt:d,lineAt:b}}function segmentSegmentIntersectionST(a,b,c,d){b=b.minus(a);var e=d.minus(c);d=b.cross(e);var g=d.lengthSquared();a=c.minus(a);c=a.cross(e).dot(d)/g;b=a.cross(b).dot(d)/g;return{s:c,t:b}}
function segmentsTouchOrIntersect(a,b,c,d){b=segmentSegmentIntersectionST(a,b,c,d);a=b.s;b=b.t;return(NLA.equals(a,0)||NLA.equals(a,1)||0<a&&1>a)&&(NLA.equals(b,0)||NLA.equals(b,1)||0<b&&1>b)}
BREP.extrude=function(a,b,c,d){assert(a.every(function(a){return a instanceof V3}),"baseVertices.every(v => v instanceof V3)");assert(b instanceof P3,"baseFacePlane instanceof P3");assert(c instanceof V3,"offset must be V3");0<b.normal.dot(c)&&(b=b.flipped());isCCW(a,b.normal)||(a=a.reverse());for(var e=a.map(function(a){return a.plus(c)}).reverse(),g=[new BREP.Face(a,b,d+"base"),new BREP.Face(e,b.flipped().translated(c),d+"roof")],n=a.length,f=0;f<n;f++)g.push(new BREP.Face([a[(f+1)%n],a[f],e[n-
1-f],e[n-1-(f+1)%n]],void 0,d+"wall"+f));return new BREP(null,null,g,!1,"BREP.extrude("+a.toSource()+", "+b.toString()+", "+c.ss+', "'+d+'")')};BREP.prototype.union=function(a){};function arrayFilterMap(a,b){for(var c=[],d=0;d<a.length;d++){var e=b(a[d]);void 0!==e&&c.push(e)}return c}function outsideVector(a,b){return a[1].minus(a[0]).cross(b)}BREP.prototype.newAll=function(a){return new BREP(null,null,this.faces.concat(a.faces),this.infiniteVolume)};
function facesWithEdge(a,b){return arrayFilterMap(b,function(b){for(var d=0;d<b.vertices.length;d++){var e=b.vertices[d],g=b.vertices[(d+1)%b.vertices.length];if(e.like(a[0])&&g.like(a[1])||e.like(a[1])&&g.like(a[0]))return{face:b,edgeVector:segmentVector(a),ov:outsideVector([e,g],b.plane.normal),reversed:!e.like(a[0])}}})}function segmentVector(a){return a[1].minus(a[0])}
function splitsVolumeEnclosingFaces(a,b,c,d,e,g){var n=segmentVector(b).normalized();a=facesWithEdge(b,a.faces).map(function(a){return{face:a,angle:(c.angleRelativeNormal(a.ov.negated(),n)+2*Math.PI+NLA.PRECISION/2)%(2*Math.PI)}}).sort(function(a,b){return a.angle-b.angle});assert(0!=a.length);return NLA.isZero(a[0].angle)?0<a[0].face.face.plane.normal.dot(d)?assert(void 0!==e)&&e:assert(void 0!==g)&&g:!a[0].face.reversed}
function getFacePlaneIntersectionSs2(a,b,c,d,e,g){var n=[];b.vertices.forEach(function(f,m,k){var h=k[(m+1)%k.length];m=k[(m+2)%k.length];console.log("segment",f.toString(),h.toString());var q=(k=segmentIntersectsLineST(f,h,c.anchor,c.dir1))&&k.segmentAt,u=k&&k.lineAt;k?NLA.equals(q,1)?(k=d.distanceToPointSigned(m),NLA.isZero(k)?0>outsideVector([h,m],b.plane.normal).dot(segmentVector([f,h]))&&n.push({t:c.pointLambda(h),on:[f,h],p:h,endpoint:!0}):0>k*d.distanceToPointSigned(f)&&(console.log("HHHEELEO",
k,h.toString(),c.pointLambda(h)),n.push({t:c.pointLambda(h),on:[f,h],p:h,endpoint:!0}))):q>NLA.PRECISION&&q<1-NLA.PRECISION&&(console.log("HHHEELE2O",h.toString(),c.pointLambda(h)),n.push({t:u,on:[f,h],p:c.at(u)})):c.containsPoint(f)&&(console.log("getFacePLaneINter",c.toString(),f.toString()),k=d.normal,console.log("brep2.infiniteVolume",a.infiniteVolume),splitsVolumeEnclosingFaces(a,[f,h],d.projectedVector(b.plane.normal),k,e,g)!=splitsVolumeEnclosingFaces(a,[f,h],d.projectedVector(b.plane.normal).negated(),
k,e,g)&&(n.push({t:c.pointLambda(f),on:[f,h],p:f,endpoint:!0}),n.push({t:c.pointLambda(h),on:[f,h],p:h,endpoint:!0})),0<outsideVector([f,h],b.plane.normal).dot(segmentVector([h,m]))&&n.push({t:c.pointLambda(h),on:[f,h],p:h,endpoint:!0}))});assert(0==n.length%2,"xss.length % 2 == 0");return n.sort(function(a,b){return a.t-b.t})}
function getFacePlaneIntersectionSs(a,b,c,d,e,g,n){var f=[],m=b.vertices.map(function(a){return NLA.snapTo(d.distanceToPointSigned(a),0)}),k=b.vertices.map(function(c,f,k){var n=(f+1)%k.length;k=k[n];var r=d.normal;return NLA.isZero(m[f])&&NLA.isZero(m[n])&&splitsVolumeEnclosingFaces(a,[c,k],d.projectedVector(b.plane.normal),r,e,g)!=splitsVolumeEnclosingFaces(a,[c,k],d.projectedVector(b.plane.normal).negated(),r,e,g)});b.vertices.forEach(function(a,e,d){var g=(e+1)%d.length,r=(e+2)%d.length,l=d[(e+
1)%d.length];d=d[(e+2)%d.length];0==m[e]?0==m[g]&&(0==m[r]?k[g]:0<outsideVector([a,l],b.plane.normal).dot(segmentVector([l,d])))!=k[e]&&f.push({t:c.pointLambda(l),on:[a,l],p:l,endpoint:!0}):0==m[g]?0==m[r]?0>outsideVector([l,d],b.plane.normal).dot(segmentVector([a,l]))!=k[g]&&f.push({t:c.pointLambda(l),on:[a,l],p:l,endpoint:!0}):0>m[e]*m[r]&&f.push({t:c.pointLambda(l),on:[a,l],p:l,endpoint:!0}):0>m[e]*m[g]&&(e=n.canonicalizeLike(a.lerp(l,m[e]/(m[e]-m[g]))),f.push({t:c.pointLambda(e),on:[a,l],p:e,
endpoint:!1}))});assert(0==f.length%2,"faceEdgePlaneIntersections.length % 2 == 0");return f.sort(function(a,b){return a.t-b.t})}
BREP.prototype.clipped=function(a,b,c){function d(a,b,c){var e=segmentVector(a);c=c.filter(function(b){return g(a,b.faceSegment)||g(a,b.projectedSegment)}).map(function(a){return{is:a,t:a.p.minus(b).dot(e)}}).filter(function(a){return 0<a.t}).sort(function(a,b){return a.t-b.t});return 0==c.length?a[1]:c[0].is.p}function e(a,b){return b.filter(function(b){return b.p.like(a)})}function g(a,b){return a[0].like(b[0])&&a[1].like(b[1])}var n=new NLA.CustomSet,f=[];this.faces.forEach(function(g){function k(a,
b,c,e){a=a.map(function(a){return a[0].like(b)||a[1].like(b)?[{reversed:a[0].like(b),angle:(c.angleRelativeNormal(segmentVector(a),g.plane.normal)+2*Math.PI+NLA.PRECISION/2)%(2*Math.PI)}]:[]}).concatenated().sort(function(a,b){return a.angle-b.angle});assert(0!=a.length,"ff.length != 0");console.log(c.toSource(),"dirr",c.toSource(),a);return NLA.isZero(a[0].angle)?e:a[0].reversed}var h=0,q=g.plane,u=[],v=[];a.faces.forEach(function(e){var d=e.plane;if(!q.isParallelToPlane(d)){var f=L3.fromPlanes(q,
d);e=getFacePlaneIntersectionSs(a,e,f,q,b,c,n);for(var d=f.dir1.cross(q.normal).dot(d.normal),h=0;h<e.length;h+=2){var k=e[h],l=e[h+1],p=0>d?[k.p,l.p]:[l.p,k.p],r=0>d?k.t:l.t,t=0>d?l.t:k.t;u.push(p);g.vertices.forEach(function(a,b,c){b=c[(b+1)%c.length];var e=(c=segmentIntersectsLineST(a,b,f.anchor,f.dir1))&&c.segmentAt,d=c&&c.lineAt;if(c){var e=NLA.snapTo(e,0),e=NLA.snapTo(e,1),d=NLA.snapTo(d,r),d=NLA.snapTo(d,t),h;0==e&&(d>k.t&&d<l.t||d==t)?h=a:0<e&&1>e&&d>=k.t&&d<=l.t?h=d==k.t?k.p:d==l.t?l.p:f.at(d):
1==e&&(d>k.t&&d<l.t||d==r)&&(h=b);h&&(a={faceSegment:[a,b],projectedSegment:p,p:h,projectedEndpoint:d==t,edgeEndpoint:1==e,edgeStartpoint:0==e,projectedStartpoint:d==r},v.push(a),a.edgeEndpoint?(a=segmentVector(a.projectedSegment),console.log("face.pointsToInside(point, dirr)",g.pointsToInside(h,a,!1)),g.pointsToInside(h,a,!1)||(console.log("popping is"),v.pop())):a.edgeStartpoint&&0<segmentVector(a.faceSegment).dot(outsideVector(a.projectedSegment,g.plane.normal))&&v.pop())}else f.containsPoint(a)})}}});
v=v.filter(function(a){return a.projectedEndpoint?k(u,a.p,segmentVector(a.faceSegment),!1):!0});console.log("face.vertices",g.vertices);if(0==u.length)console.log("brep2.infiniteVolume",a.infiniteVolume),a.infiniteVolume||(l=g.vertices.slice(),f.push(new BREP.Face(l,q,g.name)));else for(var r=0;u.some(function(a){return!a.visited})||v.some(function(a){return!a.visited});){r++;console.log("new face");var l=[],y=0,t=!0,p=v.find(function(a){return!a.visited}),w,z=null,A,E=!1;if(p)t=p,A=(t=t.projectedStartpoint||
!t.edgeEndpoint&&0<outsideVector(p.projectedSegment,g.plane.normal).dot(segmentVector(t.faceSegment)))?p.faceSegment[0]:p.projectedSegment[0],w=p=p.p;else if(w=u.find(function(a){return!a.visited}))w.visited=!0,console.log("unvisitedSegment",w),E=!0,p=w[1],A=w[0],w=p;else break;var G=!0,B,F=0;do{var I=e(p,v),D=p.minus(A),x=-Infinity,C;I.forEach(function(a){a.visited=r;if(!a.projectedEndpoint){var b=a.projectedSegment[1].minus(p),b=D.angleRelativeNormal(b,q.normal);b>x&&(x=b,C=a.projectedSegment,B=
!0)}a.edgeEndpoint||(b=a.faceSegment[1].minus(p),b=D.angleRelativeNormal(b,q.normal),b>x&&(x=b,C=a.faceSegment,B=!1))});t||g.vertices.forEach(function(a,b,c){b=c[(b+1)%c.length];a.like(p)&&(c=b.minus(a),c=D.angleRelativeNormal(c,q.normal),c>x&&(x=c,C=[a,b],B=!1))});if(E&&u.some(function(a){return a[0].like(A)&&a[1].like(p)&&a.visited&&a.visited!=r})){G=!1;break}u.forEach(function(a){a[0].like(A)&&a[1].like(p)&&(a.visited=r)});t&&u.forEach(function(a){var b=a[0],c=a[1];b.like(p)&&(b=c.minus(b),b=D.angleRelativeNormal(b,
q.normal),b>x&&(x=b,C=a,B=!0))});assert(C);F+=+(t!=B);t=B;l.push(p);A=p;p=d(C,p,v);z||(z=p)}while((!A.equals(w)||!z.equals(p))&&20>y++||0==y);20<=y&&assert(!1,"too many");if(G)if(l.pop(),!E&&1<F)f.push(new BREP.Face(l,q,g.name)),console.log("add face 3"),h++;else{console.log("is hole",g.vertices[0].ss,(new BREP.Face(l)).containsPoint(g.vertices[0]));console.log("newFaceVertices",(new BREP.Face(l)).toString());console.log("reverseblash",(new BREP.Face(l)).containsPoint(g.vertices[0]));var H=new BREP.Face(l,
q,g.name),y=g.vertices.every(function(a){return H.containsPoint2(a,!0)}),z=H.vertices.every(function(a){console.log(a.ss,g.containsPoint2(a,!0));return g.containsPoint2(a,!0)});console.log("loopContainsFace",y,"faceContainsLoop",z);y&&z?f.push(new BREP.Face(l,g.plane,g.name)):y?(console.log("loopContainsFace",a.infiniteVolume),a.infiniteVolume&&(l=g.vertices.slice(),f.push(new BREP.Face(l,q,g.name)),console.log("add face 4"))):z?(a.infiniteVolume?f.push(new BREP.Face(l,g.plane,g.name)):f.push(g.withHole(l)),
h++):a.infiniteVolume||(l=g.vertices.slice(),f.push(new BREP.Face(l,q,g.name)),console.log("add face 1"))}}});return new BREP(null,null,f,this.infiniteVolume)};
function testBREP(){try{var a=new BREP.Face([V3(0,0,0),V3(10,0,0),V3(10,10,0),V3(0,10,0)],P3.XY);new BREP.Face([V3(5,0,5),V3(5,5,5),V3(0,5,5),V3(0,0,5)],P3(V3.Z,5));new BREP.Face([V3(5,0,0),V3(5,5,0),V3(0,5,0),V3(0,0,0)].reverse(),P3(V3.Z.negated(),0));new BREP.Face([V3(0,0,-6),V3(10,0,-6),V3(11,10,0),V3(0,10,0)]);new BREP.Face([V3(10,0,0),V3(10,0,-6),V3(11,10,0)]);new BREP.Face([V3(5,8,-5),V3(9,12,1),V3(5,8,5)]);new BREP.Face([V3(5,8,-5),V3(5,8,5),V3(1,12,2)]);new BREP.Face([V3(5,8,-5),V3(1,12,2),
V3(9,12,1)]);V3(2,3,0);V3(8,7,0);V3(7,2,0);var b=new BREP(null,null,[a]),c=BREP.tetrahedron(V3(5,10,0),V3(15,10,0),V3(5,5,0),V3(5,10,-2)),b=new BREP(null,null,[new BREP.Face([V3(0,0,0),V3(0,1,0),V3(0,1,5),V3(0,0,5)])]),b=new BREP(null,null,[new BREP.Face([V3(0,0,0),V3(0,1,0),V3(0,1,5),V3(0,0,5)])]),b=new BREP(null,null,[new BREP.Face([V3(5,0,0),V3(5,5,0),V3(0,5,0),V3(0,0,0)].reverse(),P3(V3.Z.negated(),0))]),b=BREP.box(5,5,5),c=BREP.box(1,1,5).translate(1,1,1),b=BREP.extrude([V3(0,0,0),V3(10,0,0),
V3(0,10,0)],P3.XY,V3(0,0,-5),"ex0"),c=BREP.extrude([V3(0,4,-5),V3(0,0,-5),V3(0,4,-2)],P3.YZ.flipped().translate(0,0,0),V3(13,0,0),"ex1").translate(6,2,0);BREP.extrude([V3(5,5,0),V3(5,8,0),V3(8,10,-2),V3(2,11,2)].reverse(),P3.normalOnAnchor(V3(-2,0,-3),V3(5,5,0)),V3(4,0,6));aMesh=b.toMesh();bMesh=c.toMesh();console.log("css",c.ss());var d=b.minus(c);cMesh=d.toNormalMesh();console.log("css",d.ss())}catch(e){console.log(e)}paintScreen2()}
function triangulateVertices(a,b,c){var d=a.absMaxDim();a=0>a.e(d)?-1:1;for(var e=Array(2*b.length),g=b.length;g--;)switch(d){case 0:e[2*g]=b[g].y*a;e[2*g+1]=b[g].z;break;case 1:e[2*g]=b[g].z*a;e[2*g+1]=b[g].x;break;case 2:e[2*g]=b[g].x*a,e[2*g+1]=b[g].y}return earcut(e,c)}
function doubleSignedArea(a,b){assert(!b.isZero(),"!normal.isZero()");var c=b.absMaxDim(),d=a.map(function(a,b,d){b=d[(b+1)%d.length];switch(c){case 0:return(b.y-a.y)*(b.z+a.z);case 1:return(b.z-a.z)*(b.x+a.x);case 2:return(b.x-a.x)*(b.y+a.y)}}).reduce(function(a,b){return a+b});return NLA.snapTo(d*Math.sign(b.e(c)),0)}function isCCW(a,b){var c=doubleSignedArea(a,b);assert(0!=c);return 0>c}
var planes=[CustomPlane(V3.ZERO,V3.Y,V3.Z,-500,500,-500,500,16711680),CustomPlane(V3.ZERO,V3.X,V3.Z,-500,500,-500,500,65280),CustomPlane(V3.ZERO,V3.X,V3.Y,-500,500,-500,500,255)];BREP.tetrahedron=function(a,b,c,d){var e=P3.throughPoints(a,b,c).distanceToPointSigned(d);if(NLA.isZero(e))throw Error("four points are coplanar");a=[[a,b,c],[a,d,b],[b,d,c],[c,d,a]];0<e&&a.forEach(function(a){return a.reverse()});return new BREP(null,null,a.map(function(a){return new BREP.Face(a)}))};
var singleColorShader,textureColorShader,singleColorShaderHighlight,arcShader,arcShader2,xyLinePlaneMesh,gl,cubeMesh,lightingShader,vectorMesh;
window.loadup=function(){window.onerror=function(a,b,c,d,e){console.log(a,b,c,d,e)};gl=GL.create({canvas:document.getElementById("testcanvas")});gl.fullscreen();gl.canvas.oncontextmenu=function(){return!1};gl.scaleVector=function(a,b,c){gl.multMatrix(M4.scaleVector(a,b,c))};gl.translateVector=gl.translateV3;gl.scaleVector=gl.scaleV3;assert(NLA.equals(-PI/2,V3.Y.times(3).angleRelativeNormal(V3.Z.times(-2),V3.X)));setupCamera();gl.clearColor(1,1,1,0);gl.enable(gl.BLEND);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
gl.depthFunc(gl.LEQUAL);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);cubeMesh=GL.Mesh.cube();gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.loadIdentity();gl.scale(10,10,10);gl.loadIdentity();gl.onmousemove=function(a){if(a.dragging){if(a.buttons&4){var b=V3(2*-a.deltaX/gl.canvas.width,2*a.deltaY/gl.canvas.height,0),b=gl.projectionMatrix.inversed().transformVector(b);eyePos=eyePos.plus(b);eyeFocus=eyeFocus.plus(b);setupCamera();paintScreen2()}if(a.buttons&2){b=deg2rad(-a.deltaX/6);a=deg2rad(-a.deltaY/
6);var b=M4.rotation(b,eyeUp),c=eyeFocus.minus(eyePos).cross(eyeUp),b=b.times(M4.rotation(a,c));eyePos=b.transformVector(eyePos);eyeUp=b.transformVector(eyeUp);setupCamera();paintScreen2()}}};xyLinePlaneMesh=new GL.Mesh({lines:!0,triangles:!1});xyLinePlaneMesh.vertices=[[0,0],[0,1],[1,1],[1,0]];xyLinePlaneMesh.lines=[[0,1],[1,2],[2,3],[3,0]];xyLinePlaneMesh.compile();vectorMesh=rotationMesh([V3.ZERO,V3(0,.05,0),V3(.8,.05),V3(.8,.1),V3(1,0)],L3.X,2*Math.PI,8,!1);singleColorShader=new GL.Shader(vertexShaderBasic,
fragmentShaderColor);singleColorShaderHighlight=new GL.Shader(vertexShaderBasic,fragmentShaderColorHighlight);textureColorShader=new GL.Shader(vertexShaderTextureColor,fragmentShaderTextureColor);arcShader=new GL.Shader(vertexShaderRing,fragmentShaderColor);arcShader2=new GL.Shader(vertexShaderArc,fragmentShaderColor);lightingShader=new GL.Shader(vertexShaderLighting,fragmentShaderLighting);$(gl.canvas).addEvent("mousewheel",function(a){zoomFactor*=pow(.9,-a.wheel);var b=a.client;a=V3(2*b.x/gl.canvas.width-
1,2*-b.y/gl.canvas.height+1,0).times(1-1/pow(.9,-a.wheel));a=gl.projectionMatrix.inversed().transformVector(a);eyePos=eyePos.plus(a);eyeFocus=eyeFocus.plus(a);setupCamera();paintScreen2()});testBREP()};var aMesh,bMesh,cMesh;
function paintScreen2(){gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.loadIdentity();gl.scale(10,10,10);gl.loadIdentity();aMesh&&(gl.projectionMatrix.m[11]-=1/8388608,singleColorShader.uniforms({color:rgbToVec4(COLORS.PP_STROKE)}).draw(aMesh,gl.LINES),gl.projectionMatrix.m[11]+=1/8388608,singleColorShader.uniforms({color:rgbToVec4(COLORS.PP_FILL)}).draw(aMesh));bMesh&&(gl.pushMatrix(),gl.projectionMatrix.m[11]-=1/8388608,singleColorShader.uniforms({color:rgbToVec4(COLORS.TS_STROKE)}).draw(bMesh,
gl.LINES),gl.projectionMatrix.m[11]+=1/8388608,singleColorShader.uniforms({color:rgbToVec4(COLORS.TS_FILL)}).draw(bMesh),gl.popMatrix());cMesh&&(gl.pushMatrix(),gl.translate(40,0,0),gl.projectionMatrix.m[11]-=1/8388608,singleColorShader.uniforms({color:rgbToVec4(COLORS.RD_STROKE)}).draw(cMesh,gl.LINES),gl.projectionMatrix.m[11]+=1/8388608,singleColorShader.uniforms({color:rgbToVec4(COLORS.RD_FILL)}).draw(cMesh),gl.popMatrix());drawPlanes()};
