var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};
$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(b,d);void 0!==e&&$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};"min max PI sqrt pow round".split(" ").forEach(function(a){window[a]=Math[a]});
var M4=NLA.Matrix4x4,V3=NLA.Vector3,P3=NLA.Plane3,L3=NLA.Line3,eps=1E-5,B2=NLA.degineClagg("B2",NLA.Transformable,function(a,b){this.faces=a;assert(a.every(function(a){return a instanceof B2.Face}),"faces.every(f => f instanceof B2.Face)\n"+this.toString());this.infiniteVolume=!!b},{toMesh:function(){var a=new GL.Mesh({triangles:!0,normals:!0,lines:!0});this.faces.forEach(function(b,c){b.addToMesh(a)});a.compile();return a},minus:function(a){return this.intersection(a.flipped(),!0,!0)},plus:function(a){return this.flipped().intersection(a.flipped(),
!0,!0).flipped()},equals:function(a){return this.faces.length==a.faces.length&&this.faces.every(function(b){return a.faces.some(function(a){return b.equals(a)})})},toString:function(){return"new B2([\n"+this.faces.join(",\n").replace(/^/gm,"\t")+"])"},toSource:function(){return"new B2([\n"+this.faces.map(function(a){return a.toSource()}).join(",\n").replace(/^/gm,"\t")+"])"},assembleFacesFromLoops:function(a,b,c){function d(a,c){if(0==c.length)c.push(a);else{var b=c.find(function(c){c=f.edgeLoopContainsPoint(c.edges,
a.edges[0].a);console.log(a.edges[0].a.ss,a.ccw?c:!c);return c});console.log("here",b);if(b)d(a,b.subloops);else{for(b=c.length;0<=--b;){var e=c[b];f.edgeLoopContainsPoint(a.edges,e.edges[0].a)&&(a.subloops.push(e),c.splice(b,1))}c.push(a)}}}function e(b){var d=new c.constructor(c.surface,b.edges,b.subloops.map(function(a){return a.edges}));b.subloops.forEach(function(a){return a.subloops.forEach(function(a){return e(a)})});console.log(d.toString(),d.holes.toString());a.push(d)}var f=c.surface;console.log(b.map(function(a){return a.join("\n")}).join("\n\n"));
var g=[];b.forEach(function(a){var c=f.edgeLoopCCW(a);console.log("CCW",c);d({edges:a,ccw:c,subloops:[]},g);console.log(g)});if(g[0].ccw)return g.forEach(function(a){return e(a)}),!1;e({edges:c.edges,ccw:!0,subloops:g});return!0},reconstituteFaces:function(a,b,c,d){var e=this,f=[];for(a.forEach(function(a){var g=Array.prototype.concat.apply(a.edges,a.holes);console.log("reconstituting face",a.toString());var p=a.edges.map(function(a){return b.get(a)&&b.get(a).join("\n")}).map(function(a){return"\n\n"+
a}).join();console.log("edgeLooseSegments",p);if(p=c.get(a)){a.insideOutside="part";console.log("looseEdges\n",p.map(function(a){return a.toString()}).join("\n"));for(var m=[],l,t=a instanceof B2.PlaneFace?function(a){return a.a.like(l.b)}:function(a){return a.curve==l.curve?NLA.equals(a.aT,l.bT):a.a.like(l.b)};l=p.find(function(a){return!a.visited});){l.visited=!0;var n=l,q=[],u=0;do{console.log("currentEdge",l.b.ss,l.toSource());q.push(l);var v=p.filter(function(a){return t(a)}),x,y=v.length;g.forEach(function(a){return(x=
b.get(a))&&x.forEach(function(a){return t(a)&&v.push(a)})});var r=!1;y==v.length&&(g.forEach(function(a){return t(a)&&v.push(a)}),r=!0);var w=v.indexWithMax(function(c,b){return-l.bDir.angleRelativeNormal(c.aDir,a.surface.normalAt(l.b))+(b<y?NLA.PRECISION:0)});l=v[w];w<y?v.forEach(function(a){return a.isCoEdge(l)&&(a.visited=!0)}):r&&f.push(l);assert(l)}while(10>++u&&l!=n);10==u&&assert(!1,"too many");console.log("finished loop");m.push(q)}e.assembleFacesFromLoops(d,m,a)&&f.pushAll(a.edges)}else a.insideOutside=
"undecided"});0!=f.length;){var g=f.pop();facesWithEdge(g,a).forEach(function(a){"undecided"==a.face.insideOutside&&(a.face.insideOutside="inside",f.push.apply(f,a.face.edges))})}a.forEach(function(a){"inside"==a.insideOutside&&d.push(a)})},getLooseEdgeSegments:function(a){var b=new Map;a.forEach(function(a,d){var e=[];d.reversed?a.sort(function(a,c){return c.edgeT-a.edgeT}):a.sort(function(a,c){return a.edgeT-c.edgeT});for(var f=d.a,g=d.aDir,h=d.aT,k=0;k<a.length;k++){var p=a[k];assert(p.insideDir);
if(!(NLA.equals(p.edgeT,d.bT)||NLA.equals(p.edgeT,d.aT)||NLA.equals(p.edgeT,h))){var m=d.tangentAt(p.edgeT);e.push(new d.constructor(d.curve,f,p.p,h,p.edgeT,null,g,m));f=p.p;h=p.edgeT;g=m}}e.push(new d.constructor(d.curve,f,d.b,h,d.bT,null,g,d.bDir));d.b.like(V3(0,4,1))&&(console.log("pointInfos",d.reversed,d.ss,a.map(function(a){return"\n"+a.toSource()}).join()),console.log(e));b.set(d,e)});return b},intersection:function(a,b,c,d,e){var f=this,g=new Map,h=new Map;this.faces.forEach(function(c){a.faces.forEach(function(b){c.doo(b,
f,a,g,h,d,e)})});var k=[],p=this.getLooseEdgeSegments(h);b&&this.reconstituteFaces(this.faces,p,g,k,a.infiniteVolume);c&&this.reconstituteFaces(a.faces,p,g,k,this.infiniteVolume);return new B2(k,this.infiniteVolume&&a.infiniteVolume)},transform:function(a){return new B2(this.faces.map(function(b){return b.transform(a)}),this.infiniteVolume)},flipped:function(){return new B2(this.faces.map(function(a){return a.flipped()}),!this.infiniteVolume)}});
B2.Face=function(a,b,c){var d=this;this.assertChain(b);assert(b.every(function(a){return a instanceof B2.Edge}),"contour.every(f => f instanceof B2.Edge)"+b.toSource());b.forEach(function(c){return assert(a.containsCurve(c.curve),c)});c&&c.forEach(function(a){return d.assertChain(a)});assert(!c||c.constructor==Array,c&&c.toString());this.surface=a;this.edges=b;this.holes=c||[];this.id=globalId++};
B2.Face.prototype=NLA.defineObject(NLA.Transformable.prototype,{transform:function(a){var b=this.edges.map(function(c){return c.transform(a)}),c=this.holes.map(function(c){return c.map(function(c){return c.transform(a)})});return new this.constructor(this.surface.transform(a),b,c)},assertChain:function(a){a.forEach(function(b,c){var d=(c+1)%a.length;assert(b.b.like(a[d].a),"edges["+c+"].b != edges["+d+"].a ("+a[c].b.ss+" != "+a[d].a.ss+")")})},flipped:function(){var a=this.edges.map(function(a){return a.flipped()}).reverse(),
b=this.holes.map(function(a){return a.map(function(a){return a.flipped()}).reverse()});return new this.constructor(this.surface.flipped(),a,b)},toString:function(){return"new "+this.name+"("+this.surface+", ["+this.edges.map(function(a){return"\n\t"+a}).join()+"]"+(this.holes.map(function(a){return"\n\t\thole: "+a.join()})+")")},toSource:function(){return"new "+this.name+"("+this.surface.toSource()+", ["+this.edges.map(function(a){return"\n\t"+a.toSource()}).join(",")+"])"},equals:function(a){var b=
this;assert(!1);var c=this.edges.length;return this.surface.equalsSurface(a.surface)&&this.edges.length==a.edges.length&&NLA.arrayRange(0,c,1).some(function(d){return b.edges.every(function(b,f){return b.equals(a.edges[(d+f)%c])})})},likeFace:function(a){function b(a,b){return a.length==b.length&&NLA.arrayRange(0,a.length,1).some(function(e){return a.every(function(f,g){return f.likeEdge(b[(e+g)%a.length])})})}assertInst(B2.Face,a);return this.surface.equalsSurface(a.surface)&&this.holes.length==
a.holes.length&&b(this.edges,a.edges)&&this.holes.every(function(c){return a.holes.some(function(a){return b(c,a)})})},addEdgeLines:function(a){assert(!1,"buggy, fix");for(var b=this.edges.map(function(a){return a.getVerticesNo0()}).concatenated(),c=a.vertices.length,d=0;d<b.length;d++)a.vertices.push(b[d]),a.lines.push(c+d,c+(d+1)%b.length)},inB2:function(){return new B2([this])}});B2.Edge=function(){};
B2.Edge.prototype=NLA.defineObject(null,{toString:function(a){return"new "+this.name+"("+this.curve.toString(a)+", "+this.a+", "+this.b+", "+this.aT+", "+this.bT+", null, "+this.aDir+", "+this.bDir+")"},getIntersectionsWithPlane:function(a){assert(!1,this.name+".getIntersectionsWithPlane")}});
B2.PlaneFace=NLA.degineClagg("B2.PlaneFace",B2.Face,function(a,b,c,d){B2.Face.call(this,a,b,c,d);assert(a instanceof PlaneSurface)},{addToMesh:function(a){var b=a.vertices.length,c=this.surface.plane.normal,d=this.edges.map(function(a){return a.getVerticesNo0()}).concatenated();console.log(d.map(V3.ss).join());for(var e=0;e<d.length;e++)a.lines.push(b+e,b+(e+1)%d.length);var f=[];this.holes.forEach(function(a){f.push(d.length);d.pushAll(a.map(function(a){return a.getVerticesNo0()}).concatenated())});
e=triangulateVertices(c,d,f).map(function(a){return a+b});Array.prototype.push.apply(a.vertices,d);Array.prototype.push.apply(a.triangles,e);Array.prototype.push.apply(a.normals,NLA.arrayFromFunction(d.length,function(a){return c}))},containsPoint:function(a){assertVectors(a);return this.surface.edgeLoopContainsPoint(this.edges,a)},withHole:function(a){return new B2.PlaneFace(this.surface,this.edges,[a])},doo:function(a,b,c,d,e,f,g){if(a instanceof B2.RotationFace){var h=this;if(!this.surface.isCoplanarTo(a.surface)&&
(f=a.surface.getIntersectionsWithSurface(this.surface),console.log(f),0!=f.length)){var k=getFacePlaneIntersectionSs2(b,this,f,a.surface,!0,!1),p=getFacePlaneIntersectionSs2(c,a,f,this.surface,!1,!1);f.forEach(function(c,b){var f=k[b],g=p[b];if(0!=f.length&&0!=g.length){var q=0!=f.length?f[0]:g[0],u=!(0<a.surface.normalAt(q.p).cross(h.surface.normalAt(q.p)).dot(c.tangentAt(q.t))),q=0>f[0].insideDir.dot(c.tangentAt(f[0].t)),v=0>g[0].insideDir.dot(c.tangentAt(g[0].t));c.debugToMesh&&(dMesh=new GL.Mesh,
c.debugToMesh(dMesh,"curve2"),dMesh.compile(),console.log(dMesh));console.log("iscurve",c.toString(),c.tangentAt(f[0].t).ss);console.log("ps1\n",f.map(function(a){return a.toSource()}).join("\n"),"\nps2\n",g.map(function(a){return a.toSource()}).join("\n"));q=c instanceof L3?getBlug(f,g,c):getIntersectionSegments(f,g,q,v,B2.PCurveEdge,c);console.log("segments",q.toSource());f.forEach(function(a){return a.used&&mapAdd(e,a.edge,a)});g.forEach(function(a){return a.used&&mapAdd(e,a.edge,a)});q.forEach(function(c){console.log("segment",
c.toString());mapAdd(d,h,u?c:c.flipped());mapAdd(d,a,u?c.flipped():c)})}});console.log("faceMap",d)}}else a instanceof B2.PlaneFace&&this.dooPlaneFace(a,b,c,d,e,f,g)},dooPlaneFace:function(a,b,c,d,e,f,g){function h(f,g,h,k,n,t,q){console.log("handling",g&&g.toSource(),h&&h.toSource(),f.toSource());g||h||(console.log("adding"),NLA.mapAdd(d,p,f),NLA.mapAdd(d,a,f.flipped()));!g&&h&&(console.log("!col1 && col2"),0<h.aDir.cross(l.normal).dot(m.normal)&&(NLA.mapAdd(d,a,f.flipped()),NLA.mapAdd(e,h,{edgeT:h.curve.pointLambda(f.a),
p:f.a}),NLA.mapAdd(e,h,{edgeT:h.curve.pointLambda(f.b),p:f.b}),k=l.normal.negated().rejectedFrom(m.normal),console.log("testVector",k.ss,c.ss,splitsVolumeEnclosingFaces(c,h,k,m.normal)==INSIDE),splitsVolumeEnclosingFaces(c,h,k,m.normal)==INSIDE&&NLA.mapAdd(d,p,f)));!h&&g&&0<g.aDir.cross(m.normal).dot(l.normal)&&(NLA.mapAdd(d,p,f),NLA.mapAdd(e,g,{edgeT:g.curve.pointLambda(f.a),p:f.a}),NLA.mapAdd(e,g,{edgeT:g.curve.pointLambda(f.b),p:f.b}),k=m.normal.negated().rejectedFrom(l.normal),splitsVolumeEnclosingFaces(b,
g,k,l.normal)==INSIDE&&NLA.mapAdd(d,a,f.flipped()));g&&h&&(k=g.aDir.cross(m.normal).negated(),console.log("testVector",k.ss,c.ss,splitsVolumeEnclosingFaces(c,h,k,m.normal)==INSIDE),splitsVolumeEnclosingFaces(c,h,k,m.normal)==INSIDE&&(NLA.mapAdd(d,p,f),NLA.mapAdd(e,g,{edgeT:g.curve.pointLambda(f.a),p:f.a}),NLA.mapAdd(e,g,{edgeT:g.curve.pointLambda(f.b),p:f.b})),k=h.aDir.cross(l.normal).negated(),splitsVolumeEnclosingFaces(b,g,k,l.normal)==INSIDE&&(NLA.mapAdd(d,a,f.flipped()),NLA.mapAdd(e,h,{edgeT:h.curve.pointLambda(f.a),
p:f.a}),NLA.mapAdd(e,h,{edgeT:h.curve.pointLambda(f.b),p:f.b})))}function k(a,d,f,g){console.log("logging point",f,a.toSource());console.log("logging point",g,d.toSource());f&&!g&&(a.colinear||NLA.mapAdd(e,a.edge,a));g&&!f&&(d.colinear||NLA.mapAdd(e,d.edge,d));f&&g&&(a.colinear||INSIDE==splitsVolumeEnclosingFaces(c,d.edge,a.edge.aDir,m.normal)!=(INSIDE==splitsVolumeEnclosingFaces(c,d.edge,a.edge.aDir.negated(),m.normal))&&NLA.mapAdd(e,a.edge,a),d.colinear||INSIDE==splitsVolumeEnclosingFaces(b,a.edge,
d.edge.aDir,l.normal)!=(INSIDE==splitsVolumeEnclosingFaces(b,a.edge,d.edge.aDir.negated(),l.normal))&&NLA.mapAdd(e,d.edge,d))}assert(a instanceof B2.PlaneFace);var p=this,m=this.surface.plane,l=a.surface.plane;if(!m.isParallelToPlane(l)){f=L3.fromPlanes(m,l);g=getFacePlaneIntersectionSs(b,this,f,l,!0,!1);var t=getFacePlaneIntersectionSs(c,a,f,m,!1,!1);console.log("ps1\n",g.map(function(a){return a.toSource()}).join("\n"),"\nps2\n",t.map(function(a){return a.toSource()}).join("\n"));if(0!=g.length&&
0!=t.length){console.log(""+m+l);for(var n=!1,q=!1,u=!1,v=!1,x=0,y=0,r,w,z,C;x<g.length||y<t.length;){var A=g[x],B=t[y];y>=t.length||x<g.length&&NLA.lt(A.t,B.t)?(r=A,u=(n=!n)&&A.colinear&&A.edge||u,x++):(x>=g.length||NLA.gt(A.t,B.t)?(r=B,v=(q=!q)&&B.colinear&&B.edge||v):(r=A,n=!n,q=!q,A.used=!0,B.used=!0,u=n&&A.colinear&&A.edge||u,v=q&&B.colinear&&B.edge||v,x++),y++);!w||n&&q?n&&q&&(w=r.p,z=r.insideDir,C=r.t,r.used=!0,k(A,B,u||!!A.used,v||!!B.used)):(h(new StraightEdge(f,w,r.p,C,r.t,null,z,r.insideDir&&
r.insideDir.negated()),u,v,n,q,A,B),w=void 0,r.used=!0,k(A,B,u||!!A.used,v||!!B.used))}}}}});
B2.PlaneFace.forVertices=function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];console.log(b,d);a instanceof P3&&(a=new PlaneSurface(a));assert(isCCW(b,a.plane.normal),"isCCW(vs, planeSurface.plane.normal)");e=b.map(function(a,c,b){return StraightEdge.throughPoints(a,b[(c+1)%b.length])});d.forEach(function(c){return assert(0<=doubleSignedArea(c,a.plane.normal),"doubleSignedArea(vs, planeSurface.plane.normal) >= 0")});d=d.map(function(a){return a.map(function(a,c,b){return StraightEdge.throughPoints(a,
b[(c+1)%b.length])})});return new B2.PlaneFace(a,e,d)};function facesWithEdge(a,b){return arrayFilterMap(b,function(c){var b=c.edges.find(function(c){return c.isCoEdge(a)});if(b)return{face:c,reversed:!a.a.like(b.a),angle:NaN,normalAtEdgeA:null,edge:b}})}
function getFacePlaneIntersectionSs(a,b,c,d){var e=b.surface.plane,f=[];b.holes.concat([b.edges]).forEach(function(a){var b=a.map(function(a){return a.colinearToLine(c)}),k=c.dir1.cross(e.normal);a.forEach(function(a,g,l){var t=(g+1)%l.length,n=l[t];if(b[g])t=l[(g+l.length-1)%l.length],g=a.aDir.cross(e.normal),0>t.bDir.dot(g)&&f.push({p:t.b,insideDir:null,t:c.pointLambda(t.b),edge:t,edgeT:t.bT,colinear:!1}),f.push({p:a.a,insideDir:a.aDir,t:c.pointLambda(a.a),edge:a,edgeT:a.aT,colinear:!0},{p:a.b,
insideDir:a.bDir.negated(),t:c.pointLambda(a.b),edge:a,edgeT:a.bT,colinear:!0}),0<n.aDir.dot(g)&&f.push({p:a.b,insideDir:null,t:c.pointLambda(a.b),edge:a,edgeT:t.bT,colinear:!1});else for(g=a.getIntersectionsWithPlane(d),l=0;l<g.length;l++){var q=g[l];if(q==a.bT)console.log("endpoint lies on intersection line",k.dot(a.bDir),k.dot(n.aDir),k.dot(a.bDir)*k.dot(n.aDir),k.ss,a.bDir.ss,n.aDir.ss),!b[t]&&0<k.dot(a.bDir)*k.dot(n.aDir)&&(console.log("adding"),f.push({p:a.b,insideDir:null,t:c.pointLambda(a.b),
edge:a,edgeT:a.bT,caseA:!0,caseB:!0}));else if(q!=a.aT){var u=a.curve.at(q);assert(c.containsPoint(u),a.toString()+u+q);f.push({p:u,insideDir:null,t:c.pointLambda(u),edge:a,edgeT:q,colinear:!1});console.log("middle")}}})});f.sort(function(a,c){return a.t-c.t||assert(!1)});return f}
function getFacePlaneIntersectionSs2(a,b,c,d,e,f){var g=b.surface,h=b.edges.map(function(a){return!1}),k=NLA.arrayFromFunction(c.length,function(a){return[]});b.edges.forEach(function(a,b,e){var f=(b+1)%e.length;e=e[f];if(h[b]){assert(!1);var f=0<a.bDir.cross(g.normal).dot(e.aDir),n=f!=colinearSegmentsInsideCaseTrue[b],q=f!=colinearSegmentsInsideCaseFalse[b],u=a.aDir.cross(g.normal),u=0<u.dot(d.normalAt(a.b));(n||q||u!=f)&&ps.push({p:a.b,insideDir:null,t:r.pointLambda(a.b),edge:a,edgeT:a.bT,caseA:n,
caseB:q,colinear:!0,hideOnFace:u==f})}else{b=a.getIntersectionsWithSurface(d);for(var v=0;v<b.length;v++)if(n=b[v],n==a.bT){assert(!1);console.log("endpoint lies on intersection isCurve",x.dot(a.bDir),x.dot(e.aDir),x.dot(a.bDir)*x.dot(e.aDir),x.ss,a.bDir.ss,e.aDir.ss);var x=curve.tangentAt(a.b).cross(g.normalAt(a.b));if(h[f]){var u=e.aDir.cross(g.normal),y=0>u.dot(a.bDir),n=y!=colinearSegmentsInsideCaseTrue[f],q=y!=colinearSegmentsInsideCaseFalse[f],u=0<u.dot(d.normalAt(a.a));(n||q||u!=y)&&ps.push({p:a.b,
insideDir:null,t:r.pointLambda(a.b),edge:a,edgeT:a.bT,caseA:n,caseB:q,colinear:!0,hideOnFace:u==y})}else 0<x.dot(a.bDir)*x.dot(e.aDir)&&ps.push({p:a.b,insideDir:null,t:r.pointLambda(a.b),edge:a,edgeT:a.bT,caseA:!0,caseB:!0})}else if(n!=a.aT){for(var q=c.length,r,u=a.curve.at(n);0<=--q&&!(r=c[q]).containsPoint(u););console.log("edgeT",n,"p",u.ss,a,q);0>q&&assert(!1,u.ss);assert(r.containsPoint(u));var y=a.tangentAt(n).cross(g.normalAt(u)),w=r.pointLambda(u,y),z=r.tangentAt(w);0<y.dot(z)&&(z=z.negated());
k[q].push({p:u,insideDir:z,t:w,edge:a,edgeT:n,caseA:!0,caseB:!0});console.log("middle")}}});k.forEach(function(a){return a.sort(function(a,c){return a.t-c.t||assert(!1,a.t+" "+c.t+" "+a.p.ss)})});return k}var INSIDE=0,OUTSIDE=1,COPLANAR_SAME=2,COPLANAR_OPPOSITE=3;
function splitsVolumeEnclosingFaces(a,b,c,d,e,f){var g=b.aDir.normalized();a=facesWithEdge(b,a.faces);a.forEach(function(a){a.normalAtEdgeA=a.face.surface.normalAt(b.a);a.edgeDirAtEdgeA=a.reversed?a.edge.bDir:a.edge.aDir;a.outsideVector=a.edgeDirAtEdgeA.cross(a.normalAtEdgeA);a.angle=(c.angleRelativeNormal(a.outsideVector.negated(),g)+2*Math.PI+NLA.PRECISION/2)%(2*Math.PI)});a.sort(function(a,c){return a.angle-c.angle});assert(0!=a.length);console.log(a.map(function(a){return a.toSource()}).join("\n"));
return NLA.isZero(a[0].angle)?0<a[0].normalAtEdgeA.dot(d)?COPLANAR_SAME:INSIDE:a[0].reversed?OUTSIDE:INSIDE}B2.RotationFace=function(a,b,c,d){B2.Face.call(this,a,b,c,d)};
B2.RotationFace.prototype=NLA.defineObject(B2.Face.prototype,{constructor:B2.RotationFace,name:"B2.RotationFace",unrollLoop:function(a){var b=this,c=[];a.forEach(function(a,e){var f=b.surface.pointToParameterFunction(),g=a.bDir;a instanceof StraightEdge&&a.curve.dir1.isParallelTo(b.surface.dir)&&(g=b.surface.baseEllipse.f1.times(b.surface.normalDir).cross(a.bDir));a.getVerticesNo0().forEach(function(a){return c.push(f(a,g))});console.log(a.ss,"\n",a.getVerticesNo0().map(function(a){return f(a,g)}).join())});
return c},addToMesh:function(a){var b=this;console.log("mlsadkl");var c=[],d=Infinity,e=-Infinity,f=this.surface.parametricFunction(),g=this.surface.parametricNormal(),h=this.holes.concat([this.edges]).map(function(a){return b.unrollLoop(a)});h.forEach(function(a){a.forEach(function(a){var b=a.x;a=a.y;var f=c.binaryIndexOf(b,function(a,c){return NLA.snapTo(a.value-c,0)});0>f&&c.splice(-f-1,0,{value:b,left:[],right:[]});d=min(d,a);e=max(e,a)})});h.forEach(function(a){a.forEach(function(a,b,d){d=d[(b+
1)%d.length];b=d.x-a.x;console.log(a.ss,d.ss);if(!NLA.isZero(b)){0>b&&(d=$jscomp.makeIterator([d,a]),a=d.next().value,d=d.next().value,b=-b);var e=c.binaryIndexOf(a.x,function(a,c){return NLA.snapTo(a.value-c,0)}),f=c.binaryIndexOf(d.x,function(a,c){return NLA.snapTo(a.value-c,0)});c[e].right.binaryInsert(a.y);for(e=(e+1)%c.length;e!=f;e=(e+1)%c.length){var g=(c[e].value-a.x)/b,g=d.y*g+a.y*(1-g);c[e].left.binaryInsert(g);c[e].right.binaryInsert(g)}c[f].left.binaryInsert(d.y);console.log(c.map(function(a){return a.toSource()}).join("\n"))}})});
for(var h=[],k=[],p=[],m=0;m<c.length;m++){var l=c[m],t=c[(m+1)%c.length];assert(l.right.length==t.left.length);for(var n=0;n<l.right.length;n++)h.push(f(l.value,l.right[n]),f(t.value,t.left[n])),p.push(g(l.value,l.right[n]),g(t.value,t.left[n]))}console.log(c.map(function(a){return a.toSource()}).join("\n"));for(var m=h.length,q=(e-d)/1,n=NLA.arrayFromFunction(0,function(a){return d+(1+a)*q}),l=0;l<c.length;l++)for(var t=c[l].value,u=0;u<n.length;u++)h.push(f(t,n[u])),p.push(g(t,n[u]));for(var f=
0,g=1==this.surface.normalDir,u=c.length-1,v=0;v<u;v++){for(var x=(v+1)%c.length,y=!1,r=0,l=c[v],t=c[(v+1)%c.length],w=0;w<n.length+1;w++){var z=n[w]||1E5;y?l.right[r]<z||t.left[r]<z?(pushQuad(k,g,m+v*n.length+w-1,m+x*n.length+w-1,f+2*r,f+2*r+1),y=!1,r++,(l.right[r]<z||t.left[r]<z)&&w--):pushQuad(k,g,m+v*n.length+w,m+v*n.length+w-1,m+x*n.length+w,m+x*n.length+w-1):l.right[r]<z&&t.left[r]<z&&(l.right[r+1]<z||t.left[r+1]<z?(pushQuad(k,g,f+2*r,f+2*(r+1),f+2*r+1,f+2*(r+1)+1),r+=2,(l.right[r]<z||t.left[r]<
z)&&w--):(pushQuad(k,g,f+2*r,f+2*r+1,m+v*n.length+w,m+x*n.length+w),y=!0,r++))}f+=2*l.right.length}k=k.map(function(c){return c+a.vertices.length});Array.prototype.push.apply(a.vertices,h);Array.prototype.push.apply(a.triangles,k);Array.prototype.push.apply(a.normals,p)},doo:function(a){a.surface instanceof PlaneSurface?a.doo.apply(a,[this].concat(Array.from(arguments).slice(1))):B2.PlaneFace.prototype.doo.apply(this,arguments)}});
function pushQuad(a,b,c,d,e,f){b?a.push(c,e,d,d,e,f):a.push(c,d,e,d,f,e)}
B2.PCurveEdge=NLA.degineClagg("B2.PCurveEdge",B2.Edge,function(a,b,c,d,e,f,g,h){assertNumbers(d,e);assertVectors(b,c,g,h);assert(a instanceof L3||a instanceof EllipseCurve,a);assert(!a.isValidT||a.isValidT(d)&&a.isValidT(e),d+" "+e);assert(a.at(d).like(b));assert(a.at(e).like(c));this.curve=a;this.a=b;this.b=c;this.aT=d;this.bT=e;this.aDir=g;this.bDir=h;this.canon=f;this.reversed=0>this.aDir.dot(a.tangentAt(d));assert(this.reversed!=d<e,d+" "+e);this.id=globalId++},{getVerticesNo0:function(){return this.curve.calcSegmentPoints(this.aT,
this.bT,this.a,this.b,this.reversed,!1)},get points(){return this.curve.calcSegmentPoints(this.aT,this.bT,this.a,this.b,this.reversed,!0)},rotViaPlane:function(a,b){var c=this.aDir.angleRelativeNormal(this.bDir,a);0<a.dot(this.curve.normal)==!this.reversed?0>c&&(c+=2*PI):0<c&&(c-=2*PI);return c},getIntersectionsWithISurface:function(a){var b=this;assert(a.implicitFunction);var c=min(this.aT,this.bT),d=max(this.aT,this.bT);return intersectionPCurveISurface(function(a){return b.curve.at(a)},c,d,.1,
a.implicitFunction())},getIntersectionsWithSurface:function(a){var b=this;return this.curve.getIntersectionsWithSurface(a).filter(function(a){var d=b.aT,e=b.bT;a=NLA.snapTo(a,d);a=NLA.snapTo(a,e);return b.reversed?d>e?d>=a&&a>=e:!(e>a&&a>d):d<e?d<=a&&a<=e:!(e<a&&a<d)})},getIntersectionsWithPlane:function(a){var b=this;console.log(this.curve,this.curve.constructor.name);return this.curve.getIntersectionsWithPlane(a).filter(function(a){var d=b.aT,e=b.bT;a=NLA.snapTo(a,d);a=NLA.snapTo(a,e);return b.reversed?
d>e?d>=a&&a>=e:!(e>a&&a>d):d<e?d<=a&&a<=e:!(e<a&&a<d)})},tangentAt:function(a){return this.reversed?this.curve.tangentAt(a).negated():this.curve.tangentAt(a)},flipped:function(){return new B2.PCurveEdge(this.curve,this.b,this.a,this.bT,this.aT,this,this.bDir.negated(),this.aDir.negated())},transform:function(a){return new B2.PCurveEdge(this.curve.transform(a),a.transformPoint(this.a),a.transformPoint(this.b),this.aT,this.bT,null,a.transformVector(this.aDir),a.transformVector(this.bDir))},colinearToLine:function(a){return this.curve.equals(a)},
isCoEdge:function(a){return this==a||this.curve.isColinearTo(a.curve)&&(this.a.like(a.a)&&this.b.like(a.b)||this.a.like(a.b)&&this.b.like(a.a))},likeEdge:function(a){return a.constructor==StraightEdge&&this.a.like(a.a)&&this.b.like(a.b)}});
var StraightEdge=NLA.degineClagg("StraightEdge",B2.Edge,function(a,b,c,d,e,f){assertNumbers(d,e);assertVectors(b,c);assert(a instanceof L3);assert(a.containsPoint(b),"line.containsPoint(a)"+a+b);assert(a.containsPoint(c),"line.containsPoint(b)"+a+c);this.curve=a;this.a=b||a.at(d);this.b=c||a.at(e);this.aT=d;this.bT=e;this.reversed=this.aT>this.bT;this.canon=f;this.tangent=this.aT<this.bT?this.curve.dir1:this.curve.dir1.negated();this.id=globalId++},{toSource:function(){return"StraightEdge.throughPoints("+
this.a+", "+this.b+")"},getVerticesNo0:function(){return[this.b]},get points(){return[this.a,this.b]},getIntersectionsWithISurface:function(a){var b=this;assert(a.implicitFunction);var c=min(this.aT,this.bT),d=max(this.aT,this.bT);return intersectionPCurveISurface(function(a){return b.curve.at(a)},c,d,.1,a.implicitFunction())},getIntersectionsWithPlane:function(a){var b=min(this.aT,this.bT),c=max(this.aT,this.bT);a=this.curve.intersectWithPlaneLambda(a);a=NLA.snapTo(a,this.aT);a=NLA.snapTo(a,this.bT);
return b<=a&&a<=c?[a]:[]},getIntersectionsWithSurface:function(a){if(a instanceof PlaneSurface)return this.getIntersectionsWithPlane(a.plane);if(a instanceof CylinderSurface){var b=this,c=min(this.aT,this.bT),d=max(this.aT,this.bT);return a.intersectionWithLine(this.curve).map(function(a){return b.curve.pointLambda(a)}).filter(function(a){return c<=a&&a<=d})}assert(!1)},tangentAt:function(a){return this.tangent},flipped:function(){return new StraightEdge(this.curve,this.b,this.a,this.bT,this.aT,this)},
get aDir(){return this.tangent},get bDir(){return this.tangent},set aDir(a){},set bDir(a){},transform:function(a){return new StraightEdge(this.curve.transform(a),a.transformPoint(this.a),a.transformPoint(this.b),this.aT,this.bT)},colinearToLine:function(a){return this.curve.equals(a)},isCoEdge:function(a){return a.constructor==StraightEdge&&(this.a.like(a.a)&&this.b.like(a.b)||this.a.like(a.b)&&this.b.like(a.a))},likeEdge:function(a){return a.constructor==StraightEdge&&this.a.like(a.a)&&this.b.like(a.b)},
equals:function(a){return a.constructor==StraightEdge&&this.a.equals(a.a)&&this.b.equals(a.b)},getEdgeT:function(a){assertVectors(a);var b=a.minus(this.curve.anchor).dot(this.curve.dir1);if(NLA.isZero(this.curve.at(b).distanceTo(a))){a=min(this.aT,this.bT);var c=max(this.aT,this.bT),b=NLA.snapTo(b,this.aT),b=NLA.snapTo(b,this.bT);return a<=b&&b<=c?b:void 0}}});StraightEdge.throughPoints=function(a,b){return new StraightEdge(L3.throughPoints(a,b),a,b,0,b.minus(a).length())};
function intersectionUnitCircleLine(a,b,c){assertNumbers(a,b,c);var d=sqrt(a*a+b*b-c*c);return{x1:(a*c+b*d)/(a*a+b*b),x2:(a*c-b*d)/(a*a+b*b),y1:(b*c-a*d)/(a*a+b*b),y2:(b*c+a*d)/(a*a+b*b)}}function intersectionUnitHyperbolaLine(a,b,c){assertNumbers(a,b,c);var d=a*a,e=b*b,f=c*c,g=sqrt(4*f*d-4*(e-d)*(-f-e)),g=2*sqrt(e*f+e*e-d*e),f=sqrt(4*f*e-4*(e-d)*(f-d));return{x1:(-2*a*c+g)/2/(e-d),x2:(-2*a*c-g)/2/(e-d),y1:(2*b*c-f)/2/(e-d),y2:(2*b*c+f)/2/(e-d)}}
function intersectionCircleLine(a,b,c,d){assertNumbers(a,b,c,d);d=sqrt(d*d*(a*a+b*b)-c*c);return{x1:(a*c+b*d)/(a*a+b*b),x2:(a*c-b*d)/(a*a+b*b),y1:(b*c-a*d)/(a*a+b*b),y2:(b*c+a*d)/(a*a+b*b)}}function pqEquation(a,b){var c=a*a/4-b;if(c<-NLA.PRECISION)return[];if(c<=NLA.PRECISION)return[-a/2];c=Math.sqrt(c);return[-a/2-c,-a/2+c]}function integrateCurve(a,b,c,d){c=(c-b)/d;var e=0,f=a.at(b),g=0;for(b+=c;g<d;g++,b+=c)var h=a.at(b),e=e+f.distanceTo(h),f=h;return e}
function getIntersectionSegments(a,b,c,d,e,f){assert(!(c&&d),"!(in1 && in2) "+c+" "+d);console.log("in",c,d);for(var g=0,h=0,k,p=[],m,l,t;g<a.length||h<b.length;){var n=a[g],q=b[h];h>=b.length||g<a.length&&NLA.lt(n.t,q.t)?(k=n,c=!c,g++):(g>=a.length||NLA.gt(n.t,q.t)?(k=q,d=!d):(k=n,c=!c,d=!d,c==d&&(n.used=!0,q.used=!0),g++),h++);!m||c&&d?c&&d&&(m=k.p,l=k.insideDir,t=k.t,k.used=!0):(p.push(new e(f,m,k.p,t,k.t,null,l,k.insideDir.negated())),m=void 0,k.used=!0)}assert(!(c&&d),"!(in1 && in2) "+c+" "+
d);return p}function getBlug(a,b,c){for(var d=!1,e=!1,f=0,g=0,h,k=[],p,m,l;f<a.length||g<b.length;){var t=a[f],n=b[g];g>=b.length||f<a.length&&NLA.lt(t.t,n.t)?(h=t,d=!d,f++):(f>=a.length||NLA.gt(t.t,n.t)?(h=n,e=!e):(h=t,d=!d,e=!e,t.used=!0,n.used=!0,f++),g++);!p||d&&e?d&&e&&(p=h.p,m=h.insideDir,l=h.t,h.used=!0):(k.push(new StraightEdge(c,p,h.p,l,h.t,null,m,h.insideDir&&h.insideDir.negated())),p=void 0,h.used=!0)}assert(!d&&!e,"!in1 && !in2 "+d+" "+e);return k}
function PlaneSurface(a,b,c){assert(a instanceof P3);this.plane=a;this.up=c||a.normal.getPerpendicular().normalized();this.right=b||this.up.cross(this.plane.normal).normalized();assert(this.right.cross(this.up).like(this.plane.normal))}PlaneSurface.throughPoints=function(a,b,c){return new PlaneSurface(P3.throughPoints(a,b,c))};
PlaneSurface.prototype=NLA.defineObject(null,{isCoplanarTo:function(a){return a instanceof PlaneSurface&&this.plane.isCoplanarToPlane(a.plane)},parametricFunction:function(){var a=M4.forSys(this.right,this.up,this.normal,this.plane.anchor);return function(b,c){return a.transformPoint(V3.create(b,c,0))}},implicitFunction:function(){var a=this;return function(b){return a.plane.distanceToPointSigned(b)}},intersectionCurveWithImplicitSurface:function(a){assert(a.implicitFunction,"implicitSurface.implicitFunction");
return new CurvePI(this,a)},getIntersectionCurve:function(a){if(a.implicitFunction)return new CurvePI(this,a);if(a.parametricFunction)return new CurvePI(a,this)},edgeLoopCCW:function(a){for(var b=0,c=0;c<a.length;c++){var d=a[c],e=a[(c+1)%a.length];d.curve instanceof EllipseCurve&&(b+=d.rotViaPlane(this.plane.normal),console.log(d.toString(),d.rotViaPlane(this.plane.normal)));b+=d.bDir.angleRelativeNormal(e.aDir,this.plane.normal)}return 0<b},edgeLoopContainsPoint:function(a,b){function c(a){0<e.pointLambda(a)&&
(m=!m)}assertVectors(b);var d=this.right,e=L3(b,d),f=this.plane,g=d.cross(f.normal),h=P3.normalOnAnchor(g,b),k=a.map(function(a){return a.colinearToLine(e)}),p=a.map(function(a,b){return 0<a.aDir.dot(d)}),m=!1;a.forEach(function(a,b,d){var e=(b+1)%d.length;d=d[e];if(k[b])e=0<a.bDir.cross(f.normal).dot(d.aDir),p[b]!=e&&c(a.b);else{b=a.getIntersectionsWithPlane(h);for(var m=0;m<b.length;m++){var v=b[m];v==a.bT?k[e]?(v=0>d.aDir.cross(f.normal).dot(a.bDir),p[e]!=v&&c(a.b)):0<g.dot(a.bDir)*g.dot(d.aDir)&&
c(a.b):v!=a.aT&&c(a.curve.at(v))}}});return m},pointToParameterFunction:function(a){var b=M4.forSys(this.right,this.up,this.normal,this.plane.anchor).inversed();return function(a){return b.transformPoint(a)}},normalAt:function(a){return this.plane.normal},containsPoint:function(a){return this.plane.containsPoint(a)},containsCurve:function(a){if(a instanceof L3)return this.plane.containsLine(a);if(a instanceof EllipseCurve)return this.plane.containsPoint(a.center)&&this.plane.normal.isParallelTo(a.normal);
assert(!1,edge.toString())},transform:function(a){return new PlaneSurface(this.plane.transform(a))},flipped:function(){return new PlaneSurface(this.plane.flipped(),this.right,this.up.negated())},toString:function(){return this.plane.toString()},toSource:function(){return"new PlaneSurface("+this.plane+")"},equalsSurface:function(a){return a instanceof PlaneSurface&&this.plane.like(a.plane)}});
function curvePoint(a,b){for(var c=b,d=0;4>d;d++)var e=a(c.x,c.y),f=(a(c.x+1E-5,c.y)-e)/1E-5,g=(a(c.x,c.y+1E-5)-e)/1E-5,e=e/(f*f+g*g),c=c.minus(V3(e*f,e*g));return c}
function followAlgorithm(a,b,c,d,e,f,g){NLA.assertNumbers(d,a(0,0));NLA.assertVectors(b,c);assert(!e||e instanceof V3);var h=[];f=f||[];assert(NLA.isZero(a(b.x,b.y)),"NLA.isZero(implicitCurve(startPoint.x, startPoint.y))");d=d||.5;var k=e?b.minus(e):b;e=0;do{var p=a(b.x,b.y),m=(a(b.x+1E-5,b.y)-p)/1E-5,p=(a(b.x,b.y+1E-5)-p)/1E-5,m=V3.create(-p,m,0),k=0>b.minus(k).dot(m),m=m.toLength(k?-d:d),m=b.plus(m);h.push(b);f.push(m);k=b;b=curvePoint(a,m)}while(100>e++&&(4>e||k.distanceTo(c)>1.1*d)&&g(b.x,b.x));
return h}function intersectionICurveICurve(a,b,c,d,e,f){NLA.assertNumbers(e,a(0,0),f(0,0));NLA.assertVectors(b,c);assert(!d||d instanceof V3);d=[];assert(NLA.isZero(a(b.x,b.y)));e=e||.5;f=b;for(var g=0;1E3>g++&&(4>g||b.distanceTo(c)>1.1*e);){var h=a(b.x,b.y),k=(a(b.x+1E-5,b.y)-h)/1E-5,h=(a(b.x,b.y+1E-5)-h)/1E-5,k=V3(-h,k,0).toLength(e);0>b.minus(f).dot(k)&&(k=k.negated());f=b;b=curvePoint(a,b.plus(k));d.push(b)}return d}
function asj(a,b,c){for(var d=b[0],e=c(d.x,d.y),f,g=[],h=0;h<b.length;h++)f=e,d=b[h],e=c(d),0>=e*f&&g.push(newtonIterate2d(a,c,d.x,d.y));return g}function cylinderPoints(a,b){assert(a instanceof L3);var c=a.dir1,d=c.getPerpendicular().normalized(),e=c.cross(d),f=M4.forSys(d.times(b),e.times(b),c,a.anchor);return function(a,b){return f.transformPoint(V3.create(cos(a),sin(a),b))}}
function cylinderImplicit(a,b){assert(a instanceof L3);var c=a.dir1,d=c.getPerpendicular().normalized(),e=c.cross(d),c=M4.forSys(d.times(b),e.times(b),c,a.anchor),f=c.inversed();assert(f.times(c).isIdentity(NLA.PRECISION));return function(a){a=f.transformPoint(a);return 1-Math.sqrt(a.x*a.x+a.y*a.y)}}
function newtonIterate2d(a,b,c,d,e){e=e||4;do{var f=a(c,d),g=b(c,d),h=a(c+1E-5,d)-f,k=a(c,d+1E-5)-f,p=b(c+1E-5,d)-g,m=b(c,d+1E-5)-g,l=(h*m-k*p)/1E-5,h=(-p*f+h*g)/l;c-=(m*f-k*g)/l;d-=h}while(--e&&f*f+g*g>NLA.PRECISION);return e?V3(c,d,0):null}function newtonIterate(a,b){for(var c=b,d=0;4>d;d++)var e=a(c),f=(a(c+1E-5)-e)/1E-5,c=c-e/f;return c}
function intersectionPCurveISurface(a,b,c,d,e){assertNumbers(b,c,d);for(var f=[],g=e(a(b)),h=b+d;h<=c;h+=d)b=g,g=e(a(h)),0>=g*b&&f.push(newtonIterate(function(b){return e(a(b))},h));return f}function intersectionICurvePSurface(a,b,c){}function blugh(a,b,c,d,e,f){for(var g=[];d<e;){g.push(d);a(d);var h=b(d),k=c(d);d+=f*(1+h*h)/Math.max(.3,Math.abs(k))}return g}function cassini(a,b){return function(c,d){return(c*c+d*d)*(c*c+d*d)-2*b*b*(c*c-d*d)-(a*a*a*a-b*b*b*b)}}var drPs=[];addGenerator();
function initB2(){dMesh=new GL.Mesh;eyePos=V3(0,100,100);eyeFocus=V3(0,100,0);eyeUp=V3(0,1,0);zoomFactor=.5;var a=B2.PlaneFace.forVertices(P3.XY,[V3(0,0),V3(10,0),V3(10,10),V3(0,10)]),b=(new B2([B2.PlaneFace.forVertices(P3.XY,[V3(0,0),V3(5,0),V3(5,10),V3(0,10)]).flipped().rotateX(-PI/8),B2.PlaneFace.forVertices(P3.XY,[V3(0,0),V3(5,0),V3(5,10),V3(0,10)]).rotateX(PI/8)])).rotateY(PI/2).translate(0,0,2);aMesh=a.inB2().toMesh();bMesh=b.toMesh();dMesh.compile()}var aMesh,bMesh,cMesh,dMesh;
function paintScreen2(){gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.loadIdentity();gl.scale(10,10,10);gl.loadIdentity();gl.scale(10,10,10);aMesh&&(gl.projectionMatrix.m[11]-=1/1048576,aMesh.lines&&singleColorShader.uniforms({color:rgbToVec4(COLORS.PP_STROKE)}).draw(aMesh,"LINES"),gl.projectionMatrix.m[11]+=1/1048576,lightingShader.uniforms({color:rgbToVec4(COLORS.PP_FILL),camPos:eyePos}).draw(aMesh));bMesh&&(gl.pushMatrix(),gl.projectionMatrix.m[11]-=1/1048576,bMesh.lines&&singleColorShader.uniforms({color:rgbToVec4(COLORS.PP_STROKE)}).draw(bMesh,
"LINES"),gl.projectionMatrix.m[11]+=1/1048576,lightingShader.uniforms({color:rgbToVec4(COLORS.TS_FILL),camPos:eyePos}).draw(bMesh),bMesh.edgeTangents&&singleColorShader.uniforms({color:rgbToVec4(COLORS.TS_STROKE)}).drawBuffers({gl_Vertex:bMesh.vertexBuffers.edgeTangents},null,gl.LINES),bMesh.edgeTangents2&&singleColorShader.uniforms({color:rgbToVec4(COLORS.RD_STROKE)}).drawBuffers({gl_Vertex:bMesh.vertexBuffers.edgeTangents2},null,gl.LINES),gl.popMatrix());cMesh&&(gl.pushMatrix(),gl.projectionMatrix.m[11]-=
1/1048576,cMesh.lines&&singleColorShader.uniforms({color:rgbToVec4(COLORS.TS_STROKE)}).draw(cMesh,"LINES"),gl.projectionMatrix.m[11]+=1/1048576,lightingShader.uniforms({color:rgbToVec4(COLORS.RD_FILL),camPos:eyePos}).draw(cMesh),gl.popMatrix());dMesh&&(gl.pushMatrix(),gl.projectionMatrix.m[11]-=1/1048576,dMesh.lines&&singleColorShader.uniforms({color:rgbToVec4(COLORS.RD_STROKE)}).draw(dMesh,"LINES"),gl.projectionMatrix.m[11]+=1/1048576,lightingShader.uniforms({color:rgbToVec4(16776960),camPos:eyePos}).draw(dMesh),
dMesh.curve1&&singleColorShader.uniforms({color:rgbToVec4(COLORS.TS_STROKE)}).drawBuffers({gl_Vertex:dMesh.vertexBuffers.curve1},null,gl.LINES),dMesh.curve2&&singleColorShader.uniforms({color:rgbToVec4(COLORS.RD_STROKE)}).drawBuffers({gl_Vertex:dMesh.vertexBuffers.curve2},null,gl.LINES),dMesh.curve3&&singleColorShader.uniforms({color:rgbToVec4(COLORS.PP_STROKE)}).drawBuffers({gl_Vertex:dMesh.vertexBuffers.curve3},null,gl.LINES),dMesh.curve4&&singleColorShader.uniforms({color:rgbToVec4(65280)}).drawBuffers({gl_Vertex:dMesh.vertexBuffers.curve4},
null,gl.LINES),gl.popMatrix());drPs.forEach(function(a){gl.pushMatrix();gl.translate(a);gl.scale(.5,.5,.5);lightingShader.uniforms({color:rgbToVec4(NLA.randomColor())}).draw(sMesh);lightingShader.uniforms({color:rgbToVec4(NLA.randomColor())}).draw(sMesh);singleColorShader.uniforms({color:rgbToVec4(COLORS.RD_STROKE)}).draw(sMesh,"LINES");gl.popMatrix()});drawPlanes()}
var planes=[CustomPlane(V3.ZERO,V3.Y,V3.Z,-500,500,-500,500,16711680),CustomPlane(V3.ZERO,V3.X,V3.Z,-500,500,-500,500,65280),CustomPlane(V3.ZERO,V3.X,V3.Y,-500,500,-500,500,255)],singleColorShader,textureColorShader,singleColorShaderHighlight,arcShader,arcShader2,xyLinePlaneMesh,gl,cubeMesh,lightingShader,vectorMesh,sMesh;
window.loadup=function(){window.onerror=function(a,b,c,d,e){console.log(a,b,c,d,e)};gl=GL.create({canvas:document.getElementById("testcanvas")});gl.fullscreen();gl.canvas.oncontextmenu=function(){return!1};setupCamera();gl.clearColor(1,1,1,0);gl.enable(gl.BLEND);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.depthFunc(gl.LEQUAL);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);cubeMesh=GL.Mesh.cube();gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.loadIdentity();gl.scale(10,10,10);gl.loadIdentity();
gl.onmousemove=function(a){if(a.dragging){if(a.buttons&4){var b=V3(2*-a.deltaX/gl.canvas.width,2*a.deltaY/gl.canvas.height,0),b=gl.projectionMatrix.inversed().transformVector(b);eyePos=eyePos.plus(b);eyeFocus=eyeFocus.plus(b);setupCamera();paintScreen2()}if(a.buttons&2){b=deg2rad(-a.deltaX/6);a=deg2rad(-a.deltaY/6);var b=M4.rotationLine(eyeFocus,eyeUp,b),c=eyeUp.cross(eyePos.minus(eyeFocus)),b=b.times(M4.rotationLine(eyeFocus,c,a));eyePos=b.transformPoint(eyePos);eyeUp=b.transformVector(eyeUp);setupCamera();
paintScreen2()}}};xyLinePlaneMesh=new GL.Mesh({lines:!0,triangles:!1});xyLinePlaneMesh.vertices=[[0,0],[0,1],[1,1],[1,0]];xyLinePlaneMesh.lines=[[0,1],[1,2],[2,3],[3,0]];xyLinePlaneMesh.compile();vectorMesh=rotationMesh([V3.ZERO,V3(0,.05,0),V3(.8,.05),V3(.8,.1),V3(1,0)],L3.X,2*Math.PI,8,!1);sMesh=GL.Mesh.sphere2(2);singleColorShader=new GL.Shader(vertexShaderBasic,fragmentShaderColor);singleColorShaderHighlight=new GL.Shader(vertexShaderBasic,fragmentShaderColorHighlight);textureColorShader=new GL.Shader(vertexShaderTextureColor,
fragmentShaderTextureColor);arcShader=new GL.Shader(vertexShaderRing,fragmentShaderColor);arcShader2=new GL.Shader(vertexShaderArc,fragmentShaderColor);lightingShader=new GL.Shader(vertexShaderLighting,fragmentShaderLighting);$(gl.canvas).addEvent("mousewheel",function(a){zoomFactor*=pow(.9,-a.wheel);var b=a.client;a=V3(2*b.x/gl.canvas.width-1,2*-b.y/gl.canvas.height+1,0).times(1-1/pow(.9,-a.wheel));a=gl.projectionMatrix.inversed().transformVector(a);eyePos=eyePos.plus(a);eyeFocus=eyeFocus.plus(a);
setupCamera();paintScreen2()});initB2();setupCamera();paintScreen2()};
