"sin cos min max PI sqrt pow round".split(" ").forEach(function(a){window[a]=Math[a]});var M4=NLA.Matrix4x4,V3=NLA.Vector3,P3=NLA.Plane3,L3=NLA.Line3,cardMesh;function setupCamera(){gl.matrixMode(gl.PROJECTION);gl.loadIdentity();gl.perspective(45,gl.canvas.width/gl.canvas.height,1E-4,1E8);gl.lookAt(eyePos,eyeFocus,eyeUp);gl.matrixMode(gl.MODELVIEW)}
var names=["name1","Narida","KOH","KoH2"],spinDirs,textures,bgTexture,halfSpinCounts,gridHeight,gridWidth,gridSize,globalId,time=0,TOTAL_FRAMES=600,aMesh,bMesh,cMesh,dMesh;
function paintScreen2(){time==TOTAL_FRAMES&&clearInterval(intt);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.loadIdentity();var a=Math.max(gridHeight,gridWidth/(gl.canvas.width/gl.canvas.height));gl.scale(1/a/1.1,1/a/1.1,1/a/1.1);gl.translate(1.1*-(-.5+gridWidth/2),1.1*-(-.5+gridHeight/2),0);textureShader.uniforms({texture:0});for(var b=a=0;a<names.length;a++,b++){gl.pushMatrix();gl.translate(b%gridWidth*1.1,1.1*Math.floor(b/gridWidth),0);var c=halfSpinCounts[a],d=time/TOTAL_FRAMES,d=pow(d-
1,3)- -1,d=-sin(2*PI*c*d)/4/PI+c*d;gl.rotate(PI*spinDirs[a]/2,0,0,1);gl.rotate(PI*d,1,0,0);gl.rotate(-PI*spinDirs[a]/2,0,0,1);gl.translate(-.5,-.5,0);textures[a].bind();textureShader.draw(cardMesh);gl.rotate(PI,0,1,0);gl.translate(-1,0,0);bgTexture.bind();textureShader.draw(cardMesh);gl.popMatrix()}time++}
function setupHTML(){$("setupToggle").onclick=function(){$("setupBox").toggleClass("nodisplay");var a=$("setupBox").hasClass("nodisplay");$("setupToggle").set("text",a?"[+]":"[-]");$$("button").setStyle("display",a?"inline":"block").setStyle("width",a?"auto":"100%")};$("cbUniques").onchange=$("cbPicarto").onchange=$("cbEmptyLines").onchange=$("nameInput").onchange=$("nameInput").onkeyup=function(){names=$("nameInput").value.split(/\n|\r|\r\n/);names=names.map(function(a){return a.trim()});if($("cbPicarto").checked){var a;
names=names.map(function(b){return(a=b.match(/\[([^\]]+)/))&&a[1]}).filter(function(a){return a})}$("cbEmptyLines").checked&&(names=names.filter(function(a){return""!=a}));$("cbUniques").checked&&(names=names.unique());doSetup();paintScreen2()};$("resetButton").onclick=function(){doSetup();clearTimeout(intt);paintScreen2()};$("spinButton").onclick=function(){$("nameInput").onchange();clearTimeout(intt);intt=setInterval(paintScreen2,1E3/60);if(!$("setupBox").hasClass("nodisplay"))$("setupToggle").onclick()};
$("nameInput").onchange()}function doSetup(){time=0;var a=names.length;gridHeight=Math.round(Math.sqrt(a/(gl.canvas.width/gl.canvas.height)))||1;gridWidth=Math.ceil(a/gridHeight);gridSize=gridWidth*gridHeight;a=Math.floor(Math.random()*a);spinDirs=names.map(function(a){return Math.floor(4*Math.random())});halfSpinCounts=names.map(function(a){return 5+2*Math.floor(4*Math.random())});halfSpinCounts[a]++;textures=names.map(function(a){return makeTextureForName(a)});bgTexture=makeCardBG()}
function makeCardBG(){var a=$("textTextureCanvas"),b=a.getContext("2d");b.save();b.scale(b.canvas.width,b.canvas.height);var c=$("cardBG");b.fillStyle="#440000";b.fillRect(0,0,1,1);b.translate(.05,.05);b.scale(.9/c.width,.9/c.height);b.drawImage(c,0,0);b.restore();return GL.Texture.fromImage(a,{minFilter:gl.LINEAR_MIPMAP_LINEAR,magFilter:gl.LINEAR})}var savedTextures=new Map;
function makeTextureForName(a){var b;if(b=savedTextures.get(a))return b;b=$("textTextureCanvas");var c=b.getContext("2d");c.save();c.scale(c.canvas.width,c.canvas.height);c.fillStyle="#440000";c.fillRect(0,0,1,1);c.fillStyle="#FAE4BD";c.fillRect(.05,.05,.9,.9);var d=.3;c.font="0.3px Calibri";c.fillStyle="#F08326";c.strokeStyle="#560200";c.lineWidth=.004;c.textAlign="center";c.textBaseline="middle";c.imageSmoothingEnabled=!1;var e=c.measureText(a).width;c.translate(.5,.5);.9<e&&(d/=e,c.font=d+"px Calibri",
c.rotate(PI/4));c.fillText(a,0,.25*d);c.strokeText(a,0,.25*d);b=GL.Texture.fromImage(b,{minFilter:gl.LINEAR_MIPMAP_LINEAR,magFilter:gl.LINEAR});savedTextures.set(a,b);c.restore();return b}var singleColorShader,textureShader,textureColorShader,singleColorShaderHighlight,arcShader,arcShader2,xyLinePlaneMesh,gl,cubeMesh,lightingShader,vectorMesh,sMesh;
window.doDiversion=function(){window.onerror=function(a,b,c,d,e){console.log(a,b,c,d,e)};gl=GL.create();gl.fullscreen();gl.canvas.oncontextmenu=function(){return!1};gl.clearColor(1,1,1,0);gl.enable(gl.BLEND);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.depthFunc(gl.LESS);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);cubeMesh=GL.Mesh.cube();gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.loadIdentity();gl.scale(10,10,10);gl.loadIdentity();gl.onmousemove=function(a){if(a.dragging){if(a.buttons&
4){var b=V3(2*-a.deltaX/gl.canvas.width,2*a.deltaY/gl.canvas.height,0),b=gl.projectionMatrix.inversed().transformVector(b);eyePos=eyePos.plus(b);eyeFocus=eyeFocus.plus(b);setupCamera();paintScreen2()}if(a.buttons&2){b=deg2rad(-a.deltaX/6);a=deg2rad(-a.deltaY/6);var b=M4.rotationLine(eyeFocus,eyeUp,b),c=eyeUp.cross(eyePos.minus(eyeFocus)),b=b.times(M4.rotationLine(eyeFocus,c,a));eyePos=b.transformPoint(eyePos);eyeUp=b.transformVector(eyeUp);setupCamera();paintScreen2()}}};xyLinePlaneMesh=new GL.Mesh({lines:!0,
triangles:!1});xyLinePlaneMesh.vertices=[[0,0],[0,1],[1,1],[1,0]];xyLinePlaneMesh.lines=[[0,1],[1,2],[2,3],[3,0]];xyLinePlaneMesh.compile();sMesh=GL.Mesh.sphere2(2);singleColorShader=new GL.Shader(vertexShaderBasic,fragmentShaderColor);singleColorShaderHighlight=new GL.Shader(vertexShaderBasic,fragmentShaderColorHighlight);textureColorShader=new GL.Shader(vertexShaderTexture,fragmentShaderTextureColor);textureShader=new GL.Shader(vertexShaderTexture,fragmentShaderTexture);arcShader=new GL.Shader(vertexShaderRing,
fragmentShaderColor);arcShader2=new GL.Shader(vertexShaderArc,fragmentShaderColor);lightingShader=new GL.Shader(vertexShaderLighting,fragmentShaderLighting);$(gl.canvas).addEvent("mousewheel",function(a){zoomFactor*=pow(.9,-a.wheel);var b=a.client;a=V3(2*b.x/gl.canvas.width-1,2*-b.y/gl.canvas.height+1,0).times(1-1/pow(.9,-a.wheel));a=gl.projectionMatrix.inversed().transformVector(a);eyePos=eyePos.plus(a);eyeFocus=eyeFocus.plus(a);setupCamera();paintScreen2()});cardMesh=createRectangleMesh(0,0,1,1);
eyePos=V3(-.3,-.2,1.2);eyeFocus=V3(-0,-0,-.3);eyeUp=V3(0,1,0);zoomFactor=.5;setupCamera();setupCamera();setupHTML();paintScreen2()};var eyePos,eyeFocus,eyeUp,zoomFactor,intt;
