var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};
$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(b,d);void 0!==e&&$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};var NLA={};window.NLA=NLA;
var assertVectors=NLA.assertVectors=function(){if(NLA_DEBUG)for(var a=0;a<arguments.length;a++)if(!(arguments[a]instanceof NLA.Vector3||arguments[a]instanceof NLA.Vector))throw Error("NLA.assertVectors arguments["+a+"] is not a vector. "+typeof arguments[a]+" == typeof "+arguments[a]);return!0},assertInst=NLA.assertInst=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(NLA_DEBUG)for(d=0;d<c.length;d++)if(!(c[d]instanceof a))throw Error("assertInst objs["+d+"] is not a "+
a.prototype.name+". "+c[d].constructor.name);return!0},assertNumbers=NLA.assertNumbers=function(){if(NLA_DEBUG)for(var a=0;a<arguments.length;a++)if("number"!==typeof arguments[a])throw Error("NLA.assertNumbers arguments["+a+"] is not a number. "+typeof arguments[a]+" == typeof "+arguments[a]);return!0},assert=function(a,b){if(NLA_DEBUG&&!a)throw Error("NLA.assert failed: function"==typeof b?b():b);return!0};NLA.PRECISION=1/67108864;console.log("NLA.PRECISION",NLA.PRECISION);var NLA_DEBUG=!0;
NLA.isZero=function(a){return Math.abs(a)<NLA.PRECISION};NLA.isZero2=function(a,b){return Math.abs(a)<b};NLA.equals=function(a,b){return Math.abs(a-b)<=NLA.PRECISION};NLA.lt=function(a,b){return a+NLA.PRECISION<b};NLA.gt=function(a,b){return a>b+NLA.PRECISION};NLA.le=function(a,b){return a<=b+NLA.PRECISION};NLA.ge=function(a,b){return a+NLA.PRECISION>=b};NLA.equals2=function(a,b,c){return Math.abs(a-b)<c};NLA.eqAngle=function(a,b){return NLA.zeroAngle(a-b)};
NLA.zeroAngle=function(a){return(a%(2*Math.PI)+2*Math.PI+NLA.PRECISION)%(2*Math.PI)<2*NLA.PRECISION};NLA.snapTo=function(a,b){return Math.abs(a-b)<=NLA.PRECISION?b:a};NLA.canonAngle=function(a){return(a%(2*Math.PI)+2*Math.PI)%(2*Math.PI)};var COLORS={RD_FILL:10411001,RD_STROKE:7844064,TS_FILL:13737955,TS_STROKE:10972098,PP_FILL:15972047,PP_STROKE:15434164},DEG=.017453292519943295;function deg2rad(a){return.017453292519943295*a}function rad2deg(a){return a/.017453292519943295}
NLA.repeatString=function(a,b){if(0==a)return"";a*=b.length;for(var c=a/2,d=b;d.length<=c;)d+=d;return d+d.substring(0,a-d.length)};NLA.mod=function(a,b){return(a%b+b)%b};NLA.arraySwap=function(a,b,c){var d=a[b];a[b]=a[c];a[c]=d};NLA.arrayCopy=function(a,b,c,d,e){d+=e;for(e+=b;e-- >b;)c[--d]=a[e]};NLA.clamp=function(a,b,c){NLA.assertNumbers(a,b,c);return Math.max(b,Math.min(c,a))};NLA.CustomSet=function(a){this._map=new Map;this._size=0;a&&this.addAll(a)};
NLA.CustomSet.prototype={add:function(a){var b=a.hashCode(),c=this._map.get(b);if(c){if(c.some(function(b){return b.equals(a)}))return!1;c.push(a)}else this._map.set(b,[a]);this._size++;return!0},addAll:function(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())this.add(b.value)},canonicalize:function(a){var b=a.hashCode(),c=this._map.get(b);if(c){if(b=c.find(function(b){return b.equals(a)}))return b;c.push(a)}else this._map.set(b,[a]);this._size++;return a},has:function(a){var b=
a.hashCode();return(b=this._map.get(b))&&b.some(function(b){return b.equals(a)})},getLike:function(a){for(var b=$jscomp.makeIterator(a.hashCodes()),c=b.next();!c.done;c=b.next())if(c=(c=this._map.get(c.value))&&c.find(function(b){return b.like(a)}))return c},canonicalizeLike:function(a){return this.getLike(a)||this.canonicalize(a)},addLike:function(a){return!this.getLike(a)&&this.add(a)},delete:function(a){var b=a.hashCode();if(b=this._map.get(b)){var c=b.findIndex(function(b){return b.equals(a)});
if(-1!=c)return 1==b.size?this._map.delete(b):b.splice(c,1),this._size--,!0}return!1},deleteLike:function(a){for(var b=$jscomp.makeIterator(a.hashCodes()),c=b.next();!c.done;c=b.next())if(c=this._map.get(c.value)){var d=c.findIndex(function(b){return b.like(a)});if(-1!=d)return b=c[d],1==c.size?this._map.delete(c):c.splice(d,1),this._size--,b}},entries:function(){function a(a,k){for(;;)switch(b){case 0:g=$jscomp.makeIterator(h._map),f=g.next();case 1:if(f.done){b=3;break}e=f.value;d=$jscomp.makeIterator(e);
case 4:if((c=d.next(a)).done){b=5;break}b=6;return{value:c.value,done:!1};case 6:if(void 0===k){b=7;break}b=-1;throw k;case 7:b=4;break;case 5:case 2:f=g.next();b=1;break;case 3:b=-1;default:return{value:void 0,done:!0}}}var b=0,c,d,e,f,g,h=this,k={next:function(b){return a(b,void 0)},throw:function(b){return a(void 0,b)}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k},clear:function(){this._map.clear();this._size=0},get size(){return this._size}};
NLA.CustomMap=function(){};
NLA.CustomMap.prototype={set:function(a,b){var c=a.hashCode(),d=this._map.get(c);if(d)if(c=d.findIndex(function(b){return b.key.equals(a)}),-1==c)d.push({key:a,value:b});else return d[c].value=b,!1;else this._map.set(c,[{key:a,value:b}]);this._size++;return!0},has:function(a){var b=a.hashCode();return(b=this._map.get(b))&&b.some(function(b){return b.key.equals(a)})},getLike:function(a){for(var b=$jscomp.makeIterator(a.hashCodes()),c=b.next();!c.done;c=b.next())if(c=(c=this._map.get(c.value))&&c.find(function(b){return b.key.like(a)}))return c},
setLike:function(a,b){return!this.getLike(b)&&this.set(a,b)},delete:function(a){var b=a.hashCode();if(b=this._map.get(b)){var c=b.findIndex(function(b){return b.key.equals(a)});if(-1!=c)return 1==b.size?this._map.delete(b):b.splice(c,1),this._size--,!0}return!1},deleteLike:function(a){for(var b=$jscomp.makeIterator(a.hashCodes()),c=b.next();!c.done;c=b.next())if(c=this._map.get(c.value)){var d=c.findIndex(function(b){return b.key.like(a)});if(-1!=d)return b=c[d],1==c.size?this._map.delete(c):c.splice(d,
1),this._size--,b}},entries:function(){function a(a,k){for(;;)switch(b){case 0:g=$jscomp.makeIterator(h._map),f=g.next();case 1:if(f.done){b=3;break}e=f.value;d=$jscomp.makeIterator(e);case 4:if((c=d.next(a)).done){b=5;break}b=6;return{value:c.value,done:!1};case 6:if(void 0===k){b=7;break}b=-1;throw k;case 7:b=4;break;case 5:case 2:f=g.next();b=1;break;case 3:b=-1;default:return{value:void 0,done:!0}}}var b=0,c,d,e,f,g,h=this,k={next:function(b){return a(b,void 0)},throw:function(b){return a(void 0,
b)}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k},clear:function(){this._map.clear();this._size=0},get size(){return this._size}};NLA.CustomSet.prototype.values=NLA.CustomSet.prototype.entries;$jscomp.initSymbol();$jscomp.initSymbolIterator();NLA.CustomSet.prototype[Symbol.iterator]=NLA.CustomSet.prototype.entries;NLA.CustomSet.prototype.keys=NLA.CustomSet.prototype.entries;NLA.randomColor=function(){return Math.floor(16777216*Math.random())};
NLA.mapAdd=function(a,b,c){var d=a.get(b);d?d.push(c):a.set(b,[c])};NLA.addTransformationMethods=function(a){NLA.addOwnProperties(a,NLA.Transformable.prototype)};String.prototype.capitalizeFirstLetter=function(){return this.charAt(0).toUpperCase()+this.slice(1)};
var ARRAY_UTILITIES={pushAll:function(a){Array.prototype.push.apply(this,a)},copyStep:function(a,b,c,d,e,f,g){var h=b+g*c;for(e+=g*f;h>b;)d[e-=f]=a[h-=c]},sliceStep:function(a,b,c){NLA.assertNumbers(a,b);c=c||1;for(var d=Array(Math.ceil((this.length-a)/b)),e=0,f=0;f<this.length;f+=b)for(var g=0;g<c;g++)d[e++]=this[a+f+g];return d},concatenated:function(){return Array.prototype.concat.apply([],this)},min:function(){return Math.min.apply(null,this)},max:function(){return Math.max.apply(null,this)},
indexWithMax:function(a){if(0==this.length)return 0;for(var b=this.length,c=-1,d=-Infinity;b--;){var e=a(this[b],b);e>d&&(d=e,c=b)}return c},withMax:function(a){for(var b=this.length,c=void 0,d=-Infinity;b--;){var e=this[b],f=a(e);f>d&&(d=f,c=e)}return c},absSum:function(){for(var a=this.length,b=0;a--;)b+=Math.abs(this[a]);return b},sum:function(){for(var a=this.length,b=0;a--;)b+=this[a];return b},isEmpty:function(){return 0==this.length},unique:function(){var a=new Set(this);return Array.from(a)},
remove:function(a){a=this.indexOf(a);-1!=a&&this.splice(a,1)},removeAll:function(a){for(var b=a.length;b--;)this.remove(a[b])},toggle:function(a){var b=this.indexOf(a);-1!=b?this.splice(b,1):this.push(a)},binaryIndexOf:function(a,b){for(var c=0,d=this.length-1,e,f;c<=d;)if(e=(c+d)/2|0,f=this[e],0>b(f,a))c=e+1;else if(0<b(f,a))d=e-1;else return e;return-c-1},binaryInsert:function(a,b){b=b||NLA.minus;for(var c=0,d=this.length,e,f;c<d;)e=~~((c+d)/2),f=this[e],0>b(f,a)?c=e+1:d=e;this.splice(c,0,a)}};
NLA.minus=function(a,b){return a-b};var $jscomp$loop$9={key:void 0},key;for(key in ARRAY_UTILITIES)$jscomp$loop$9.key=key,NLA["array"+$jscomp$loop$9.key.capitalizeFirstLetter()]=function(a){return function(b,c){for(var d=[],e=1;e<arguments.length;++e)d[e-1]=arguments[e];ARRAY_UTILITIES[a.key].apply(b,d)}}($jscomp$loop$9),$jscomp$loop$9={key:$jscomp$loop$9.key};NLA.arrayCopyStep=function(a,b,c,d,e,f,g){var h=b+g*c;for(e+=g*f;h>b;)d[e-=f]=a[h-=c]};
NLA.arrayCopyBlocks=function(a,b,c,d,e,f,g,h){for(var k=0;k<h;k++)NLA.arrayCopy(a,b+c*k,d,e+f*k,g)};NLA.arrayRange=function(a,b,c){NLA.assertNumbers(a,c);console.log(Math.ceil((b-a)/c));a=Array(Math.ceil((b-a)/c));for(var d=0,e=0;e<b;e+=c)a[d++]=e;return a};NLA.arrayFromFunction=function(a,b){NLA.assertNumbers(a);assert("function"==typeof b);for(var c=Array(a),d=a;d--;)c[d]=b(d);return c};NLA.Vector=function(a){if(NLA_DEBUG&&!(a instanceof Float64Array))throw Error("!!");this.v=a};
NLA.Vector.fromFunction=function(a,b){NLA.assertNumbers(a);for(var c=new Float64Array(a),d=a;d--;)c[d]=b(d);return new NLA.Vector(c)};NLA.Vector.random=function(a){return NLA.Vector.fromFunction(a,function(a){return Math.random()})};
NLA.Vector.fromArguments=function(){assert(arguments[0]instanceof Float64Array||arguments.every(function(a){return"number"==typeof a}),"arguments[0] instanceof Float64Array || arguments.every(a => 'number' == typeof a)");return new NLA.Vector(arguments[0]instanceof Float64Array?arguments[0]:Float64Array.from(arguments))};NLA.V=NLA.Vector.fromArguments;
NLA.Vector.prototype={dim:function(){return this.v.length},e:function(a){if(0>a||a>=this.v.length)throw Error("array index out of bounds");return this.v[a]},plus:function(a){var b=this.v;a=a.v;for(var c=new Float64Array(b.length),d=b.length;d--;)c[d]=b[d]+a[d];return new NLA.Vector(c)},minus:function(a){var b=this.v;a=a.v;for(var c=new Float64Array(b.length),d=b.length;d--;)c[d]=b[d]-a[d];return new NLA.Vector(c)},div:function(a){for(var b=this.v,c=new Float64Array(b.length),d=b.length;d--;)c[d]=
b[d]/a;return new NLA.Vector(c)},dot:function(a){assert(this.dim==a.dim,"passed vector must have the same dim");var b=0,c=this.v;a=a.v;for(var d=c.length;d--;)b+=c[d]*a[d];return b},times:function(a){for(var b=this.v,c=new Float64Array(b.length),d=b.length;d--;)c[d]=b[d]*a;return new NLA.Vector(c)},cross:function(a){assert(a instanceof NLA.Vector,"vector instanceof NLA.Vector");var b=new Float64Array(3);b[0]=this.v[1]*a.v[2]-this.v[2]*a.v[1];b[1]=this.v[2]*a.v[0]-this.v[0]*a.v[2];b[2]=this.v[0]*a.v[1]-
this.v[1]*a.v[0];return new NLA.Vector(b)},equals:function(a){if(a===this)return!0;if(a.constructor==NLA.Vector||this.v.length!=a.v.length)return!1;for(var b=this.v.length;b--;)if(!NLA.equals(this.v[b],a.v[b]))return!1;return!0},map:function(a){for(var b=new Float64Array(this.v.length),c=b.length;c--;)b[c]=a(c);return new NLA.Vector(b)},toString:function(a){a=a||function(a){return+a.toFixed(6)};return"NLA.Vector("+this.v.map(a).join(", ")+")"},angleTo:function(a){assert(a instanceof NLA.Vector,"vector instanceof NLA.Vector");
assert(!this.isZero(),"!this.isZero()");assert(!a.isZero(),"!vector.isZero()");return Math.acos(this.dot(a)/this.length()/a.length())},isParallelTo:function(a){assert(a instanceof NLA.Vector,"vector instanceof NLA.Vector");assert(!this.isZero(),"!this.isZero()");assert(!a.isZero(),"!vector.isZero()");return NLA.equals(Math.sqrt(this.lengthSquared()*a.lengthSquared()),Math.abs(this.dot(a)))},isPerpendicularTo:function(a){assert(a instanceof NLA.Vector,"vector instanceof NLA.Vector");assert(!this.isZero(),
"!this.isZero()");assert(!a.isZero(),"!vector.isZero()");return NLA.isZero(this.dot(a))},isZero:function(){return NLA.isZero(this.length())},length:function(){return Math.sqrt(this.lengthSquared())},lengthSquared:function(){for(var a=0,b=this.v,c=b.length;c--;)a+=b[c]*b[c];return a},normalized:function(){var a=this.length();if(NLA.isZero(a))throw Error("cannot normalize zero vector");return this.div(this.length())},asRowMatrix:function(){return new NLA.Matrix(this.v.length,1,this.v)},asColMatrix:function(){return new NLA.Matrix(1,
this.v.length,this.v)},projectedOn:function(a){assert(a instanceof NLA.Vector,"b instanceof NLA.Vector");return a.times(this.dot(a)/a.dot(a))},rejectedOn:function(a){assert(a instanceof NLA.Vector,"b instanceof NLA.Vector");return this.minus(a.times(this.dot(a)/a.dot(a)))},hasLength:function(a){NLA.assertNumbers(a);return NLA.equals(a,this.length())}};
NLA.addOwnProperties=function(a,b){b&&Object.getOwnPropertyNames(b).forEach(function(c){b.hasOwnProperty(c)&&(a.hasOwnProperty(c)&&console.warn("target ",a," already has property ",c),Object.defineProperty(a,c,Object.getOwnPropertyDescriptor(b,c)))})};NLA.degineClagg=function(a,b,c,d,e){assert("function"==typeof c,"'function' == typeof constructor");c.prototype=NLA.defineObject(b&&b.prototype,d);c.prototype.constructor=c;c.prototype.name=a;NLA.addOwnProperties(c,e);return c};
NLA.defaultRoundFunction=function(a){return Math.round10(a,-4)};NLA.defineObject=function(a,b){var c=Object.create(a||NLA.BaseObject);NLA.addOwnProperties(c,b);return c};NLA.BaseObject=function(a){Object.apply(this,arguments)};$jscomp.inherits(NLA.BaseObject,Object);NLA.BaseObject.assign=Object.assign;NLA.BaseObject.isFrozen=Object.isFrozen;NLA.BaseObject.isSealed=Object.isSealed;NLA.BaseObject.isExtensible=Object.isExtensible;NLA.BaseObject.freeze=Object.freeze;NLA.BaseObject.seal=Object.seal;
NLA.BaseObject.preventExtensions=Object.preventExtensions;NLA.BaseObject.getPrototypeOf=Object.getPrototypeOf;NLA.BaseObject.getOwnPropertyNames=Object.getOwnPropertyNames;NLA.BaseObject.keys=Object.keys;NLA.BaseObject.getOwnPropertyDescriptor=Object.getOwnPropertyDescriptor;NLA.BaseObject.defineProperties=Object.defineProperties;NLA.BaseObject.defineProperty=Object.defineProperty;NLA.BaseObject.create=Object.create;
NLA.BaseObject.prototype.toSource=function(){return this.toString==Object.prototype.toString?Object.prototype.toSource.apply(this):this.toString()};Object.defineProperties(NLA.BaseObject.prototype,{$:{configurable:!0,enumerable:!0,get:function(){return this.toSource()}}});NLA.forceFinite=function(a){a=parseFloat(a.replace(",",".").replace(/^[^0-9,\.\-]/,""));return Number.isFinite(a)?a:0};
(function(){function a(a,c,d){if("undefined"===typeof d||0===+d)return Math[a](c);c=+c;d=+d;if(isNaN(c)||"number"!==typeof d||0!==d%1)return NaN;c=c.toString().split("e");c=Math[a](+(c[0]+"e"+(c[1]?+c[1]-d:-d)));c=c.toString().split("e");return+(c[0]+"e"+(c[1]?+c[1]+d:d))}Math.round10||(Math.round10=function(b,c){return a("round",b,c)});Math.floor10||(Math.floor10=function(b,c){return a("floor",b,c)});Math.ceil10||(Math.ceil10=function(b,c){return a("ceil",b,c)})})();
NLA.Matrix=function(a,b,c){assert(a*b==c.length,"uhm...");this.m=c;this.width=a;this.height=b};NLA.Matrix.random=function(a,b){NLA.assertNumbers(a,b);return NLA.Matrix.fromFunction(a,b,function(a,b){return Math.random()})};NLA.Matrix.fromFunction=function(a,b,c){NLA.assertNumbers(a,b);for(var d=new Float64Array(b*a),e=b*a;e--;)d[e]=c(Math.floor(e/a),e%a,e);return new NLA.Matrix(a,b,d)};
NLA.Matrix.identity=function(a){NLA.assertNumbers(a);for(var b=new Float64Array(a*a),c=a*(a+1);c;)c-=a+1,b[c]=1;return new NLA.Matrix(a,a,b)};NLA.Matrix.permutation=function(a,b,c){NLA.assertNumbers(a,b,c);for(var d=new Float64Array(a*a),e=a*(a+1);e;)e-=a+1,d[e]=1;d[b*a+b]=0;d[c*a+c]=0;d[b*a+c]=1;d[c*a+b]=1;return new NLA.Matrix(a,a,d)};NLA.Matrix.fromRowArrays=function(){return NLA.Matrix.fromRowArrays2(arguments)};
NLA.Matrix.fromRowArrays2=function(a){if(0==a.length)throw Error("cannot have 0 vector");var b=a.length,c=a[0].length,d=new Float64Array(b*c);NLA.arrayCopy(a[0],0,d,0,c);for(var e=1;e<b;e++){if(a[e].length!=c)throw Error("all row arrays must be the same length");NLA.arrayCopy(a[e],0,d,e*c,c)}return new NLA.Matrix(c,b,d)};NLA.Matrix.fromColVectors=function(a){return NLA.Matrix.fromColArrays(a.map(function(a){return a.v}))};
NLA.Matrix.forWidthHeight=function(a,b){return new NLA.Matrix(a,b,new Float64Array(a*b))};NLA.Matrix.fromColArrays=function(a){if(0==a.length)throw Error("cannot have 0 vector");var b=a.length,c=a[0].length,d=new Float64Array(c*b);NLA.arrayCopyStep(a[0],0,1,d,0,b,c);for(var e=1;e<b;e++){if(a[e].length!=c)throw Error("all col arrays must be the same length");NLA.arrayCopyStep(a[e],0,1,d,e,b,c)}return new NLA.Matrix(b,c,d)};
NLA.Matrix.prototype={e:function(a,b){NLA.assertNumbers(a,b);if(NLA_DEBUG&&(a>=this.height||b>=this.width))throw Error("index "+a+", "+b+" is out of bounds ("+this.width+" x "+this.height+")");return this.m[a*this.width+b]},setEl:function(a,b,c){NLA.assertNumbers(a,b);assert(0<=a&&a<this.height,"rowIndex out of bounds "+a);assert(0<=b&&b<this.width,"colIndex out of bounds "+b);this.m[a*this.width+b]=c},toString:function(a){var b=this;a=a||function(a){return a.toFixed(3)};assert("string"==typeof a(0),
""+typeof a(0));var c=Array.prototype.slice.call(this.m).map(a),d=NLA.arrayFromFunction(this.width,function(a){return c.sliceStep(a,b.width).map(function(a){return a.length}).max()});return NLA.arrayFromFunction(this.height,function(a){return c.slice(a*b.width,(a+1)*b.width).map(function(a,b){return NLA.repeatString(d[b]-a.length," ")+a}).join(" ")}).map(function(a){return a+"\n"}).join("")},row:function(a){var b=new Float64Array(this.width);NLA.arrayCopy(this.m,a*this.width,b,0,this.width);return new NLA.Vector(b)},
col:function(a){var b=new Float64Array(this.height);NLA.arrayCopyStep(this.m,a,this.width,b,0,1,this.height);return new NLA.Vector(b)},dim:function(){return{width:this.width,height:this.height}},dimString:function(){return this.width+"x"+this.height},equals:function(a){if(a.constructor!=NLA.Matrix||this.width!=a.width||this.height!=a.height)return!1;for(var b=this.m.length;b--;)if(this.m[b]!=a.m[b])return!1},equalsMatrix:function(a,b){b=b||NLA.PRECISION;if(!(a instanceof NLA.Matrix))throw Error("not a matrix");
if(this.width!=a.width||this.height!=a.height)return!1;for(var c=this.m.length;c--;)if(Math.abs(this.m[c]-a.m[c])>=b)return!1;return!0},hashCode:function(){for(var a=0,b=this.m.length;b--;)a=31*a+NLA.floatHashCode(this.m[b]);return a},isOrthogonal:function(){return this.isSquare()&&this.transposed().times(this).equalsMatrix(NLA.Matrix.identity(this.width))},luDecomposition:function(){assert(this.isSquare());for(var a=this.asRowArrays(Float64Array),b=this.width,c=NLA.arrayFromFunction(b,function(a){return new Float64Array(b)}),
d=NLA.Matrix.identity(b).asRowArrays(Float64Array),e=0;e<b;e++){for(var f=0,g=b,h=e;--g>=e;)Math.abs(a[g][e])>=f&&(f=Math.abs(a[g][e]),h=g);NLA.arraySwap(a,e,h);NLA.arraySwap(c,e,h);NLA.arraySwap(d,e,h);c[e][e]=1;for(g=e+1;g<b;g++)for(f=a[g][e]/a[e][e],c[g][e]=f,h=e;h<b;h++)a[g][h]-=f*a[e][h]}return{L:NLA.Matrix.fromRowArrays2(c),U:NLA.Matrix.fromRowArrays2(a),P:NLA.Matrix.fromRowArrays2(d)}},qrDecompositionGivensRotation:function(){for(var a=NLA.Matrix.identity(this.height),b=0;b<this.width;b++)for(var c=
b+1;c<this.height;c++){var d=this.e(b,b),e=this.e(c,b);if(0!=e){for(var f=Math.sqrt(d*d+e*e),d=d/f,e=e/f,f=b;f<this.width;f++){var g=this.e(b,f)*d+this.e(c,f)*e,h=this.e(c,f)*d-this.e(b,f)*e;this.setEl(b,f,g);this.setEl(c,f,h)}f=b;g=c;h=NLA.Matrix.identity(this.height);h.setEl(f,f,d);h.setEl(g,g,d);h.setEl(f,g,e);h.setEl(g,f,-e);a=h.times(a)}}return{Q:a.transposed(),R:this}},isPermutation:function(){return!this.isSquare()||this.m.some(function(a){return!NLA.isZero(a)&&!NLA.equals(1,a)})||this.asRowArrays(Array).some(function(a){return 1!=
a.filter(function(a){return NLA.equals(1,a)}).length})||this.asColArrays(Array).some(function(a){return 1!=a.filter(function(a){return NLA.equals(1,a)}).length})?!1:!0},isIdentity:function(a){return this.isLowerUnitriangular(a)&&this.isUpperTriangular(a)},isUpperTriangular:function(){if(!this.isSquare())return!1;for(var a=1;a<this.height;a++)for(var b=0;b<a;b++)if(!NLA.isZero(this.m[a*this.width+b]))return!1;return!0},solveLinearSystem:function(a){var b=this.luDecomposition();a=b.L.solveForwards(b.P.timesVector(a));
return b.U.solveBackwards(a)},isLowerUnitriangular:function(a){a="number"==typeof a?a:NLA.PRECISION;if(!this.isSquare())return!1;for(var b=0;b<this.height-1;b++)for(var c=b;c<this.width;c++){var d=this.m[b*this.width+c];if(b==c?!NLA.equals2(1,d,a):!NLA.isZero2(d,a))return!1}return!0},isLowerTriangular:function(){if(!this.isSquare())return!1;for(var a=0;a<this.height-1;a++)for(var b=a+1;b<this.width;b++)if(!NLA.isZero(this.m[a*this.width+b]))return!1;return!0},solveBackwards:function(a){NLA.assertVectors(a);
assert(this.height==a.dim(),"this.height == x.dim()");assert(this.isUpperTriangular(),"this.isUpperTriangular()");for(var b=new Float64Array(this.width),c=this.height;c--;){for(var d=a.v[c],e=c+1;e<this.width;e++)d-=b[e]*this.e(c,e);b[c]=d/this.e(c,c)}return new NLA.Vector(b)},solveBackwardsMatrix:function(a){for(var b=Array(a.width),c=a.width;c--;)b[c]=this.solveBackwards(a.col(c));return NLA.Matrix.fromColVectors(b)},solveForwardsMatrix:function(a){for(var b=Array(a.width),c=a.width;c--;)b[c]=this.solveForwards(a.col(c));
return NLA.Matrix.fromColVectors(b)},solveForwards:function(a){NLA.assertVectors(a);assert(this.height==a.dim(),"\u00b0\u00b0");assert(this.isLowerTriangular(),"\u00b0\u00b0");for(var b=new Float64Array(this.width),c=0;c<this.height;c++){for(var d=a.v[c],e=0;e<c;e++)d-=b[e]*this.e(c,e);b[c]=d/this.e(c,c)}return new NLA.Vector(b)},rank:function(){for(var a=this.qrDecompositionGivensRotation().R,b=this.height;b--&&a.row(b).isZero(););return b+1},rowsIndependent:function(){return this.height==this.rank()},
colsIndependent:function(){return this.width==this.rank()},asRowArrays:function(a){a=a||Float64Array;for(var b=this.height,c=Array(this.height);b--;)c[b]=this.rowArray(b,a);return c},asColArrays:function(a){a=a||Float64Array;for(var b=this.width,c=Array(this.width);b--;)c[b]=this.colArray(b,a);return c},rowArray:function(a,b){b=b||Float64Array;var c=new b(this.width);NLA.arrayCopy(this.m,a*this.width,c,0,this.width);return c},colArray:function(a,b){b=b||Float64Array;var c=new b(this.width);NLA.arrayCopyStep(this.m,
a,this.height,c,0,1,this.height);return c},subMatrix:function(a,b,c,d){if(a+b>this.width||c+d>this.height)throw Error("inavlid params");c=new Float64Array(this.height);NLA.arrayCopyBlocks(this.m,a,this.width,c,0,b,d,b);return new NLA.Matrix(b,d,c)},map:function(a){return new NLA.Matrix(this.width,this.height,this.m.map(a))},dimEquals:function(a){assert(a instanceof NLA.Matrix,"matrix is not a NLA.Matrix");return this.width==a.width&&this.height==a.height},inversed:function(){var a=this.luDecomposition(),
b=a.L.solveForwardsMatrix(a.P);return a.U.solveBackwardsMatrix(b)},canMultiply:function(a){assert(a instanceof NLA.Matrix,"matrix is not a NLA.Matrix"+a);return this.width==a.height},times:function(a){assert(a instanceof NLA.Matrix);assert(this.canMultiply(a),"Cannot multiply this {this.dimString()} by matrix {matrix.dimString()}");for(var b=a.width,c=this.height,d=this.width,e=new Float64Array(b*c),f=c;f--;)for(var g=b;g--;){for(var h=0,k=d;k--;)h+=this.m[f*d+k]*a.m[k*b+g];e[f*b+g]=h}return new NLA.Matrix(b,
c,e)},timesVector:function(a){NLA.assertVectors(a);assert(this.width==a.dim());for(var b=this.height,c=this.width,d=new Float64Array(b);b--;){for(var e=0,f=c;f--;)e+=this.m[b*c+f]*a.v[f];d[b]=e}return new NLA.Vector(d)},transposed:function(){for(var a=this.height,b=this.width,c=new Float64Array(a*b),d=b;d--;)for(var e=a;e--;)c[d*a+e]=this.m[e*b+d];return new NLA.Matrix(a,b,c)},transpose:function(){for(var a=this.height,b=this.width,c=this.m,d=a;d--;)for(var e=Math.min(d,b);e--;){console.log("col",
e,"row",d);var f=c[d*b+e];c[d*b+e]=c[e*a+d];c[e*a+d]=f}this.width=a;this.height=b},isSquare:function(){return this.height==this.width},diagonal:function(){if(!this.isSquare())throw Error("!!");for(var a=new Float64Array(this.width),b=this.width*(this.width+1),c=this.width;c--;)b-=this.width+1,a[c]=this.m[b];return new NLA.Vector(a)},max:function(){return NLA.arrayMax(this.m)},min:function(){return NLA.arrayMin(this.m)},maxAbsColSum:function(){for(var a=0,b=this.width;b--;){for(var c=0,d=this.height;d--;)c+=
Math.abs(this.m(d*this.width+b));a=Math.max(a,c)}return a},maxAbsRowSum:function(){for(var a=0,b=this.height;b--;){for(var c=0,d=this.width;d--;)c+=Math.abs(this.m(b*this.width+d));a=Math.max(a,c)}return a},getTriangularDeterminant:function(){assert(this.isUpperTriangular()||this.isLowerTriangular(),"not a triangular matrix");for(var a=1,b=this.width*(this.width+1);b;)b-=this.width+1,a*=this.m[b];return a},getDeterminant:function(){return this.luDecomposition().U.getTriangularDeterminant()},hasFullRank:function(){return Math.min(this.width,
this.height)==this.rank()}};NLA.Vector.Zero=function(a){NLA.assertNumbers(a);var b=0;for(a=new Float64Array(a);b--;)a[b]=0;return new NLA.Vector(a)};NLA.Vector.Unit=function(a,b){NLA.assertNumbers(a,b);for(var c=0,d=new Float64Array(a);c--;)d[c]=+(c==b);return new NLA.Vector(d)};
NLA.combinations=function(a){function b(b,f){for(;;)switch(c){case 0:e=0;case 1:if(!(e<a)){c=3;break}d=e;case 4:if(!(d<a)){c=6;break}c=7;return{value:{i:e,j:d},done:!1};case 7:if(void 0===f){c=8;break}c=-1;throw f;case 8:case 5:d++;c=4;break;case 6:case 2:e++;c=1;break;case 3:c=-1;default:return{value:void 0,done:!0}}}var c=0,d,e,f={next:function(a){return b(a,void 0)},throw:function(a){return b(void 0,a)}};$jscomp.initSymbolIterator();f[Symbol.iterator]=function(){return this};return f};
function pqEquation(a,b){var c=a*a/4-b;if(c<-NLA.PRECISION)return[];if(c<=NLA.PRECISION)return[-a/2];c=Math.sqrt(c);return[-a/2-c,-a/2+c]}
function solveCubicReal2(a,b,c,d){if(NLA.isZero(a))return NLA.isZero(b)?[-d/c]:pqEquation(c/b,d/b);var e=a;a=b/e;b=c/e;c=(3*b-a*a)/3;var f=c/3;b=(2*a*a*a-9*a*b+d/e*27)/27;d=b/2;f=d*d+f*f*f;if(f<-NLA.PRECISION)return c=-c/3,c=Math.sqrt(c*c*c),f=-b/(2*c),b=Math.acos(-1>f?-1:1<f?1:f),d=2*Math.cbrt(c),c=d*Math.cos(b/3)-a/3,f=d*Math.cos((b+2*Math.PI)/3)-a/3,a=d*Math.cos((b+4*Math.PI)/3)-a/3,[c,f,a];if(f<=NLA.PRECISION)return c=0>d?Math.cbrt(-d):-Math.cbrt(d),[2*c-a/3,-c-a/3];f=Math.sqrt(f);c=Math.cbrt(-d+
f);return[c-Math.cbrt(d+f)-a/3]}NLA.Transformable=function(a){NLA.BaseObject.apply(this,arguments)};$jscomp.inherits(NLA.Transformable,NLA.BaseObject);NLA.Transformable.assign=NLA.BaseObject.assign;NLA.Transformable.isFrozen=NLA.BaseObject.isFrozen;NLA.Transformable.isSealed=NLA.BaseObject.isSealed;NLA.Transformable.isExtensible=NLA.BaseObject.isExtensible;NLA.Transformable.freeze=NLA.BaseObject.freeze;NLA.Transformable.seal=NLA.BaseObject.seal;NLA.Transformable.preventExtensions=NLA.BaseObject.preventExtensions;
NLA.Transformable.getPrototypeOf=NLA.BaseObject.getPrototypeOf;NLA.Transformable.getOwnPropertyNames=NLA.BaseObject.getOwnPropertyNames;NLA.Transformable.keys=NLA.BaseObject.keys;NLA.Transformable.getOwnPropertyDescriptor=NLA.BaseObject.getOwnPropertyDescriptor;NLA.Transformable.defineProperties=NLA.BaseObject.defineProperties;NLA.Transformable.defineProperty=NLA.BaseObject.defineProperty;NLA.Transformable.create=NLA.BaseObject.create;NLA.Transformable.prototype.mirrored=function(a){return this.transform(NLA.Matrix4x4.mirroring(a))};
NLA.Transformable.prototype.mirroredX=function(){return this.mirrored(NLA.Plane3.YZ)};NLA.Transformable.prototype.mirroredY=function(){return this.mirrored(NLA.Plane3.ZX)};NLA.Transformable.prototype.mirroredZ=function(){return this.mirrored(NLA.Plane3.XY)};NLA.Transformable.prototype.translate=function(a,b,c){return this.transform(NLA.Matrix4x4.translation(a,b,c))};NLA.Transformable.prototype.scale=function(a,b,c){return this.transform(NLA.Matrix4x4.scaling(a,b,c))};
NLA.Transformable.prototype.rotateX=function(a){return this.transform(NLA.Matrix4x4.rotationX(a))};NLA.Transformable.prototype.rotateY=function(a){return this.transform(NLA.Matrix4x4.rotationY(a))};NLA.Transformable.prototype.rotateZ=function(a){return this.transform(NLA.Matrix4x4.rotationZ(a))};NLA.Transformable.prototype.rotate=function(a,b,c){return this.transform(NLA.Matrix4x4.rotation(a,b,c))};
NLA.Transformable.prototype.eulerZXZ=function(a,b,c){return this.transform(NLA.Matrix4x4.eulerZXZ(a,b,c))};NLA.Transformable.prototype.project=function(a){return this.transform(NLA.Matrix4x4.projection(a))};NLA.Transformable.prototype.projXY=function(){return this.transform(NLA.Matrix4x4.projection(NLA.Plane3.XY))};NLA.Transformable.prototype.projYZ=function(){return this.transform(NLA.Matrix4x4.projection(NLA.Plane3.YZ))};NLA.Transformable.prototype.projZX=function(){return this.transform(NLA.Matrix4x4.projection(NLA.Plane3.ZX))};
NLA.Transformable.prototype.shearedX=function(a,b){return this.transform(NLA.Matrix4x4([1,a,b,0,0,1,0,0,0,0,1,0,0,0,0,1]))};NLA.Transformable.prototype.foo=function(){return this.transform(NLA.Matrix4x4.FOO)};NLA.Transformable.prototype.bar=function(){return this.transform(NLA.Matrix4x4.BAR)};NLA.addOwnProperties(Array.prototype,ARRAY_UTILITIES);
