var V3=function(a,b,c){if(3==arguments.length)return V3.create(parseFloat(a),parseFloat(b),parseFloat(c));if(2==arguments.length)return V3.create(parseFloat(a),parseFloat(b),0);if(1==arguments.length&&"object"==typeof a){if(a instanceof V3)return a;if(a instanceof Array||a instanceof Float32Array||a instanceof Float64Array){if(2==a.length)return V3.create(parseFloat(a[0]),parseFloat(a[1]),0);if(3==a.length)return V3.create(parseFloat(a[0]),parseFloat(a[1]),parseFloat(a[2]))}else if("x"in a&&"y"in
a)return"z"in a?V3.create(parseFloat(a.x),parseFloat(a.y),parseFloat(a.z)):V3.create(parseFloat(a.x),parseFloat(a.y),0)}throw Error("invalid arguments"+arguments);};V3.id=0;V3.create=function(a,b,c){assert(3==arguments.length);assertNumbers(a,b,c);var d=Object.create(V3.prototype);Object.defineProperties(d,{x:{value:a},y:{value:b},z:{value:c}});return d};
V3.prototype={perturbed:function(a,b){b=b||.8*NLA.PRECISION;return this.map(function(a){return a+(Math.random()-.5)*b})},e:function(a){assert(0<=a&&3>a);return 0==a?this.x:1==a?this.y:this.z},negated:function(){return V3.create(-this.x,-this.y,-this.z)},abs:function(){return V3.create(Math.abs(this.x),Math.abs(this.y),Math.abs(this.z))},plus:function(a){assert(a instanceof V3);return V3.create(this.x+a.x,this.y+a.y,this.z+a.z)},minus:function(a){assert(a instanceof V3);return V3.create(this.x-a.x,
this.y-a.y,this.z-a.z)},times:function(a){assertNumbers(a);return V3.create(this.x*a,this.y*a,this.z*a)},div:function(a){assertNumbers(a);return V3.create(this.x/a,this.y/a,this.z/a)},dot:function(a){assert(a instanceof V3,"a instanceof V3");return this.x*a.x+this.y*a.y+this.z*a.z},lerp:function(a,b){assert(a instanceof V3,"a instanceof V3");assertNumbers(b);assert(0<=b&&1>=b,"0 <= t && t <= 1");return this.plus(a.minus(this).times(b))},lengthSquared:function(){return this.dot(this)},distanceTo:function(a){assert(a instanceof
V3,"a instanceof V3");return Math.hypot(this.x-a.x,this.y-a.y,this.z-a.z)},distanceToSquared:function(a){assert(a instanceof V3,"a instanceof V3");return this.minus(a).lengthSquared()},multiply4x4:function(a){return a.leftMultiplyVector3(this)},randomNonParallelVector:function(){var a=this.abs();return a.x<=a.y&&a.x<=a.z?V3.X:a.y<=a.x&&a.y<=a.z?V3.Y:V3.Z},slerp:function(a,b){assert(a instanceof V3,"a instanceof V3");NLA.assertNumbers(b);assert(0<=b&&1>=b,"0 <= t && t <= 1");var c=Math.sin,d=this.angleTo(a);
return this.times(c((1-b)*d)/c(d)).plus(a.times(c(b*d)/c(d)))},min:function(a){return V3.create(Math.min(this.x,a.x),Math.min(this.y,a.y),Math.min(this.z,a.z))},max:function(a){return V3.create(Math.max(this.x,a.x),Math.max(this.y,a.y),Math.max(this.z,a.z))},equals:function(a){return this==a||this.x==a.x&&this.y==a.y&&this.z==a.z},cross:function(a){return V3.create(this.y*a.z-this.z*a.y,this.z*a.x-this.x*a.z,this.x*a.y-this.y*a.x)},unit:function(){return this.div(this.length())},minElement:function(){return Math.min(Math.min(this.x,
this.y),this.z)},maxElement:function(){return Math.max(Math.max(this.x,this.y),this.z)},toAngles:function(){return{theta:Math.atan2(this.z,this.x),phi:Math.asin(this.y/this.length())}},toArray:function(a){return[this.x,this.y,this.z].slice(0,a||3)},getPerpendicular:function(){if(NLA.isZero(this.x)&&NLA.isZero(this.y)){if(NLA.isZero(this.z))throw Error("zero vector");return V3.Y}return V3(-this.y,this.x,0)},dim:function(){return 3},els:function(){return[this.x,this.y,this.z]},angleXY:function(){return Math.atan2(this.y,
this.x)},lengthXY:function(){return Math.sqrt(this.x*this.x+this.y*this.y)},map:function(a){return V3.create(a(this.x),a(this.y),a(this.z))},toString:function(a){a=a||NLA.defaultRoundFunction;return"V3("+[this.x,this.y,this.z].map(a).join(", ")+")"},angleTo:function(a){assert(1==arguments.length);assert(a instanceof V3,"vector instanceof V3");assert(!this.isZero());assert(!a.isZero());return Math.acos(this.dot(a)/this.length()/a.length())},angleRelativeNormal:function(a,b){assert(2==arguments.length);
NLA.assertVectors(a,b);assert(b.hasLength(1));assert(a.isPerpendicularTo(b),"vector.isPerpendicularTo(normal1)");assert(this.isPerpendicularTo(b),"this.isPerpendicularTo(normal1)");return Math.atan2(this.cross(a).dot(b),this.dot(a))},isParallelTo:function(a){assert(a instanceof V3,"vector instanceof V3");assert(!this.isZero());assert(!a.isZero());var b=this.dot(a);return NLA.equals(this.lengthSquared()*a.lengthSquared(),b*b)},isPerpendicularTo:function(a){assert(a instanceof V3,"vector instanceof V3");
assert(!this.isZero(),"!this.isZero()");assert(!a.isZero(),"!vector.isZero()");return NLA.isZero(this.dot(a))},isReverseDirTo:function(a){assert(a instanceof V3,"vector instanceof V3");assert(!this.isZero());assert(!a.isZero());var b=this.dot(a);return NLA.equals(Math.sqrt(this.lengthSquared()*a.lengthSquared()),b)},length:function(){return Math.hypot(this.x,this.y,this.z)},isZero:function(){return this.like(V3.ZERO)},like:function(a){return a===this?!0:a instanceof V3?NLA.equals(this.x,a.x)&&NLA.equals(this.y,
a.y)&&NLA.equals(this.z,a.z):!1},likeOrReversed:function(a){return NLA.equals(Math.abs(this.dot(a)),Math.sqrt(this.lengthSquared()*a.lengthSquared()))},normalized:function(){assert(!this.isZero(),"cannot normalize zero vector");return this.div(this.length())},toLength:function(a){assertNumbers(a);return this.times(a/this.length())},projectedOn:function(a){assert(a instanceof V3,"b instanceof V3");return a.times(this.dot(a)/a.dot(a))},rejectedFrom:function(a){assert(a instanceof V3,"b instanceof V3");
return this.minus(a.times(this.dot(a)/a.dot(a)))},hasLength:function(a){NLA.assertNumbers(a);return NLA.equals(a,this.length())},absSum:function(){return Math.abs(this.x)+Math.abs(this.y)+Math.abs(this.z)},maxAbsElement:function(){return Math.max(Math.abs(this.x),Math.max(Math.abs(this.y),Math.abs(this.z)))},minAbsElement:function(){return Math.min(Math.abs(this.x),Math.min(Math.abs(this.y),Math.min(this.z)))},absMaxDim:function(){var a=Math.abs(this.x),b=Math.abs(this.y),c=Math.abs(this.z);return a>=
b?a>=c?0:2:b>=c?1:2},absMinDim:function(){var a=Math.abs(this.x),b=Math.abs(this.y),c=Math.abs(this.z);return a<b?a<c?0:2:b<c?1:2},transform:function(a){assert(a instanceof NLA.Matrix4x4);return a.transformPoint(this)},withElement:function(a,b){assert(["x","y","z"].includes(a),""+a);assertNumbers(b);return"x"==a?V3.create(b,this.y,this.z):"y"==a?V3.create(this.x,b,this.z):V3.create(this.x,this.y,b)},get ss(){return this.toString()},hashCode:function(){return~~(31*(31*~~(268435456*this.x)+~~(268435456*
this.y))+~~(268435456*this.z))},hashCodes:function(){var a=~~(31*(31*~~(268435456*this.x-.5)+~~(268435456*this.y-.5))+~~(268435456*this.z-.5));return[~~a,~~(a+961),~~(a+31),~~(a+31+961),~~(a+1),~~(a+1+961),~~(a+1+31),~~(a+1+31+961)]},compareTo2:function(a,b){b=b||0;return NLA.equals2(this.x,a.x,b)?NLA.equals2(this.y,a.y,b)?NLA.equals2(this.z,a.z,b)?0:this.z-a.z:this.y-a.y:this.x-a.x},compareTo:function(a){return this.x!=a.x?this.x-a.x:this.y!=a.y?this.y-a.y:this.z-a.z}};V3.prototype.toSource=V3.prototype.toString;
V3.random=function(){return V3(Math.random(),Math.random(),Math.random())};V3.randomUnit=function(){var a=2*Math.random()*Math.PI,b=2*Math.random()-1,c=Math.sqrt(1-b*b);return V3(c*Math.cos(a),c*Math.sin(a),b)};V3.fromAngles=function(a,b){return V3.create(Math.cos(a)*Math.cos(b),Math.sin(b),Math.sin(a)*Math.cos(b))};V3.fromFunction=function(a){return V3.create(a(0),a(1),a(2))};V3.ss=function(a){return a.ss};V3.min=function(a,b){return V3.create(Math.min(a.x,b.x),Math.min(a.y,b.y),Math.min(a.z,b.z))};
V3.max=function(a,b){return V3.create(Math.max(a.x,b.x),Math.max(a.y,b.y),Math.max(a.z,b.z))};V3.lerp=function(a,b,c){return b.minus(a).times(c).plus(a)};V3.fromArray=function(a){return V3.create(a[0],a[1],a[2])};V3.angleBetween=function(a,b){return a.angleTo(b)};
V3.zip=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];assert(a instanceof Function);return V3.create(a.apply(void 0,c.map(function(a){return a.x})),a.apply(void 0,c.map(function(a){return a.y})),a.apply(void 0,c.map(function(a){return a.z})))};V3.normalOnPoints=function(a,b,c){assert(a instanceof V3,"v0 instanceof V3");assert(b instanceof V3,""+b.toString());assert(c instanceof V3,"v2 instanceof V3");return b.minus(a).cross(c.minus(a))};
V3.add=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];assert(b.every(function(a){return a instanceof V3}));for(var d=c=0,f=0,e=b.length;e--;)c+=b[e].x,d+=b[e].y,f+=b[e].z;return V3.create(c,d,f)};V3.sub=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];assert(b.every(function(a){return a instanceof V3}));for(var c=b[0].x,d=b[0].y,f=b[0].z,e=b.length,e=1;e<b.length;e++)c-=b[e].x,d-=b[e].y,f-=b[e].z;return V3.create(c,d,f)};
V3.flattenV3Array=function(a,b,c,d,f){c=c||0;d=d||0;f=f||a.length-c;b=b||new Float32Array(3*f);assert(b.length-d>=f,"dest.length - destStart >= v3count");for(var e=0;e<f;e++){var g=a[c+e];b[d+3*e]=g.x;b[d+3*e+1]=g.y;b[d+3*e+2]=g.z}return b};V3.perturbed=function(a,b){return a.perturbed(b)};V3.polar=function(a,b){return V3.create(a*Math.cos(b),a*Math.sin(b),0)};V3.areDisjoint=function(a){for(var b=new NLA.CustomSet,c;c=a.next().value;)if(!c.equals(b.canonicalizeLike(c)))return!1;return!0};
V3.ZERO=V3.create(0,0,0);V3.X=V3.create(1,0,0);V3.Y=V3.create(0,1,0);V3.Z=V3.create(0,0,1);V3.INF=V3.create(Infinity,Infinity,Infinity);V3.XYZ=[V3.X,V3.Y,V3.Z];NLA.Vector3=V3;
